/*
Vio-V

Vio-V API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GroupSpray type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupSpray{}

// GroupSpray struct for GroupSpray
type GroupSpray struct {
	ID string `json:"ID"`
	GroupID int32 `json:"GroupID"`
	SprayObject string `json:"SprayObject"`
	Timestamp int32 `json:"Timestamp"`
}

type _GroupSpray GroupSpray

// NewGroupSpray instantiates a new GroupSpray object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupSpray(iD string, groupID int32, sprayObject string, timestamp int32) *GroupSpray {
	this := GroupSpray{}
	this.ID = iD
	this.GroupID = groupID
	this.SprayObject = sprayObject
	this.Timestamp = timestamp
	return &this
}

// NewGroupSprayWithDefaults instantiates a new GroupSpray object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupSprayWithDefaults() *GroupSpray {
	this := GroupSpray{}
	return &this
}

// GetID returns the ID field value
func (o *GroupSpray) GetID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ID
}

// GetIDOk returns a tuple with the ID field value
// and a boolean to check if the value has been set.
func (o *GroupSpray) GetIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ID, true
}

// SetID sets field value
func (o *GroupSpray) SetID(v string) {
	o.ID = v
}

// GetGroupID returns the GroupID field value
func (o *GroupSpray) GetGroupID() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.GroupID
}

// GetGroupIDOk returns a tuple with the GroupID field value
// and a boolean to check if the value has been set.
func (o *GroupSpray) GetGroupIDOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GroupID, true
}

// SetGroupID sets field value
func (o *GroupSpray) SetGroupID(v int32) {
	o.GroupID = v
}

// GetSprayObject returns the SprayObject field value
func (o *GroupSpray) GetSprayObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SprayObject
}

// GetSprayObjectOk returns a tuple with the SprayObject field value
// and a boolean to check if the value has been set.
func (o *GroupSpray) GetSprayObjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SprayObject, true
}

// SetSprayObject sets field value
func (o *GroupSpray) SetSprayObject(v string) {
	o.SprayObject = v
}

// GetTimestamp returns the Timestamp field value
func (o *GroupSpray) GetTimestamp() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *GroupSpray) GetTimestampOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *GroupSpray) SetTimestamp(v int32) {
	o.Timestamp = v
}

func (o GroupSpray) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupSpray) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ID"] = o.ID
	toSerialize["GroupID"] = o.GroupID
	toSerialize["SprayObject"] = o.SprayObject
	toSerialize["Timestamp"] = o.Timestamp
	return toSerialize, nil
}

func (o *GroupSpray) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ID",
		"GroupID",
		"SprayObject",
		"Timestamp",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGroupSpray := _GroupSpray{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGroupSpray)

	if err != nil {
		return err
	}

	*o = GroupSpray(varGroupSpray)

	return err
}

type NullableGroupSpray struct {
	value *GroupSpray
	isSet bool
}

func (v NullableGroupSpray) Get() *GroupSpray {
	return v.value
}

func (v *NullableGroupSpray) Set(val *GroupSpray) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupSpray) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupSpray) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupSpray(val *GroupSpray) *NullableGroupSpray {
	return &NullableGroupSpray{value: val, isSet: true}
}

func (v NullableGroupSpray) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupSpray) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


