/*
Vio-V

Vio-V API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GroupMember type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupMember{}

// GroupMember struct for GroupMember
type GroupMember struct {
	CharacterID int32 `json:"CharacterID"`
	GroupID int32 `json:"GroupID"`
	Rank int32 `json:"Rank"`
	Activity int32 `json:"Activity"`
	Name *string `json:"Name,omitempty"`
	Permissions string `json:"Permissions"`
	LastActivity int32 `json:"LastActivity"`
	Online int32 `json:"Online"`
}

type _GroupMember GroupMember

// NewGroupMember instantiates a new GroupMember object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupMember(characterID int32, groupID int32, rank int32, activity int32, permissions string, lastActivity int32, online int32) *GroupMember {
	this := GroupMember{}
	this.CharacterID = characterID
	this.GroupID = groupID
	this.Rank = rank
	this.Activity = activity
	this.Permissions = permissions
	this.LastActivity = lastActivity
	this.Online = online
	return &this
}

// NewGroupMemberWithDefaults instantiates a new GroupMember object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupMemberWithDefaults() *GroupMember {
	this := GroupMember{}
	return &this
}

// GetCharacterID returns the CharacterID field value
func (o *GroupMember) GetCharacterID() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CharacterID
}

// GetCharacterIDOk returns a tuple with the CharacterID field value
// and a boolean to check if the value has been set.
func (o *GroupMember) GetCharacterIDOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CharacterID, true
}

// SetCharacterID sets field value
func (o *GroupMember) SetCharacterID(v int32) {
	o.CharacterID = v
}

// GetGroupID returns the GroupID field value
func (o *GroupMember) GetGroupID() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.GroupID
}

// GetGroupIDOk returns a tuple with the GroupID field value
// and a boolean to check if the value has been set.
func (o *GroupMember) GetGroupIDOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GroupID, true
}

// SetGroupID sets field value
func (o *GroupMember) SetGroupID(v int32) {
	o.GroupID = v
}

// GetRank returns the Rank field value
func (o *GroupMember) GetRank() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Rank
}

// GetRankOk returns a tuple with the Rank field value
// and a boolean to check if the value has been set.
func (o *GroupMember) GetRankOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rank, true
}

// SetRank sets field value
func (o *GroupMember) SetRank(v int32) {
	o.Rank = v
}

// GetActivity returns the Activity field value
func (o *GroupMember) GetActivity() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Activity
}

// GetActivityOk returns a tuple with the Activity field value
// and a boolean to check if the value has been set.
func (o *GroupMember) GetActivityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Activity, true
}

// SetActivity sets field value
func (o *GroupMember) SetActivity(v int32) {
	o.Activity = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GroupMember) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupMember) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GroupMember) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GroupMember) SetName(v string) {
	o.Name = &v
}

// GetPermissions returns the Permissions field value
func (o *GroupMember) GetPermissions() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Permissions
}

// GetPermissionsOk returns a tuple with the Permissions field value
// and a boolean to check if the value has been set.
func (o *GroupMember) GetPermissionsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Permissions, true
}

// SetPermissions sets field value
func (o *GroupMember) SetPermissions(v string) {
	o.Permissions = v
}

// GetLastActivity returns the LastActivity field value
func (o *GroupMember) GetLastActivity() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.LastActivity
}

// GetLastActivityOk returns a tuple with the LastActivity field value
// and a boolean to check if the value has been set.
func (o *GroupMember) GetLastActivityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastActivity, true
}

// SetLastActivity sets field value
func (o *GroupMember) SetLastActivity(v int32) {
	o.LastActivity = v
}

// GetOnline returns the Online field value
func (o *GroupMember) GetOnline() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Online
}

// GetOnlineOk returns a tuple with the Online field value
// and a boolean to check if the value has been set.
func (o *GroupMember) GetOnlineOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Online, true
}

// SetOnline sets field value
func (o *GroupMember) SetOnline(v int32) {
	o.Online = v
}

func (o GroupMember) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupMember) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["CharacterID"] = o.CharacterID
	toSerialize["GroupID"] = o.GroupID
	toSerialize["Rank"] = o.Rank
	toSerialize["Activity"] = o.Activity
	if !IsNil(o.Name) {
		toSerialize["Name"] = o.Name
	}
	toSerialize["Permissions"] = o.Permissions
	toSerialize["LastActivity"] = o.LastActivity
	toSerialize["Online"] = o.Online
	return toSerialize, nil
}

func (o *GroupMember) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"CharacterID",
		"GroupID",
		"Rank",
		"Activity",
		"Permissions",
		"LastActivity",
		"Online",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGroupMember := _GroupMember{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGroupMember)

	if err != nil {
		return err
	}

	*o = GroupMember(varGroupMember)

	return err
}

type NullableGroupMember struct {
	value *GroupMember
	isSet bool
}

func (v NullableGroupMember) Get() *GroupMember {
	return v.value
}

func (v *NullableGroupMember) Set(val *GroupMember) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupMember) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupMember) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupMember(val *GroupMember) *NullableGroupMember {
	return &NullableGroupMember{value: val, isSet: true}
}

func (v NullableGroupMember) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupMember) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


