/*
Vio-V

Vio-V API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Character type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Character{}

// Character struct for Character
type Character struct {
	ID *int32 `json:"ID,omitempty"`
	AccountID int32 `json:"AccountID"`
	Name string `json:"Name"`
	Playingtime *int32 `json:"Playingtime,omitempty"`
	Gender int32 `json:"Gender"`
	STVO int32 `json:"STVO"`
	VehicleLimit int32 `json:"VehicleLimit"`
	BusExp *int32 `json:"BusExp,omitempty"`
	Spawn *string `json:"Spawn,omitempty"`
	SpawnID *int32 `json:"SpawnID,omitempty"`
	Wanteds *int32 `json:"Wanteds,omitempty"`
	JailTime *int32 `json:"JailTime,omitempty"`
	MethTime *int32 `json:"MethTime,omitempty"`
	WeaponLicenseA *int32 `json:"WeaponLicenseA,omitempty"`
	WeaponLicenseB *int32 `json:"WeaponLicenseB,omitempty"`
	WeaponLicenseC *int32 `json:"WeaponLicenseC,omitempty"`
	ActivityTimestamp *int32 `json:"ActivityTimestamp,omitempty"`
	QuestID string `json:"QuestID"`
	QuestStatus *int32 `json:"QuestStatus,omitempty"`
	PhoneNumber *int32 `json:"PhoneNumber,omitempty"`
	FactionTime *int32 `json:"FactionTime,omitempty"`
	Grade *float64 `json:"Grade,omitempty"`
	Raiting int32 `json:"Raiting"`
	DrivingLicenseA *int32 `json:"DrivingLicenseA,omitempty"`
	FoodStatus int32 `json:"FoodStatus"`
	ActivityStep int32 `json:"ActivityStep"`
	DrivingLicensesBlockedTimestamp *int32 `json:"DrivingLicensesBlockedTimestamp,omitempty"`
	WantedArchiv *string `json:"WantedArchiv,omitempty"`
	Skin *string `json:"Skin,omitempty"`
	Skills *string `json:"Skills,omitempty"`
	DailyQuests *string `json:"DailyQuests,omitempty"`
	BonusVehicleLimit *int32 `json:"BonusVehicleLimit,omitempty"`
	Accessory *string `json:"Accessory,omitempty"`
	Achievements *string `json:"Achievements,omitempty"`
	TotalStatus *string `json:"TotalStatus,omitempty"`
	ActiveStatus *string `json:"ActiveStatus,omitempty"`
	SkillPoints *string `json:"SkillPoints,omitempty"`
	SkillBranches *string `json:"SkillBranches,omitempty"`
	SkillSync int32 `json:"SkillSync"`
	ExpBoost *int32 `json:"ExpBoost,omitempty"`
	Tattoos *string `json:"Tattoos,omitempty"`
	Licenses *string `json:"Licenses,omitempty"`
	DailyBonus *string `json:"DailyBonus,omitempty"`
}

type _Character Character

// NewCharacter instantiates a new Character object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCharacter(accountID int32, name string, gender int32, sTVO int32, vehicleLimit int32, questID string, raiting int32, foodStatus int32, activityStep int32, skillSync int32) *Character {
	this := Character{}
	this.AccountID = accountID
	this.Name = name
	this.Gender = gender
	this.STVO = sTVO
	this.VehicleLimit = vehicleLimit
	this.QuestID = questID
	this.Raiting = raiting
	this.FoodStatus = foodStatus
	this.ActivityStep = activityStep
	this.SkillSync = skillSync
	return &this
}

// NewCharacterWithDefaults instantiates a new Character object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCharacterWithDefaults() *Character {
	this := Character{}
	return &this
}

// GetID returns the ID field value if set, zero value otherwise.
func (o *Character) GetID() int32 {
	if o == nil || IsNil(o.ID) {
		var ret int32
		return ret
	}
	return *o.ID
}

// GetIDOk returns a tuple with the ID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Character) GetIDOk() (*int32, bool) {
	if o == nil || IsNil(o.ID) {
		return nil, false
	}
	return o.ID, true
}

// HasID returns a boolean if a field has been set.
func (o *Character) HasID() bool {
	if o != nil && !IsNil(o.ID) {
		return true
	}

	return false
}

// SetID gets a reference to the given int32 and assigns it to the ID field.
func (o *Character) SetID(v int32) {
	o.ID = &v
}

// GetAccountID returns the AccountID field value
func (o *Character) GetAccountID() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AccountID
}

// GetAccountIDOk returns a tuple with the AccountID field value
// and a boolean to check if the value has been set.
func (o *Character) GetAccountIDOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountID, true
}

// SetAccountID sets field value
func (o *Character) SetAccountID(v int32) {
	o.AccountID = v
}

// GetName returns the Name field value
func (o *Character) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Character) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Character) SetName(v string) {
	o.Name = v
}

// GetPlayingtime returns the Playingtime field value if set, zero value otherwise.
func (o *Character) GetPlayingtime() int32 {
	if o == nil || IsNil(o.Playingtime) {
		var ret int32
		return ret
	}
	return *o.Playingtime
}

// GetPlayingtimeOk returns a tuple with the Playingtime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Character) GetPlayingtimeOk() (*int32, bool) {
	if o == nil || IsNil(o.Playingtime) {
		return nil, false
	}
	return o.Playingtime, true
}

// HasPlayingtime returns a boolean if a field has been set.
func (o *Character) HasPlayingtime() bool {
	if o != nil && !IsNil(o.Playingtime) {
		return true
	}

	return false
}

// SetPlayingtime gets a reference to the given int32 and assigns it to the Playingtime field.
func (o *Character) SetPlayingtime(v int32) {
	o.Playingtime = &v
}

// GetGender returns the Gender field value
func (o *Character) GetGender() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Gender
}

// GetGenderOk returns a tuple with the Gender field value
// and a boolean to check if the value has been set.
func (o *Character) GetGenderOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Gender, true
}

// SetGender sets field value
func (o *Character) SetGender(v int32) {
	o.Gender = v
}

// GetSTVO returns the STVO field value
func (o *Character) GetSTVO() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.STVO
}

// GetSTVOOk returns a tuple with the STVO field value
// and a boolean to check if the value has been set.
func (o *Character) GetSTVOOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.STVO, true
}

// SetSTVO sets field value
func (o *Character) SetSTVO(v int32) {
	o.STVO = v
}

// GetVehicleLimit returns the VehicleLimit field value
func (o *Character) GetVehicleLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.VehicleLimit
}

// GetVehicleLimitOk returns a tuple with the VehicleLimit field value
// and a boolean to check if the value has been set.
func (o *Character) GetVehicleLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VehicleLimit, true
}

// SetVehicleLimit sets field value
func (o *Character) SetVehicleLimit(v int32) {
	o.VehicleLimit = v
}

// GetBusExp returns the BusExp field value if set, zero value otherwise.
func (o *Character) GetBusExp() int32 {
	if o == nil || IsNil(o.BusExp) {
		var ret int32
		return ret
	}
	return *o.BusExp
}

// GetBusExpOk returns a tuple with the BusExp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Character) GetBusExpOk() (*int32, bool) {
	if o == nil || IsNil(o.BusExp) {
		return nil, false
	}
	return o.BusExp, true
}

// HasBusExp returns a boolean if a field has been set.
func (o *Character) HasBusExp() bool {
	if o != nil && !IsNil(o.BusExp) {
		return true
	}

	return false
}

// SetBusExp gets a reference to the given int32 and assigns it to the BusExp field.
func (o *Character) SetBusExp(v int32) {
	o.BusExp = &v
}

// GetSpawn returns the Spawn field value if set, zero value otherwise.
func (o *Character) GetSpawn() string {
	if o == nil || IsNil(o.Spawn) {
		var ret string
		return ret
	}
	return *o.Spawn
}

// GetSpawnOk returns a tuple with the Spawn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Character) GetSpawnOk() (*string, bool) {
	if o == nil || IsNil(o.Spawn) {
		return nil, false
	}
	return o.Spawn, true
}

// HasSpawn returns a boolean if a field has been set.
func (o *Character) HasSpawn() bool {
	if o != nil && !IsNil(o.Spawn) {
		return true
	}

	return false
}

// SetSpawn gets a reference to the given string and assigns it to the Spawn field.
func (o *Character) SetSpawn(v string) {
	o.Spawn = &v
}

// GetSpawnID returns the SpawnID field value if set, zero value otherwise.
func (o *Character) GetSpawnID() int32 {
	if o == nil || IsNil(o.SpawnID) {
		var ret int32
		return ret
	}
	return *o.SpawnID
}

// GetSpawnIDOk returns a tuple with the SpawnID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Character) GetSpawnIDOk() (*int32, bool) {
	if o == nil || IsNil(o.SpawnID) {
		return nil, false
	}
	return o.SpawnID, true
}

// HasSpawnID returns a boolean if a field has been set.
func (o *Character) HasSpawnID() bool {
	if o != nil && !IsNil(o.SpawnID) {
		return true
	}

	return false
}

// SetSpawnID gets a reference to the given int32 and assigns it to the SpawnID field.
func (o *Character) SetSpawnID(v int32) {
	o.SpawnID = &v
}

// GetWanteds returns the Wanteds field value if set, zero value otherwise.
func (o *Character) GetWanteds() int32 {
	if o == nil || IsNil(o.Wanteds) {
		var ret int32
		return ret
	}
	return *o.Wanteds
}

// GetWantedsOk returns a tuple with the Wanteds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Character) GetWantedsOk() (*int32, bool) {
	if o == nil || IsNil(o.Wanteds) {
		return nil, false
	}
	return o.Wanteds, true
}

// HasWanteds returns a boolean if a field has been set.
func (o *Character) HasWanteds() bool {
	if o != nil && !IsNil(o.Wanteds) {
		return true
	}

	return false
}

// SetWanteds gets a reference to the given int32 and assigns it to the Wanteds field.
func (o *Character) SetWanteds(v int32) {
	o.Wanteds = &v
}

// GetJailTime returns the JailTime field value if set, zero value otherwise.
func (o *Character) GetJailTime() int32 {
	if o == nil || IsNil(o.JailTime) {
		var ret int32
		return ret
	}
	return *o.JailTime
}

// GetJailTimeOk returns a tuple with the JailTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Character) GetJailTimeOk() (*int32, bool) {
	if o == nil || IsNil(o.JailTime) {
		return nil, false
	}
	return o.JailTime, true
}

// HasJailTime returns a boolean if a field has been set.
func (o *Character) HasJailTime() bool {
	if o != nil && !IsNil(o.JailTime) {
		return true
	}

	return false
}

// SetJailTime gets a reference to the given int32 and assigns it to the JailTime field.
func (o *Character) SetJailTime(v int32) {
	o.JailTime = &v
}

// GetMethTime returns the MethTime field value if set, zero value otherwise.
func (o *Character) GetMethTime() int32 {
	if o == nil || IsNil(o.MethTime) {
		var ret int32
		return ret
	}
	return *o.MethTime
}

// GetMethTimeOk returns a tuple with the MethTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Character) GetMethTimeOk() (*int32, bool) {
	if o == nil || IsNil(o.MethTime) {
		return nil, false
	}
	return o.MethTime, true
}

// HasMethTime returns a boolean if a field has been set.
func (o *Character) HasMethTime() bool {
	if o != nil && !IsNil(o.MethTime) {
		return true
	}

	return false
}

// SetMethTime gets a reference to the given int32 and assigns it to the MethTime field.
func (o *Character) SetMethTime(v int32) {
	o.MethTime = &v
}

// GetWeaponLicenseA returns the WeaponLicenseA field value if set, zero value otherwise.
func (o *Character) GetWeaponLicenseA() int32 {
	if o == nil || IsNil(o.WeaponLicenseA) {
		var ret int32
		return ret
	}
	return *o.WeaponLicenseA
}

// GetWeaponLicenseAOk returns a tuple with the WeaponLicenseA field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Character) GetWeaponLicenseAOk() (*int32, bool) {
	if o == nil || IsNil(o.WeaponLicenseA) {
		return nil, false
	}
	return o.WeaponLicenseA, true
}

// HasWeaponLicenseA returns a boolean if a field has been set.
func (o *Character) HasWeaponLicenseA() bool {
	if o != nil && !IsNil(o.WeaponLicenseA) {
		return true
	}

	return false
}

// SetWeaponLicenseA gets a reference to the given int32 and assigns it to the WeaponLicenseA field.
func (o *Character) SetWeaponLicenseA(v int32) {
	o.WeaponLicenseA = &v
}

// GetWeaponLicenseB returns the WeaponLicenseB field value if set, zero value otherwise.
func (o *Character) GetWeaponLicenseB() int32 {
	if o == nil || IsNil(o.WeaponLicenseB) {
		var ret int32
		return ret
	}
	return *o.WeaponLicenseB
}

// GetWeaponLicenseBOk returns a tuple with the WeaponLicenseB field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Character) GetWeaponLicenseBOk() (*int32, bool) {
	if o == nil || IsNil(o.WeaponLicenseB) {
		return nil, false
	}
	return o.WeaponLicenseB, true
}

// HasWeaponLicenseB returns a boolean if a field has been set.
func (o *Character) HasWeaponLicenseB() bool {
	if o != nil && !IsNil(o.WeaponLicenseB) {
		return true
	}

	return false
}

// SetWeaponLicenseB gets a reference to the given int32 and assigns it to the WeaponLicenseB field.
func (o *Character) SetWeaponLicenseB(v int32) {
	o.WeaponLicenseB = &v
}

// GetWeaponLicenseC returns the WeaponLicenseC field value if set, zero value otherwise.
func (o *Character) GetWeaponLicenseC() int32 {
	if o == nil || IsNil(o.WeaponLicenseC) {
		var ret int32
		return ret
	}
	return *o.WeaponLicenseC
}

// GetWeaponLicenseCOk returns a tuple with the WeaponLicenseC field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Character) GetWeaponLicenseCOk() (*int32, bool) {
	if o == nil || IsNil(o.WeaponLicenseC) {
		return nil, false
	}
	return o.WeaponLicenseC, true
}

// HasWeaponLicenseC returns a boolean if a field has been set.
func (o *Character) HasWeaponLicenseC() bool {
	if o != nil && !IsNil(o.WeaponLicenseC) {
		return true
	}

	return false
}

// SetWeaponLicenseC gets a reference to the given int32 and assigns it to the WeaponLicenseC field.
func (o *Character) SetWeaponLicenseC(v int32) {
	o.WeaponLicenseC = &v
}

// GetActivityTimestamp returns the ActivityTimestamp field value if set, zero value otherwise.
func (o *Character) GetActivityTimestamp() int32 {
	if o == nil || IsNil(o.ActivityTimestamp) {
		var ret int32
		return ret
	}
	return *o.ActivityTimestamp
}

// GetActivityTimestampOk returns a tuple with the ActivityTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Character) GetActivityTimestampOk() (*int32, bool) {
	if o == nil || IsNil(o.ActivityTimestamp) {
		return nil, false
	}
	return o.ActivityTimestamp, true
}

// HasActivityTimestamp returns a boolean if a field has been set.
func (o *Character) HasActivityTimestamp() bool {
	if o != nil && !IsNil(o.ActivityTimestamp) {
		return true
	}

	return false
}

// SetActivityTimestamp gets a reference to the given int32 and assigns it to the ActivityTimestamp field.
func (o *Character) SetActivityTimestamp(v int32) {
	o.ActivityTimestamp = &v
}

// GetQuestID returns the QuestID field value
func (o *Character) GetQuestID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QuestID
}

// GetQuestIDOk returns a tuple with the QuestID field value
// and a boolean to check if the value has been set.
func (o *Character) GetQuestIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuestID, true
}

// SetQuestID sets field value
func (o *Character) SetQuestID(v string) {
	o.QuestID = v
}

// GetQuestStatus returns the QuestStatus field value if set, zero value otherwise.
func (o *Character) GetQuestStatus() int32 {
	if o == nil || IsNil(o.QuestStatus) {
		var ret int32
		return ret
	}
	return *o.QuestStatus
}

// GetQuestStatusOk returns a tuple with the QuestStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Character) GetQuestStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.QuestStatus) {
		return nil, false
	}
	return o.QuestStatus, true
}

// HasQuestStatus returns a boolean if a field has been set.
func (o *Character) HasQuestStatus() bool {
	if o != nil && !IsNil(o.QuestStatus) {
		return true
	}

	return false
}

// SetQuestStatus gets a reference to the given int32 and assigns it to the QuestStatus field.
func (o *Character) SetQuestStatus(v int32) {
	o.QuestStatus = &v
}

// GetPhoneNumber returns the PhoneNumber field value if set, zero value otherwise.
func (o *Character) GetPhoneNumber() int32 {
	if o == nil || IsNil(o.PhoneNumber) {
		var ret int32
		return ret
	}
	return *o.PhoneNumber
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Character) GetPhoneNumberOk() (*int32, bool) {
	if o == nil || IsNil(o.PhoneNumber) {
		return nil, false
	}
	return o.PhoneNumber, true
}

// HasPhoneNumber returns a boolean if a field has been set.
func (o *Character) HasPhoneNumber() bool {
	if o != nil && !IsNil(o.PhoneNumber) {
		return true
	}

	return false
}

// SetPhoneNumber gets a reference to the given int32 and assigns it to the PhoneNumber field.
func (o *Character) SetPhoneNumber(v int32) {
	o.PhoneNumber = &v
}

// GetFactionTime returns the FactionTime field value if set, zero value otherwise.
func (o *Character) GetFactionTime() int32 {
	if o == nil || IsNil(o.FactionTime) {
		var ret int32
		return ret
	}
	return *o.FactionTime
}

// GetFactionTimeOk returns a tuple with the FactionTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Character) GetFactionTimeOk() (*int32, bool) {
	if o == nil || IsNil(o.FactionTime) {
		return nil, false
	}
	return o.FactionTime, true
}

// HasFactionTime returns a boolean if a field has been set.
func (o *Character) HasFactionTime() bool {
	if o != nil && !IsNil(o.FactionTime) {
		return true
	}

	return false
}

// SetFactionTime gets a reference to the given int32 and assigns it to the FactionTime field.
func (o *Character) SetFactionTime(v int32) {
	o.FactionTime = &v
}

// GetGrade returns the Grade field value if set, zero value otherwise.
func (o *Character) GetGrade() float64 {
	if o == nil || IsNil(o.Grade) {
		var ret float64
		return ret
	}
	return *o.Grade
}

// GetGradeOk returns a tuple with the Grade field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Character) GetGradeOk() (*float64, bool) {
	if o == nil || IsNil(o.Grade) {
		return nil, false
	}
	return o.Grade, true
}

// HasGrade returns a boolean if a field has been set.
func (o *Character) HasGrade() bool {
	if o != nil && !IsNil(o.Grade) {
		return true
	}

	return false
}

// SetGrade gets a reference to the given float64 and assigns it to the Grade field.
func (o *Character) SetGrade(v float64) {
	o.Grade = &v
}

// GetRaiting returns the Raiting field value
func (o *Character) GetRaiting() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Raiting
}

// GetRaitingOk returns a tuple with the Raiting field value
// and a boolean to check if the value has been set.
func (o *Character) GetRaitingOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Raiting, true
}

// SetRaiting sets field value
func (o *Character) SetRaiting(v int32) {
	o.Raiting = v
}

// GetDrivingLicenseA returns the DrivingLicenseA field value if set, zero value otherwise.
func (o *Character) GetDrivingLicenseA() int32 {
	if o == nil || IsNil(o.DrivingLicenseA) {
		var ret int32
		return ret
	}
	return *o.DrivingLicenseA
}

// GetDrivingLicenseAOk returns a tuple with the DrivingLicenseA field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Character) GetDrivingLicenseAOk() (*int32, bool) {
	if o == nil || IsNil(o.DrivingLicenseA) {
		return nil, false
	}
	return o.DrivingLicenseA, true
}

// HasDrivingLicenseA returns a boolean if a field has been set.
func (o *Character) HasDrivingLicenseA() bool {
	if o != nil && !IsNil(o.DrivingLicenseA) {
		return true
	}

	return false
}

// SetDrivingLicenseA gets a reference to the given int32 and assigns it to the DrivingLicenseA field.
func (o *Character) SetDrivingLicenseA(v int32) {
	o.DrivingLicenseA = &v
}

// GetFoodStatus returns the FoodStatus field value
func (o *Character) GetFoodStatus() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.FoodStatus
}

// GetFoodStatusOk returns a tuple with the FoodStatus field value
// and a boolean to check if the value has been set.
func (o *Character) GetFoodStatusOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FoodStatus, true
}

// SetFoodStatus sets field value
func (o *Character) SetFoodStatus(v int32) {
	o.FoodStatus = v
}

// GetActivityStep returns the ActivityStep field value
func (o *Character) GetActivityStep() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ActivityStep
}

// GetActivityStepOk returns a tuple with the ActivityStep field value
// and a boolean to check if the value has been set.
func (o *Character) GetActivityStepOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ActivityStep, true
}

// SetActivityStep sets field value
func (o *Character) SetActivityStep(v int32) {
	o.ActivityStep = v
}

// GetDrivingLicensesBlockedTimestamp returns the DrivingLicensesBlockedTimestamp field value if set, zero value otherwise.
func (o *Character) GetDrivingLicensesBlockedTimestamp() int32 {
	if o == nil || IsNil(o.DrivingLicensesBlockedTimestamp) {
		var ret int32
		return ret
	}
	return *o.DrivingLicensesBlockedTimestamp
}

// GetDrivingLicensesBlockedTimestampOk returns a tuple with the DrivingLicensesBlockedTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Character) GetDrivingLicensesBlockedTimestampOk() (*int32, bool) {
	if o == nil || IsNil(o.DrivingLicensesBlockedTimestamp) {
		return nil, false
	}
	return o.DrivingLicensesBlockedTimestamp, true
}

// HasDrivingLicensesBlockedTimestamp returns a boolean if a field has been set.
func (o *Character) HasDrivingLicensesBlockedTimestamp() bool {
	if o != nil && !IsNil(o.DrivingLicensesBlockedTimestamp) {
		return true
	}

	return false
}

// SetDrivingLicensesBlockedTimestamp gets a reference to the given int32 and assigns it to the DrivingLicensesBlockedTimestamp field.
func (o *Character) SetDrivingLicensesBlockedTimestamp(v int32) {
	o.DrivingLicensesBlockedTimestamp = &v
}

// GetWantedArchiv returns the WantedArchiv field value if set, zero value otherwise.
func (o *Character) GetWantedArchiv() string {
	if o == nil || IsNil(o.WantedArchiv) {
		var ret string
		return ret
	}
	return *o.WantedArchiv
}

// GetWantedArchivOk returns a tuple with the WantedArchiv field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Character) GetWantedArchivOk() (*string, bool) {
	if o == nil || IsNil(o.WantedArchiv) {
		return nil, false
	}
	return o.WantedArchiv, true
}

// HasWantedArchiv returns a boolean if a field has been set.
func (o *Character) HasWantedArchiv() bool {
	if o != nil && !IsNil(o.WantedArchiv) {
		return true
	}

	return false
}

// SetWantedArchiv gets a reference to the given string and assigns it to the WantedArchiv field.
func (o *Character) SetWantedArchiv(v string) {
	o.WantedArchiv = &v
}

// GetSkin returns the Skin field value if set, zero value otherwise.
func (o *Character) GetSkin() string {
	if o == nil || IsNil(o.Skin) {
		var ret string
		return ret
	}
	return *o.Skin
}

// GetSkinOk returns a tuple with the Skin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Character) GetSkinOk() (*string, bool) {
	if o == nil || IsNil(o.Skin) {
		return nil, false
	}
	return o.Skin, true
}

// HasSkin returns a boolean if a field has been set.
func (o *Character) HasSkin() bool {
	if o != nil && !IsNil(o.Skin) {
		return true
	}

	return false
}

// SetSkin gets a reference to the given string and assigns it to the Skin field.
func (o *Character) SetSkin(v string) {
	o.Skin = &v
}

// GetSkills returns the Skills field value if set, zero value otherwise.
func (o *Character) GetSkills() string {
	if o == nil || IsNil(o.Skills) {
		var ret string
		return ret
	}
	return *o.Skills
}

// GetSkillsOk returns a tuple with the Skills field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Character) GetSkillsOk() (*string, bool) {
	if o == nil || IsNil(o.Skills) {
		return nil, false
	}
	return o.Skills, true
}

// HasSkills returns a boolean if a field has been set.
func (o *Character) HasSkills() bool {
	if o != nil && !IsNil(o.Skills) {
		return true
	}

	return false
}

// SetSkills gets a reference to the given string and assigns it to the Skills field.
func (o *Character) SetSkills(v string) {
	o.Skills = &v
}

// GetDailyQuests returns the DailyQuests field value if set, zero value otherwise.
func (o *Character) GetDailyQuests() string {
	if o == nil || IsNil(o.DailyQuests) {
		var ret string
		return ret
	}
	return *o.DailyQuests
}

// GetDailyQuestsOk returns a tuple with the DailyQuests field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Character) GetDailyQuestsOk() (*string, bool) {
	if o == nil || IsNil(o.DailyQuests) {
		return nil, false
	}
	return o.DailyQuests, true
}

// HasDailyQuests returns a boolean if a field has been set.
func (o *Character) HasDailyQuests() bool {
	if o != nil && !IsNil(o.DailyQuests) {
		return true
	}

	return false
}

// SetDailyQuests gets a reference to the given string and assigns it to the DailyQuests field.
func (o *Character) SetDailyQuests(v string) {
	o.DailyQuests = &v
}

// GetBonusVehicleLimit returns the BonusVehicleLimit field value if set, zero value otherwise.
func (o *Character) GetBonusVehicleLimit() int32 {
	if o == nil || IsNil(o.BonusVehicleLimit) {
		var ret int32
		return ret
	}
	return *o.BonusVehicleLimit
}

// GetBonusVehicleLimitOk returns a tuple with the BonusVehicleLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Character) GetBonusVehicleLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.BonusVehicleLimit) {
		return nil, false
	}
	return o.BonusVehicleLimit, true
}

// HasBonusVehicleLimit returns a boolean if a field has been set.
func (o *Character) HasBonusVehicleLimit() bool {
	if o != nil && !IsNil(o.BonusVehicleLimit) {
		return true
	}

	return false
}

// SetBonusVehicleLimit gets a reference to the given int32 and assigns it to the BonusVehicleLimit field.
func (o *Character) SetBonusVehicleLimit(v int32) {
	o.BonusVehicleLimit = &v
}

// GetAccessory returns the Accessory field value if set, zero value otherwise.
func (o *Character) GetAccessory() string {
	if o == nil || IsNil(o.Accessory) {
		var ret string
		return ret
	}
	return *o.Accessory
}

// GetAccessoryOk returns a tuple with the Accessory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Character) GetAccessoryOk() (*string, bool) {
	if o == nil || IsNil(o.Accessory) {
		return nil, false
	}
	return o.Accessory, true
}

// HasAccessory returns a boolean if a field has been set.
func (o *Character) HasAccessory() bool {
	if o != nil && !IsNil(o.Accessory) {
		return true
	}

	return false
}

// SetAccessory gets a reference to the given string and assigns it to the Accessory field.
func (o *Character) SetAccessory(v string) {
	o.Accessory = &v
}

// GetAchievements returns the Achievements field value if set, zero value otherwise.
func (o *Character) GetAchievements() string {
	if o == nil || IsNil(o.Achievements) {
		var ret string
		return ret
	}
	return *o.Achievements
}

// GetAchievementsOk returns a tuple with the Achievements field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Character) GetAchievementsOk() (*string, bool) {
	if o == nil || IsNil(o.Achievements) {
		return nil, false
	}
	return o.Achievements, true
}

// HasAchievements returns a boolean if a field has been set.
func (o *Character) HasAchievements() bool {
	if o != nil && !IsNil(o.Achievements) {
		return true
	}

	return false
}

// SetAchievements gets a reference to the given string and assigns it to the Achievements field.
func (o *Character) SetAchievements(v string) {
	o.Achievements = &v
}

// GetTotalStatus returns the TotalStatus field value if set, zero value otherwise.
func (o *Character) GetTotalStatus() string {
	if o == nil || IsNil(o.TotalStatus) {
		var ret string
		return ret
	}
	return *o.TotalStatus
}

// GetTotalStatusOk returns a tuple with the TotalStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Character) GetTotalStatusOk() (*string, bool) {
	if o == nil || IsNil(o.TotalStatus) {
		return nil, false
	}
	return o.TotalStatus, true
}

// HasTotalStatus returns a boolean if a field has been set.
func (o *Character) HasTotalStatus() bool {
	if o != nil && !IsNil(o.TotalStatus) {
		return true
	}

	return false
}

// SetTotalStatus gets a reference to the given string and assigns it to the TotalStatus field.
func (o *Character) SetTotalStatus(v string) {
	o.TotalStatus = &v
}

// GetActiveStatus returns the ActiveStatus field value if set, zero value otherwise.
func (o *Character) GetActiveStatus() string {
	if o == nil || IsNil(o.ActiveStatus) {
		var ret string
		return ret
	}
	return *o.ActiveStatus
}

// GetActiveStatusOk returns a tuple with the ActiveStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Character) GetActiveStatusOk() (*string, bool) {
	if o == nil || IsNil(o.ActiveStatus) {
		return nil, false
	}
	return o.ActiveStatus, true
}

// HasActiveStatus returns a boolean if a field has been set.
func (o *Character) HasActiveStatus() bool {
	if o != nil && !IsNil(o.ActiveStatus) {
		return true
	}

	return false
}

// SetActiveStatus gets a reference to the given string and assigns it to the ActiveStatus field.
func (o *Character) SetActiveStatus(v string) {
	o.ActiveStatus = &v
}

// GetSkillPoints returns the SkillPoints field value if set, zero value otherwise.
func (o *Character) GetSkillPoints() string {
	if o == nil || IsNil(o.SkillPoints) {
		var ret string
		return ret
	}
	return *o.SkillPoints
}

// GetSkillPointsOk returns a tuple with the SkillPoints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Character) GetSkillPointsOk() (*string, bool) {
	if o == nil || IsNil(o.SkillPoints) {
		return nil, false
	}
	return o.SkillPoints, true
}

// HasSkillPoints returns a boolean if a field has been set.
func (o *Character) HasSkillPoints() bool {
	if o != nil && !IsNil(o.SkillPoints) {
		return true
	}

	return false
}

// SetSkillPoints gets a reference to the given string and assigns it to the SkillPoints field.
func (o *Character) SetSkillPoints(v string) {
	o.SkillPoints = &v
}

// GetSkillBranches returns the SkillBranches field value if set, zero value otherwise.
func (o *Character) GetSkillBranches() string {
	if o == nil || IsNil(o.SkillBranches) {
		var ret string
		return ret
	}
	return *o.SkillBranches
}

// GetSkillBranchesOk returns a tuple with the SkillBranches field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Character) GetSkillBranchesOk() (*string, bool) {
	if o == nil || IsNil(o.SkillBranches) {
		return nil, false
	}
	return o.SkillBranches, true
}

// HasSkillBranches returns a boolean if a field has been set.
func (o *Character) HasSkillBranches() bool {
	if o != nil && !IsNil(o.SkillBranches) {
		return true
	}

	return false
}

// SetSkillBranches gets a reference to the given string and assigns it to the SkillBranches field.
func (o *Character) SetSkillBranches(v string) {
	o.SkillBranches = &v
}

// GetSkillSync returns the SkillSync field value
func (o *Character) GetSkillSync() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SkillSync
}

// GetSkillSyncOk returns a tuple with the SkillSync field value
// and a boolean to check if the value has been set.
func (o *Character) GetSkillSyncOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SkillSync, true
}

// SetSkillSync sets field value
func (o *Character) SetSkillSync(v int32) {
	o.SkillSync = v
}

// GetExpBoost returns the ExpBoost field value if set, zero value otherwise.
func (o *Character) GetExpBoost() int32 {
	if o == nil || IsNil(o.ExpBoost) {
		var ret int32
		return ret
	}
	return *o.ExpBoost
}

// GetExpBoostOk returns a tuple with the ExpBoost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Character) GetExpBoostOk() (*int32, bool) {
	if o == nil || IsNil(o.ExpBoost) {
		return nil, false
	}
	return o.ExpBoost, true
}

// HasExpBoost returns a boolean if a field has been set.
func (o *Character) HasExpBoost() bool {
	if o != nil && !IsNil(o.ExpBoost) {
		return true
	}

	return false
}

// SetExpBoost gets a reference to the given int32 and assigns it to the ExpBoost field.
func (o *Character) SetExpBoost(v int32) {
	o.ExpBoost = &v
}

// GetTattoos returns the Tattoos field value if set, zero value otherwise.
func (o *Character) GetTattoos() string {
	if o == nil || IsNil(o.Tattoos) {
		var ret string
		return ret
	}
	return *o.Tattoos
}

// GetTattoosOk returns a tuple with the Tattoos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Character) GetTattoosOk() (*string, bool) {
	if o == nil || IsNil(o.Tattoos) {
		return nil, false
	}
	return o.Tattoos, true
}

// HasTattoos returns a boolean if a field has been set.
func (o *Character) HasTattoos() bool {
	if o != nil && !IsNil(o.Tattoos) {
		return true
	}

	return false
}

// SetTattoos gets a reference to the given string and assigns it to the Tattoos field.
func (o *Character) SetTattoos(v string) {
	o.Tattoos = &v
}

// GetLicenses returns the Licenses field value if set, zero value otherwise.
func (o *Character) GetLicenses() string {
	if o == nil || IsNil(o.Licenses) {
		var ret string
		return ret
	}
	return *o.Licenses
}

// GetLicensesOk returns a tuple with the Licenses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Character) GetLicensesOk() (*string, bool) {
	if o == nil || IsNil(o.Licenses) {
		return nil, false
	}
	return o.Licenses, true
}

// HasLicenses returns a boolean if a field has been set.
func (o *Character) HasLicenses() bool {
	if o != nil && !IsNil(o.Licenses) {
		return true
	}

	return false
}

// SetLicenses gets a reference to the given string and assigns it to the Licenses field.
func (o *Character) SetLicenses(v string) {
	o.Licenses = &v
}

// GetDailyBonus returns the DailyBonus field value if set, zero value otherwise.
func (o *Character) GetDailyBonus() string {
	if o == nil || IsNil(o.DailyBonus) {
		var ret string
		return ret
	}
	return *o.DailyBonus
}

// GetDailyBonusOk returns a tuple with the DailyBonus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Character) GetDailyBonusOk() (*string, bool) {
	if o == nil || IsNil(o.DailyBonus) {
		return nil, false
	}
	return o.DailyBonus, true
}

// HasDailyBonus returns a boolean if a field has been set.
func (o *Character) HasDailyBonus() bool {
	if o != nil && !IsNil(o.DailyBonus) {
		return true
	}

	return false
}

// SetDailyBonus gets a reference to the given string and assigns it to the DailyBonus field.
func (o *Character) SetDailyBonus(v string) {
	o.DailyBonus = &v
}

func (o Character) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Character) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ID) {
		toSerialize["ID"] = o.ID
	}
	toSerialize["AccountID"] = o.AccountID
	toSerialize["Name"] = o.Name
	if !IsNil(o.Playingtime) {
		toSerialize["Playingtime"] = o.Playingtime
	}
	toSerialize["Gender"] = o.Gender
	toSerialize["STVO"] = o.STVO
	toSerialize["VehicleLimit"] = o.VehicleLimit
	if !IsNil(o.BusExp) {
		toSerialize["BusExp"] = o.BusExp
	}
	if !IsNil(o.Spawn) {
		toSerialize["Spawn"] = o.Spawn
	}
	if !IsNil(o.SpawnID) {
		toSerialize["SpawnID"] = o.SpawnID
	}
	if !IsNil(o.Wanteds) {
		toSerialize["Wanteds"] = o.Wanteds
	}
	if !IsNil(o.JailTime) {
		toSerialize["JailTime"] = o.JailTime
	}
	if !IsNil(o.MethTime) {
		toSerialize["MethTime"] = o.MethTime
	}
	if !IsNil(o.WeaponLicenseA) {
		toSerialize["WeaponLicenseA"] = o.WeaponLicenseA
	}
	if !IsNil(o.WeaponLicenseB) {
		toSerialize["WeaponLicenseB"] = o.WeaponLicenseB
	}
	if !IsNil(o.WeaponLicenseC) {
		toSerialize["WeaponLicenseC"] = o.WeaponLicenseC
	}
	if !IsNil(o.ActivityTimestamp) {
		toSerialize["ActivityTimestamp"] = o.ActivityTimestamp
	}
	toSerialize["QuestID"] = o.QuestID
	if !IsNil(o.QuestStatus) {
		toSerialize["QuestStatus"] = o.QuestStatus
	}
	if !IsNil(o.PhoneNumber) {
		toSerialize["PhoneNumber"] = o.PhoneNumber
	}
	if !IsNil(o.FactionTime) {
		toSerialize["FactionTime"] = o.FactionTime
	}
	if !IsNil(o.Grade) {
		toSerialize["Grade"] = o.Grade
	}
	toSerialize["Raiting"] = o.Raiting
	if !IsNil(o.DrivingLicenseA) {
		toSerialize["DrivingLicenseA"] = o.DrivingLicenseA
	}
	toSerialize["FoodStatus"] = o.FoodStatus
	toSerialize["ActivityStep"] = o.ActivityStep
	if !IsNil(o.DrivingLicensesBlockedTimestamp) {
		toSerialize["DrivingLicensesBlockedTimestamp"] = o.DrivingLicensesBlockedTimestamp
	}
	if !IsNil(o.WantedArchiv) {
		toSerialize["WantedArchiv"] = o.WantedArchiv
	}
	if !IsNil(o.Skin) {
		toSerialize["Skin"] = o.Skin
	}
	if !IsNil(o.Skills) {
		toSerialize["Skills"] = o.Skills
	}
	if !IsNil(o.DailyQuests) {
		toSerialize["DailyQuests"] = o.DailyQuests
	}
	if !IsNil(o.BonusVehicleLimit) {
		toSerialize["BonusVehicleLimit"] = o.BonusVehicleLimit
	}
	if !IsNil(o.Accessory) {
		toSerialize["Accessory"] = o.Accessory
	}
	if !IsNil(o.Achievements) {
		toSerialize["Achievements"] = o.Achievements
	}
	if !IsNil(o.TotalStatus) {
		toSerialize["TotalStatus"] = o.TotalStatus
	}
	if !IsNil(o.ActiveStatus) {
		toSerialize["ActiveStatus"] = o.ActiveStatus
	}
	if !IsNil(o.SkillPoints) {
		toSerialize["SkillPoints"] = o.SkillPoints
	}
	if !IsNil(o.SkillBranches) {
		toSerialize["SkillBranches"] = o.SkillBranches
	}
	toSerialize["SkillSync"] = o.SkillSync
	if !IsNil(o.ExpBoost) {
		toSerialize["ExpBoost"] = o.ExpBoost
	}
	if !IsNil(o.Tattoos) {
		toSerialize["Tattoos"] = o.Tattoos
	}
	if !IsNil(o.Licenses) {
		toSerialize["Licenses"] = o.Licenses
	}
	if !IsNil(o.DailyBonus) {
		toSerialize["DailyBonus"] = o.DailyBonus
	}
	return toSerialize, nil
}

func (o *Character) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"AccountID",
		"Name",
		"Gender",
		"STVO",
		"VehicleLimit",
		"QuestID",
		"Raiting",
		"FoodStatus",
		"ActivityStep",
		"SkillSync",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCharacter := _Character{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCharacter)

	if err != nil {
		return err
	}

	*o = Character(varCharacter)

	return err
}

type NullableCharacter struct {
	value *Character
	isSet bool
}

func (v NullableCharacter) Get() *Character {
	return v.value
}

func (v *NullableCharacter) Set(val *Character) {
	v.value = val
	v.isSet = true
}

func (v NullableCharacter) IsSet() bool {
	return v.isSet
}

func (v *NullableCharacter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCharacter(val *Character) *NullableCharacter {
	return &NullableCharacter{value: val, isSet: true}
}

func (v NullableCharacter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCharacter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


