/*
Vio-V

Vio-V API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GroupSkin type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupSkin{}

// GroupSkin struct for GroupSkin
type GroupSkin struct {
	GangID int32 `json:"GangID"`
	Torso int32 `json:"Torso"`
	TorsoTexture int32 `json:"TorsoTexture"`
	Legs int32 `json:"Legs"`
	LegsTexture int32 `json:"LegsTexture"`
	Feet int32 `json:"Feet"`
	FeetTexture int32 `json:"FeetTexture"`
	Accessories int32 `json:"Accessories"`
	Undershirt int32 `json:"Undershirt"`
	UndershirtTexture int32 `json:"UndershirtTexture"`
	Tops int32 `json:"Tops"`
	TopsTexture int32 `json:"TopsTexture"`
	Gender int32 `json:"Gender"`
	PrimKey *int32 `json:"PrimKey,omitempty"`
}

type _GroupSkin GroupSkin

// NewGroupSkin instantiates a new GroupSkin object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupSkin(gangID int32, torso int32, torsoTexture int32, legs int32, legsTexture int32, feet int32, feetTexture int32, accessories int32, undershirt int32, undershirtTexture int32, tops int32, topsTexture int32, gender int32) *GroupSkin {
	this := GroupSkin{}
	this.GangID = gangID
	this.Torso = torso
	this.TorsoTexture = torsoTexture
	this.Legs = legs
	this.LegsTexture = legsTexture
	this.Feet = feet
	this.FeetTexture = feetTexture
	this.Accessories = accessories
	this.Undershirt = undershirt
	this.UndershirtTexture = undershirtTexture
	this.Tops = tops
	this.TopsTexture = topsTexture
	this.Gender = gender
	return &this
}

// NewGroupSkinWithDefaults instantiates a new GroupSkin object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupSkinWithDefaults() *GroupSkin {
	this := GroupSkin{}
	return &this
}

// GetGangID returns the GangID field value
func (o *GroupSkin) GetGangID() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.GangID
}

// GetGangIDOk returns a tuple with the GangID field value
// and a boolean to check if the value has been set.
func (o *GroupSkin) GetGangIDOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GangID, true
}

// SetGangID sets field value
func (o *GroupSkin) SetGangID(v int32) {
	o.GangID = v
}

// GetTorso returns the Torso field value
func (o *GroupSkin) GetTorso() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Torso
}

// GetTorsoOk returns a tuple with the Torso field value
// and a boolean to check if the value has been set.
func (o *GroupSkin) GetTorsoOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Torso, true
}

// SetTorso sets field value
func (o *GroupSkin) SetTorso(v int32) {
	o.Torso = v
}

// GetTorsoTexture returns the TorsoTexture field value
func (o *GroupSkin) GetTorsoTexture() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TorsoTexture
}

// GetTorsoTextureOk returns a tuple with the TorsoTexture field value
// and a boolean to check if the value has been set.
func (o *GroupSkin) GetTorsoTextureOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TorsoTexture, true
}

// SetTorsoTexture sets field value
func (o *GroupSkin) SetTorsoTexture(v int32) {
	o.TorsoTexture = v
}

// GetLegs returns the Legs field value
func (o *GroupSkin) GetLegs() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Legs
}

// GetLegsOk returns a tuple with the Legs field value
// and a boolean to check if the value has been set.
func (o *GroupSkin) GetLegsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Legs, true
}

// SetLegs sets field value
func (o *GroupSkin) SetLegs(v int32) {
	o.Legs = v
}

// GetLegsTexture returns the LegsTexture field value
func (o *GroupSkin) GetLegsTexture() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.LegsTexture
}

// GetLegsTextureOk returns a tuple with the LegsTexture field value
// and a boolean to check if the value has been set.
func (o *GroupSkin) GetLegsTextureOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LegsTexture, true
}

// SetLegsTexture sets field value
func (o *GroupSkin) SetLegsTexture(v int32) {
	o.LegsTexture = v
}

// GetFeet returns the Feet field value
func (o *GroupSkin) GetFeet() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Feet
}

// GetFeetOk returns a tuple with the Feet field value
// and a boolean to check if the value has been set.
func (o *GroupSkin) GetFeetOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Feet, true
}

// SetFeet sets field value
func (o *GroupSkin) SetFeet(v int32) {
	o.Feet = v
}

// GetFeetTexture returns the FeetTexture field value
func (o *GroupSkin) GetFeetTexture() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.FeetTexture
}

// GetFeetTextureOk returns a tuple with the FeetTexture field value
// and a boolean to check if the value has been set.
func (o *GroupSkin) GetFeetTextureOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FeetTexture, true
}

// SetFeetTexture sets field value
func (o *GroupSkin) SetFeetTexture(v int32) {
	o.FeetTexture = v
}

// GetAccessories returns the Accessories field value
func (o *GroupSkin) GetAccessories() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Accessories
}

// GetAccessoriesOk returns a tuple with the Accessories field value
// and a boolean to check if the value has been set.
func (o *GroupSkin) GetAccessoriesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Accessories, true
}

// SetAccessories sets field value
func (o *GroupSkin) SetAccessories(v int32) {
	o.Accessories = v
}

// GetUndershirt returns the Undershirt field value
func (o *GroupSkin) GetUndershirt() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Undershirt
}

// GetUndershirtOk returns a tuple with the Undershirt field value
// and a boolean to check if the value has been set.
func (o *GroupSkin) GetUndershirtOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Undershirt, true
}

// SetUndershirt sets field value
func (o *GroupSkin) SetUndershirt(v int32) {
	o.Undershirt = v
}

// GetUndershirtTexture returns the UndershirtTexture field value
func (o *GroupSkin) GetUndershirtTexture() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.UndershirtTexture
}

// GetUndershirtTextureOk returns a tuple with the UndershirtTexture field value
// and a boolean to check if the value has been set.
func (o *GroupSkin) GetUndershirtTextureOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UndershirtTexture, true
}

// SetUndershirtTexture sets field value
func (o *GroupSkin) SetUndershirtTexture(v int32) {
	o.UndershirtTexture = v
}

// GetTops returns the Tops field value
func (o *GroupSkin) GetTops() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Tops
}

// GetTopsOk returns a tuple with the Tops field value
// and a boolean to check if the value has been set.
func (o *GroupSkin) GetTopsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tops, true
}

// SetTops sets field value
func (o *GroupSkin) SetTops(v int32) {
	o.Tops = v
}

// GetTopsTexture returns the TopsTexture field value
func (o *GroupSkin) GetTopsTexture() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TopsTexture
}

// GetTopsTextureOk returns a tuple with the TopsTexture field value
// and a boolean to check if the value has been set.
func (o *GroupSkin) GetTopsTextureOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TopsTexture, true
}

// SetTopsTexture sets field value
func (o *GroupSkin) SetTopsTexture(v int32) {
	o.TopsTexture = v
}

// GetGender returns the Gender field value
func (o *GroupSkin) GetGender() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Gender
}

// GetGenderOk returns a tuple with the Gender field value
// and a boolean to check if the value has been set.
func (o *GroupSkin) GetGenderOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Gender, true
}

// SetGender sets field value
func (o *GroupSkin) SetGender(v int32) {
	o.Gender = v
}

// GetPrimKey returns the PrimKey field value if set, zero value otherwise.
func (o *GroupSkin) GetPrimKey() int32 {
	if o == nil || IsNil(o.PrimKey) {
		var ret int32
		return ret
	}
	return *o.PrimKey
}

// GetPrimKeyOk returns a tuple with the PrimKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupSkin) GetPrimKeyOk() (*int32, bool) {
	if o == nil || IsNil(o.PrimKey) {
		return nil, false
	}
	return o.PrimKey, true
}

// HasPrimKey returns a boolean if a field has been set.
func (o *GroupSkin) HasPrimKey() bool {
	if o != nil && !IsNil(o.PrimKey) {
		return true
	}

	return false
}

// SetPrimKey gets a reference to the given int32 and assigns it to the PrimKey field.
func (o *GroupSkin) SetPrimKey(v int32) {
	o.PrimKey = &v
}

func (o GroupSkin) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupSkin) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["GangID"] = o.GangID
	toSerialize["Torso"] = o.Torso
	toSerialize["TorsoTexture"] = o.TorsoTexture
	toSerialize["Legs"] = o.Legs
	toSerialize["LegsTexture"] = o.LegsTexture
	toSerialize["Feet"] = o.Feet
	toSerialize["FeetTexture"] = o.FeetTexture
	toSerialize["Accessories"] = o.Accessories
	toSerialize["Undershirt"] = o.Undershirt
	toSerialize["UndershirtTexture"] = o.UndershirtTexture
	toSerialize["Tops"] = o.Tops
	toSerialize["TopsTexture"] = o.TopsTexture
	toSerialize["Gender"] = o.Gender
	if !IsNil(o.PrimKey) {
		toSerialize["PrimKey"] = o.PrimKey
	}
	return toSerialize, nil
}

func (o *GroupSkin) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"GangID",
		"Torso",
		"TorsoTexture",
		"Legs",
		"LegsTexture",
		"Feet",
		"FeetTexture",
		"Accessories",
		"Undershirt",
		"UndershirtTexture",
		"Tops",
		"TopsTexture",
		"Gender",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGroupSkin := _GroupSkin{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGroupSkin)

	if err != nil {
		return err
	}

	*o = GroupSkin(varGroupSkin)

	return err
}

type NullableGroupSkin struct {
	value *GroupSkin
	isSet bool
}

func (v NullableGroupSkin) Get() *GroupSkin {
	return v.value
}

func (v *NullableGroupSkin) Set(val *GroupSkin) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupSkin) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupSkin) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupSkin(val *GroupSkin) *NullableGroupSkin {
	return &NullableGroupSkin{value: val, isSet: true}
}

func (v NullableGroupSkin) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupSkin) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


