/*
Vio-V

Vio-V API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Group type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Group{}

// Group struct for Group
type Group struct {
	ID int32 `json:"ID"`
	Name string `json:"Name"`
	Exp int32 `json:"Exp"`
	Level int32 `json:"Level"`
	Server int32 `json:"Server"`
	Msg string `json:"Msg"`
	R *int32 `json:"R,omitempty"`
	G int32 `json:"G"`
	B *int32 `json:"B,omitempty"`
	ChatR int32 `json:"Chat_R"`
	ChatG int32 `json:"Chat_G"`
	ChatB int32 `json:"Chat_B"`
	Memberlimit int32 `json:"Memberlimit"`
	Tag int32 `json:"Tag"`
	Rang0 string `json:"Rang0"`
	Rang1 string `json:"Rang1"`
	Rang2 *string `json:"Rang2,omitempty"`
	Rang3 *string `json:"Rang3,omitempty"`
	Rang4 string `json:"Rang4"`
	Rang5 string `json:"Rang5"`
	LastExp int32 `json:"LastExp"`
	R2 int32 `json:"R2"`
	G2 int32 `json:"G2"`
	B2 int32 `json:"B2"`
	Type string `json:"Type"`
	Boost1 int32 `json:"Boost1"`
	SkinMale string `json:"SkinMale"`
	SkinFemale string `json:"SkinFemale"`
	Boosts string `json:"Boosts"`
	Relationships string `json:"Relationships"`
	CraftingStorage *int32 `json:"CraftingStorage,omitempty"`
}

type _Group Group

// NewGroup instantiates a new Group object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroup(iD int32, name string, exp int32, level int32, server int32, msg string, g int32, chatR int32, chatG int32, chatB int32, memberlimit int32, tag int32, rang0 string, rang1 string, rang4 string, rang5 string, lastExp int32, r2 int32, g2 int32, b2 int32, type_ string, boost1 int32, skinMale string, skinFemale string, boosts string, relationships string) *Group {
	this := Group{}
	this.ID = iD
	this.Name = name
	this.Exp = exp
	this.Level = level
	this.Server = server
	this.Msg = msg
	this.G = g
	this.ChatR = chatR
	this.ChatG = chatG
	this.ChatB = chatB
	this.Memberlimit = memberlimit
	this.Tag = tag
	this.Rang0 = rang0
	this.Rang1 = rang1
	this.Rang4 = rang4
	this.Rang5 = rang5
	this.LastExp = lastExp
	this.R2 = r2
	this.G2 = g2
	this.B2 = b2
	this.Type = type_
	this.Boost1 = boost1
	this.SkinMale = skinMale
	this.SkinFemale = skinFemale
	this.Boosts = boosts
	this.Relationships = relationships
	return &this
}

// NewGroupWithDefaults instantiates a new Group object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupWithDefaults() *Group {
	this := Group{}
	return &this
}

// GetID returns the ID field value
func (o *Group) GetID() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ID
}

// GetIDOk returns a tuple with the ID field value
// and a boolean to check if the value has been set.
func (o *Group) GetIDOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ID, true
}

// SetID sets field value
func (o *Group) SetID(v int32) {
	o.ID = v
}

// GetName returns the Name field value
func (o *Group) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Group) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Group) SetName(v string) {
	o.Name = v
}

// GetExp returns the Exp field value
func (o *Group) GetExp() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Exp
}

// GetExpOk returns a tuple with the Exp field value
// and a boolean to check if the value has been set.
func (o *Group) GetExpOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Exp, true
}

// SetExp sets field value
func (o *Group) SetExp(v int32) {
	o.Exp = v
}

// GetLevel returns the Level field value
func (o *Group) GetLevel() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Level
}

// GetLevelOk returns a tuple with the Level field value
// and a boolean to check if the value has been set.
func (o *Group) GetLevelOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Level, true
}

// SetLevel sets field value
func (o *Group) SetLevel(v int32) {
	o.Level = v
}

// GetServer returns the Server field value
func (o *Group) GetServer() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Server
}

// GetServerOk returns a tuple with the Server field value
// and a boolean to check if the value has been set.
func (o *Group) GetServerOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Server, true
}

// SetServer sets field value
func (o *Group) SetServer(v int32) {
	o.Server = v
}

// GetMsg returns the Msg field value
func (o *Group) GetMsg() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Msg
}

// GetMsgOk returns a tuple with the Msg field value
// and a boolean to check if the value has been set.
func (o *Group) GetMsgOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Msg, true
}

// SetMsg sets field value
func (o *Group) SetMsg(v string) {
	o.Msg = v
}

// GetR returns the R field value if set, zero value otherwise.
func (o *Group) GetR() int32 {
	if o == nil || IsNil(o.R) {
		var ret int32
		return ret
	}
	return *o.R
}

// GetROk returns a tuple with the R field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Group) GetROk() (*int32, bool) {
	if o == nil || IsNil(o.R) {
		return nil, false
	}
	return o.R, true
}

// HasR returns a boolean if a field has been set.
func (o *Group) HasR() bool {
	if o != nil && !IsNil(o.R) {
		return true
	}

	return false
}

// SetR gets a reference to the given int32 and assigns it to the R field.
func (o *Group) SetR(v int32) {
	o.R = &v
}

// GetG returns the G field value
func (o *Group) GetG() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.G
}

// GetGOk returns a tuple with the G field value
// and a boolean to check if the value has been set.
func (o *Group) GetGOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.G, true
}

// SetG sets field value
func (o *Group) SetG(v int32) {
	o.G = v
}

// GetB returns the B field value if set, zero value otherwise.
func (o *Group) GetB() int32 {
	if o == nil || IsNil(o.B) {
		var ret int32
		return ret
	}
	return *o.B
}

// GetBOk returns a tuple with the B field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Group) GetBOk() (*int32, bool) {
	if o == nil || IsNil(o.B) {
		return nil, false
	}
	return o.B, true
}

// HasB returns a boolean if a field has been set.
func (o *Group) HasB() bool {
	if o != nil && !IsNil(o.B) {
		return true
	}

	return false
}

// SetB gets a reference to the given int32 and assigns it to the B field.
func (o *Group) SetB(v int32) {
	o.B = &v
}

// GetChatR returns the ChatR field value
func (o *Group) GetChatR() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ChatR
}

// GetChatROk returns a tuple with the ChatR field value
// and a boolean to check if the value has been set.
func (o *Group) GetChatROk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChatR, true
}

// SetChatR sets field value
func (o *Group) SetChatR(v int32) {
	o.ChatR = v
}

// GetChatG returns the ChatG field value
func (o *Group) GetChatG() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ChatG
}

// GetChatGOk returns a tuple with the ChatG field value
// and a boolean to check if the value has been set.
func (o *Group) GetChatGOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChatG, true
}

// SetChatG sets field value
func (o *Group) SetChatG(v int32) {
	o.ChatG = v
}

// GetChatB returns the ChatB field value
func (o *Group) GetChatB() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ChatB
}

// GetChatBOk returns a tuple with the ChatB field value
// and a boolean to check if the value has been set.
func (o *Group) GetChatBOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChatB, true
}

// SetChatB sets field value
func (o *Group) SetChatB(v int32) {
	o.ChatB = v
}

// GetMemberlimit returns the Memberlimit field value
func (o *Group) GetMemberlimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Memberlimit
}

// GetMemberlimitOk returns a tuple with the Memberlimit field value
// and a boolean to check if the value has been set.
func (o *Group) GetMemberlimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Memberlimit, true
}

// SetMemberlimit sets field value
func (o *Group) SetMemberlimit(v int32) {
	o.Memberlimit = v
}

// GetTag returns the Tag field value
func (o *Group) GetTag() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Tag
}

// GetTagOk returns a tuple with the Tag field value
// and a boolean to check if the value has been set.
func (o *Group) GetTagOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tag, true
}

// SetTag sets field value
func (o *Group) SetTag(v int32) {
	o.Tag = v
}

// GetRang0 returns the Rang0 field value
func (o *Group) GetRang0() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Rang0
}

// GetRang0Ok returns a tuple with the Rang0 field value
// and a boolean to check if the value has been set.
func (o *Group) GetRang0Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rang0, true
}

// SetRang0 sets field value
func (o *Group) SetRang0(v string) {
	o.Rang0 = v
}

// GetRang1 returns the Rang1 field value
func (o *Group) GetRang1() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Rang1
}

// GetRang1Ok returns a tuple with the Rang1 field value
// and a boolean to check if the value has been set.
func (o *Group) GetRang1Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rang1, true
}

// SetRang1 sets field value
func (o *Group) SetRang1(v string) {
	o.Rang1 = v
}

// GetRang2 returns the Rang2 field value if set, zero value otherwise.
func (o *Group) GetRang2() string {
	if o == nil || IsNil(o.Rang2) {
		var ret string
		return ret
	}
	return *o.Rang2
}

// GetRang2Ok returns a tuple with the Rang2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Group) GetRang2Ok() (*string, bool) {
	if o == nil || IsNil(o.Rang2) {
		return nil, false
	}
	return o.Rang2, true
}

// HasRang2 returns a boolean if a field has been set.
func (o *Group) HasRang2() bool {
	if o != nil && !IsNil(o.Rang2) {
		return true
	}

	return false
}

// SetRang2 gets a reference to the given string and assigns it to the Rang2 field.
func (o *Group) SetRang2(v string) {
	o.Rang2 = &v
}

// GetRang3 returns the Rang3 field value if set, zero value otherwise.
func (o *Group) GetRang3() string {
	if o == nil || IsNil(o.Rang3) {
		var ret string
		return ret
	}
	return *o.Rang3
}

// GetRang3Ok returns a tuple with the Rang3 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Group) GetRang3Ok() (*string, bool) {
	if o == nil || IsNil(o.Rang3) {
		return nil, false
	}
	return o.Rang3, true
}

// HasRang3 returns a boolean if a field has been set.
func (o *Group) HasRang3() bool {
	if o != nil && !IsNil(o.Rang3) {
		return true
	}

	return false
}

// SetRang3 gets a reference to the given string and assigns it to the Rang3 field.
func (o *Group) SetRang3(v string) {
	o.Rang3 = &v
}

// GetRang4 returns the Rang4 field value
func (o *Group) GetRang4() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Rang4
}

// GetRang4Ok returns a tuple with the Rang4 field value
// and a boolean to check if the value has been set.
func (o *Group) GetRang4Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rang4, true
}

// SetRang4 sets field value
func (o *Group) SetRang4(v string) {
	o.Rang4 = v
}

// GetRang5 returns the Rang5 field value
func (o *Group) GetRang5() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Rang5
}

// GetRang5Ok returns a tuple with the Rang5 field value
// and a boolean to check if the value has been set.
func (o *Group) GetRang5Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rang5, true
}

// SetRang5 sets field value
func (o *Group) SetRang5(v string) {
	o.Rang5 = v
}

// GetLastExp returns the LastExp field value
func (o *Group) GetLastExp() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.LastExp
}

// GetLastExpOk returns a tuple with the LastExp field value
// and a boolean to check if the value has been set.
func (o *Group) GetLastExpOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastExp, true
}

// SetLastExp sets field value
func (o *Group) SetLastExp(v int32) {
	o.LastExp = v
}

// GetR2 returns the R2 field value
func (o *Group) GetR2() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.R2
}

// GetR2Ok returns a tuple with the R2 field value
// and a boolean to check if the value has been set.
func (o *Group) GetR2Ok() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.R2, true
}

// SetR2 sets field value
func (o *Group) SetR2(v int32) {
	o.R2 = v
}

// GetG2 returns the G2 field value
func (o *Group) GetG2() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.G2
}

// GetG2Ok returns a tuple with the G2 field value
// and a boolean to check if the value has been set.
func (o *Group) GetG2Ok() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.G2, true
}

// SetG2 sets field value
func (o *Group) SetG2(v int32) {
	o.G2 = v
}

// GetB2 returns the B2 field value
func (o *Group) GetB2() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.B2
}

// GetB2Ok returns a tuple with the B2 field value
// and a boolean to check if the value has been set.
func (o *Group) GetB2Ok() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.B2, true
}

// SetB2 sets field value
func (o *Group) SetB2(v int32) {
	o.B2 = v
}

// GetType returns the Type field value
func (o *Group) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *Group) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *Group) SetType(v string) {
	o.Type = v
}

// GetBoost1 returns the Boost1 field value
func (o *Group) GetBoost1() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Boost1
}

// GetBoost1Ok returns a tuple with the Boost1 field value
// and a boolean to check if the value has been set.
func (o *Group) GetBoost1Ok() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Boost1, true
}

// SetBoost1 sets field value
func (o *Group) SetBoost1(v int32) {
	o.Boost1 = v
}

// GetSkinMale returns the SkinMale field value
func (o *Group) GetSkinMale() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SkinMale
}

// GetSkinMaleOk returns a tuple with the SkinMale field value
// and a boolean to check if the value has been set.
func (o *Group) GetSkinMaleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SkinMale, true
}

// SetSkinMale sets field value
func (o *Group) SetSkinMale(v string) {
	o.SkinMale = v
}

// GetSkinFemale returns the SkinFemale field value
func (o *Group) GetSkinFemale() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SkinFemale
}

// GetSkinFemaleOk returns a tuple with the SkinFemale field value
// and a boolean to check if the value has been set.
func (o *Group) GetSkinFemaleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SkinFemale, true
}

// SetSkinFemale sets field value
func (o *Group) SetSkinFemale(v string) {
	o.SkinFemale = v
}

// GetBoosts returns the Boosts field value
func (o *Group) GetBoosts() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Boosts
}

// GetBoostsOk returns a tuple with the Boosts field value
// and a boolean to check if the value has been set.
func (o *Group) GetBoostsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Boosts, true
}

// SetBoosts sets field value
func (o *Group) SetBoosts(v string) {
	o.Boosts = v
}

// GetRelationships returns the Relationships field value
func (o *Group) GetRelationships() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value
// and a boolean to check if the value has been set.
func (o *Group) GetRelationshipsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Relationships, true
}

// SetRelationships sets field value
func (o *Group) SetRelationships(v string) {
	o.Relationships = v
}

// GetCraftingStorage returns the CraftingStorage field value if set, zero value otherwise.
func (o *Group) GetCraftingStorage() int32 {
	if o == nil || IsNil(o.CraftingStorage) {
		var ret int32
		return ret
	}
	return *o.CraftingStorage
}

// GetCraftingStorageOk returns a tuple with the CraftingStorage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Group) GetCraftingStorageOk() (*int32, bool) {
	if o == nil || IsNil(o.CraftingStorage) {
		return nil, false
	}
	return o.CraftingStorage, true
}

// HasCraftingStorage returns a boolean if a field has been set.
func (o *Group) HasCraftingStorage() bool {
	if o != nil && !IsNil(o.CraftingStorage) {
		return true
	}

	return false
}

// SetCraftingStorage gets a reference to the given int32 and assigns it to the CraftingStorage field.
func (o *Group) SetCraftingStorage(v int32) {
	o.CraftingStorage = &v
}

func (o Group) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Group) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ID"] = o.ID
	toSerialize["Name"] = o.Name
	toSerialize["Exp"] = o.Exp
	toSerialize["Level"] = o.Level
	toSerialize["Server"] = o.Server
	toSerialize["Msg"] = o.Msg
	if !IsNil(o.R) {
		toSerialize["R"] = o.R
	}
	toSerialize["G"] = o.G
	if !IsNil(o.B) {
		toSerialize["B"] = o.B
	}
	toSerialize["Chat_R"] = o.ChatR
	toSerialize["Chat_G"] = o.ChatG
	toSerialize["Chat_B"] = o.ChatB
	toSerialize["Memberlimit"] = o.Memberlimit
	toSerialize["Tag"] = o.Tag
	toSerialize["Rang0"] = o.Rang0
	toSerialize["Rang1"] = o.Rang1
	if !IsNil(o.Rang2) {
		toSerialize["Rang2"] = o.Rang2
	}
	if !IsNil(o.Rang3) {
		toSerialize["Rang3"] = o.Rang3
	}
	toSerialize["Rang4"] = o.Rang4
	toSerialize["Rang5"] = o.Rang5
	toSerialize["LastExp"] = o.LastExp
	toSerialize["R2"] = o.R2
	toSerialize["G2"] = o.G2
	toSerialize["B2"] = o.B2
	toSerialize["Type"] = o.Type
	toSerialize["Boost1"] = o.Boost1
	toSerialize["SkinMale"] = o.SkinMale
	toSerialize["SkinFemale"] = o.SkinFemale
	toSerialize["Boosts"] = o.Boosts
	toSerialize["Relationships"] = o.Relationships
	if !IsNil(o.CraftingStorage) {
		toSerialize["CraftingStorage"] = o.CraftingStorage
	}
	return toSerialize, nil
}

func (o *Group) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ID",
		"Name",
		"Exp",
		"Level",
		"Server",
		"Msg",
		"G",
		"Chat_R",
		"Chat_G",
		"Chat_B",
		"Memberlimit",
		"Tag",
		"Rang0",
		"Rang1",
		"Rang4",
		"Rang5",
		"LastExp",
		"R2",
		"G2",
		"B2",
		"Type",
		"Boost1",
		"SkinMale",
		"SkinFemale",
		"Boosts",
		"Relationships",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGroup := _Group{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGroup)

	if err != nil {
		return err
	}

	*o = Group(varGroup)

	return err
}

type NullableGroup struct {
	value *Group
	isSet bool
}

func (v NullableGroup) Get() *Group {
	return v.value
}

func (v *NullableGroup) Set(val *Group) {
	v.value = val
	v.isSet = true
}

func (v NullableGroup) IsSet() bool {
	return v.isSet
}

func (v *NullableGroup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroup(val *Group) *NullableGroup {
	return &NullableGroup{value: val, isSet: true}
}

func (v NullableGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


