/*
Vio-V

Vio-V API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CharacterBankLog type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CharacterBankLog{}

// CharacterBankLog struct for CharacterBankLog
type CharacterBankLog struct {
	CharacterID *int32 `json:"CharacterID,omitempty"`
	Timestamp *int32 `json:"Timestamp,omitempty"`
	Amount *string `json:"Amount,omitempty"`
	Reason *string `json:"Reason,omitempty"`
	Info *string `json:"Info,omitempty"`
	Info1 *string `json:"Info1,omitempty"`
}

// NewCharacterBankLog instantiates a new CharacterBankLog object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCharacterBankLog() *CharacterBankLog {
	this := CharacterBankLog{}
	return &this
}

// NewCharacterBankLogWithDefaults instantiates a new CharacterBankLog object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCharacterBankLogWithDefaults() *CharacterBankLog {
	this := CharacterBankLog{}
	return &this
}

// GetCharacterID returns the CharacterID field value if set, zero value otherwise.
func (o *CharacterBankLog) GetCharacterID() int32 {
	if o == nil || IsNil(o.CharacterID) {
		var ret int32
		return ret
	}
	return *o.CharacterID
}

// GetCharacterIDOk returns a tuple with the CharacterID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CharacterBankLog) GetCharacterIDOk() (*int32, bool) {
	if o == nil || IsNil(o.CharacterID) {
		return nil, false
	}
	return o.CharacterID, true
}

// HasCharacterID returns a boolean if a field has been set.
func (o *CharacterBankLog) HasCharacterID() bool {
	if o != nil && !IsNil(o.CharacterID) {
		return true
	}

	return false
}

// SetCharacterID gets a reference to the given int32 and assigns it to the CharacterID field.
func (o *CharacterBankLog) SetCharacterID(v int32) {
	o.CharacterID = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *CharacterBankLog) GetTimestamp() int32 {
	if o == nil || IsNil(o.Timestamp) {
		var ret int32
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CharacterBankLog) GetTimestampOk() (*int32, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *CharacterBankLog) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given int32 and assigns it to the Timestamp field.
func (o *CharacterBankLog) SetTimestamp(v int32) {
	o.Timestamp = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *CharacterBankLog) GetAmount() string {
	if o == nil || IsNil(o.Amount) {
		var ret string
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CharacterBankLog) GetAmountOk() (*string, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *CharacterBankLog) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given string and assigns it to the Amount field.
func (o *CharacterBankLog) SetAmount(v string) {
	o.Amount = &v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *CharacterBankLog) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CharacterBankLog) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *CharacterBankLog) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *CharacterBankLog) SetReason(v string) {
	o.Reason = &v
}

// GetInfo returns the Info field value if set, zero value otherwise.
func (o *CharacterBankLog) GetInfo() string {
	if o == nil || IsNil(o.Info) {
		var ret string
		return ret
	}
	return *o.Info
}

// GetInfoOk returns a tuple with the Info field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CharacterBankLog) GetInfoOk() (*string, bool) {
	if o == nil || IsNil(o.Info) {
		return nil, false
	}
	return o.Info, true
}

// HasInfo returns a boolean if a field has been set.
func (o *CharacterBankLog) HasInfo() bool {
	if o != nil && !IsNil(o.Info) {
		return true
	}

	return false
}

// SetInfo gets a reference to the given string and assigns it to the Info field.
func (o *CharacterBankLog) SetInfo(v string) {
	o.Info = &v
}

// GetInfo1 returns the Info1 field value if set, zero value otherwise.
func (o *CharacterBankLog) GetInfo1() string {
	if o == nil || IsNil(o.Info1) {
		var ret string
		return ret
	}
	return *o.Info1
}

// GetInfo1Ok returns a tuple with the Info1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CharacterBankLog) GetInfo1Ok() (*string, bool) {
	if o == nil || IsNil(o.Info1) {
		return nil, false
	}
	return o.Info1, true
}

// HasInfo1 returns a boolean if a field has been set.
func (o *CharacterBankLog) HasInfo1() bool {
	if o != nil && !IsNil(o.Info1) {
		return true
	}

	return false
}

// SetInfo1 gets a reference to the given string and assigns it to the Info1 field.
func (o *CharacterBankLog) SetInfo1(v string) {
	o.Info1 = &v
}

func (o CharacterBankLog) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CharacterBankLog) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CharacterID) {
		toSerialize["CharacterID"] = o.CharacterID
	}
	if !IsNil(o.Timestamp) {
		toSerialize["Timestamp"] = o.Timestamp
	}
	if !IsNil(o.Amount) {
		toSerialize["Amount"] = o.Amount
	}
	if !IsNil(o.Reason) {
		toSerialize["Reason"] = o.Reason
	}
	if !IsNil(o.Info) {
		toSerialize["Info"] = o.Info
	}
	if !IsNil(o.Info1) {
		toSerialize["Info1"] = o.Info1
	}
	return toSerialize, nil
}

type NullableCharacterBankLog struct {
	value *CharacterBankLog
	isSet bool
}

func (v NullableCharacterBankLog) Get() *CharacterBankLog {
	return v.value
}

func (v *NullableCharacterBankLog) Set(val *CharacterBankLog) {
	v.value = val
	v.isSet = true
}

func (v NullableCharacterBankLog) IsSet() bool {
	return v.isSet
}

func (v *NullableCharacterBankLog) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCharacterBankLog(val *CharacterBankLog) *NullableCharacterBankLog {
	return &NullableCharacterBankLog{value: val, isSet: true}
}

func (v NullableCharacterBankLog) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCharacterBankLog) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


