/*
Vio-V

Vio-V API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Character type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Character{}

// Character struct for Character
type Character struct {
	ID int32 `json:"ID"`
	AccountID int32 `json:"AccountID"`
	Name string `json:"Name"`
	Playingtime int32 `json:"Playingtime"`
	Gender int32 `json:"Gender"`
	STVO int32 `json:"STVO"`
	VehicleLimit int32 `json:"VehicleLimit"`
	BusExp int32 `json:"BusExp"`
	Spawn string `json:"Spawn"`
	SpawnID int32 `json:"SpawnID"`
	Wanteds int32 `json:"Wanteds"`
	JailTime int32 `json:"JailTime"`
	MethTime int32 `json:"MethTime"`
	WeaponLicenseA int32 `json:"WeaponLicenseA"`
	WeaponLicenseB int32 `json:"WeaponLicenseB"`
	WeaponLicenseC int32 `json:"WeaponLicenseC"`
	ActivityTimestamp int32 `json:"ActivityTimestamp"`
	QuestID string `json:"QuestID"`
	QuestStatus int32 `json:"QuestStatus"`
	PhoneNumber int32 `json:"PhoneNumber"`
	FactionTime int32 `json:"FactionTime"`
	Grade float64 `json:"Grade"`
	Raiting float64 `json:"Raiting"`
	DrivingLicenseA int32 `json:"DrivingLicenseA"`
	FoodStatus int32 `json:"FoodStatus"`
	ActivityStep int32 `json:"ActivityStep"`
	DrivingLicensesBlockedTimestamp int32 `json:"DrivingLicensesBlockedTimestamp"`
	WantedArchiv string `json:"WantedArchiv"`
	Skin string `json:"Skin"`
	Skills string `json:"Skills"`
	DailyQuests string `json:"DailyQuests"`
	BonusVehicleLimit int32 `json:"BonusVehicleLimit"`
	Accessory string `json:"Accessory"`
	Achievements string `json:"Achievements"`
	TotalStatus string `json:"TotalStatus"`
	ActiveStatus string `json:"ActiveStatus"`
	SkillPoints string `json:"SkillPoints"`
	SkillBranches string `json:"SkillBranches"`
	SkillSync int32 `json:"SkillSync"`
	Boosts string `json:"Boosts"`
	Tattoos string `json:"Tattoos"`
	Licenses string `json:"Licenses"`
	DailyBonus string `json:"DailyBonus"`
	SeasonPass string `json:"SeasonPass"`
	SeasonPassPoints float64 `json:"SeasonPassPoints"`
	SeasonPassPremium int32 `json:"SeasonPassPremium"`
	WeaponsSkins string `json:"WeaponsSkins"`
	VehiclesSkins string `json:"VehiclesSkins"`
	HalloweenCount int32 `json:"HalloweenCount"`
	LoginTimestamp int32 `json:"LoginTimestamp"`
	RegisterTimestamp time.Time `json:"RegisterTimestamp"`
}

type _Character Character

// NewCharacter instantiates a new Character object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCharacter(iD int32, accountID int32, name string, playingtime int32, gender int32, sTVO int32, vehicleLimit int32, busExp int32, spawn string, spawnID int32, wanteds int32, jailTime int32, methTime int32, weaponLicenseA int32, weaponLicenseB int32, weaponLicenseC int32, activityTimestamp int32, questID string, questStatus int32, phoneNumber int32, factionTime int32, grade float64, raiting float64, drivingLicenseA int32, foodStatus int32, activityStep int32, drivingLicensesBlockedTimestamp int32, wantedArchiv string, skin string, skills string, dailyQuests string, bonusVehicleLimit int32, accessory string, achievements string, totalStatus string, activeStatus string, skillPoints string, skillBranches string, skillSync int32, boosts string, tattoos string, licenses string, dailyBonus string, seasonPass string, seasonPassPoints float64, seasonPassPremium int32, weaponsSkins string, vehiclesSkins string, halloweenCount int32, loginTimestamp int32, registerTimestamp time.Time) *Character {
	this := Character{}
	this.ID = iD
	this.AccountID = accountID
	this.Name = name
	this.Playingtime = playingtime
	this.Gender = gender
	this.STVO = sTVO
	this.VehicleLimit = vehicleLimit
	this.BusExp = busExp
	this.Spawn = spawn
	this.SpawnID = spawnID
	this.Wanteds = wanteds
	this.JailTime = jailTime
	this.MethTime = methTime
	this.WeaponLicenseA = weaponLicenseA
	this.WeaponLicenseB = weaponLicenseB
	this.WeaponLicenseC = weaponLicenseC
	this.ActivityTimestamp = activityTimestamp
	this.QuestID = questID
	this.QuestStatus = questStatus
	this.PhoneNumber = phoneNumber
	this.FactionTime = factionTime
	this.Grade = grade
	this.Raiting = raiting
	this.DrivingLicenseA = drivingLicenseA
	this.FoodStatus = foodStatus
	this.ActivityStep = activityStep
	this.DrivingLicensesBlockedTimestamp = drivingLicensesBlockedTimestamp
	this.WantedArchiv = wantedArchiv
	this.Skin = skin
	this.Skills = skills
	this.DailyQuests = dailyQuests
	this.BonusVehicleLimit = bonusVehicleLimit
	this.Accessory = accessory
	this.Achievements = achievements
	this.TotalStatus = totalStatus
	this.ActiveStatus = activeStatus
	this.SkillPoints = skillPoints
	this.SkillBranches = skillBranches
	this.SkillSync = skillSync
	this.Boosts = boosts
	this.Tattoos = tattoos
	this.Licenses = licenses
	this.DailyBonus = dailyBonus
	this.SeasonPass = seasonPass
	this.SeasonPassPoints = seasonPassPoints
	this.SeasonPassPremium = seasonPassPremium
	this.WeaponsSkins = weaponsSkins
	this.VehiclesSkins = vehiclesSkins
	this.HalloweenCount = halloweenCount
	this.LoginTimestamp = loginTimestamp
	this.RegisterTimestamp = registerTimestamp
	return &this
}

// NewCharacterWithDefaults instantiates a new Character object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCharacterWithDefaults() *Character {
	this := Character{}
	return &this
}

// GetID returns the ID field value
func (o *Character) GetID() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ID
}

// GetIDOk returns a tuple with the ID field value
// and a boolean to check if the value has been set.
func (o *Character) GetIDOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ID, true
}

// SetID sets field value
func (o *Character) SetID(v int32) {
	o.ID = v
}

// GetAccountID returns the AccountID field value
func (o *Character) GetAccountID() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AccountID
}

// GetAccountIDOk returns a tuple with the AccountID field value
// and a boolean to check if the value has been set.
func (o *Character) GetAccountIDOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountID, true
}

// SetAccountID sets field value
func (o *Character) SetAccountID(v int32) {
	o.AccountID = v
}

// GetName returns the Name field value
func (o *Character) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Character) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Character) SetName(v string) {
	o.Name = v
}

// GetPlayingtime returns the Playingtime field value
func (o *Character) GetPlayingtime() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Playingtime
}

// GetPlayingtimeOk returns a tuple with the Playingtime field value
// and a boolean to check if the value has been set.
func (o *Character) GetPlayingtimeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Playingtime, true
}

// SetPlayingtime sets field value
func (o *Character) SetPlayingtime(v int32) {
	o.Playingtime = v
}

// GetGender returns the Gender field value
func (o *Character) GetGender() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Gender
}

// GetGenderOk returns a tuple with the Gender field value
// and a boolean to check if the value has been set.
func (o *Character) GetGenderOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Gender, true
}

// SetGender sets field value
func (o *Character) SetGender(v int32) {
	o.Gender = v
}

// GetSTVO returns the STVO field value
func (o *Character) GetSTVO() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.STVO
}

// GetSTVOOk returns a tuple with the STVO field value
// and a boolean to check if the value has been set.
func (o *Character) GetSTVOOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.STVO, true
}

// SetSTVO sets field value
func (o *Character) SetSTVO(v int32) {
	o.STVO = v
}

// GetVehicleLimit returns the VehicleLimit field value
func (o *Character) GetVehicleLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.VehicleLimit
}

// GetVehicleLimitOk returns a tuple with the VehicleLimit field value
// and a boolean to check if the value has been set.
func (o *Character) GetVehicleLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VehicleLimit, true
}

// SetVehicleLimit sets field value
func (o *Character) SetVehicleLimit(v int32) {
	o.VehicleLimit = v
}

// GetBusExp returns the BusExp field value
func (o *Character) GetBusExp() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.BusExp
}

// GetBusExpOk returns a tuple with the BusExp field value
// and a boolean to check if the value has been set.
func (o *Character) GetBusExpOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BusExp, true
}

// SetBusExp sets field value
func (o *Character) SetBusExp(v int32) {
	o.BusExp = v
}

// GetSpawn returns the Spawn field value
func (o *Character) GetSpawn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Spawn
}

// GetSpawnOk returns a tuple with the Spawn field value
// and a boolean to check if the value has been set.
func (o *Character) GetSpawnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Spawn, true
}

// SetSpawn sets field value
func (o *Character) SetSpawn(v string) {
	o.Spawn = v
}

// GetSpawnID returns the SpawnID field value
func (o *Character) GetSpawnID() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SpawnID
}

// GetSpawnIDOk returns a tuple with the SpawnID field value
// and a boolean to check if the value has been set.
func (o *Character) GetSpawnIDOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SpawnID, true
}

// SetSpawnID sets field value
func (o *Character) SetSpawnID(v int32) {
	o.SpawnID = v
}

// GetWanteds returns the Wanteds field value
func (o *Character) GetWanteds() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Wanteds
}

// GetWantedsOk returns a tuple with the Wanteds field value
// and a boolean to check if the value has been set.
func (o *Character) GetWantedsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Wanteds, true
}

// SetWanteds sets field value
func (o *Character) SetWanteds(v int32) {
	o.Wanteds = v
}

// GetJailTime returns the JailTime field value
func (o *Character) GetJailTime() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.JailTime
}

// GetJailTimeOk returns a tuple with the JailTime field value
// and a boolean to check if the value has been set.
func (o *Character) GetJailTimeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JailTime, true
}

// SetJailTime sets field value
func (o *Character) SetJailTime(v int32) {
	o.JailTime = v
}

// GetMethTime returns the MethTime field value
func (o *Character) GetMethTime() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MethTime
}

// GetMethTimeOk returns a tuple with the MethTime field value
// and a boolean to check if the value has been set.
func (o *Character) GetMethTimeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MethTime, true
}

// SetMethTime sets field value
func (o *Character) SetMethTime(v int32) {
	o.MethTime = v
}

// GetWeaponLicenseA returns the WeaponLicenseA field value
func (o *Character) GetWeaponLicenseA() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.WeaponLicenseA
}

// GetWeaponLicenseAOk returns a tuple with the WeaponLicenseA field value
// and a boolean to check if the value has been set.
func (o *Character) GetWeaponLicenseAOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WeaponLicenseA, true
}

// SetWeaponLicenseA sets field value
func (o *Character) SetWeaponLicenseA(v int32) {
	o.WeaponLicenseA = v
}

// GetWeaponLicenseB returns the WeaponLicenseB field value
func (o *Character) GetWeaponLicenseB() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.WeaponLicenseB
}

// GetWeaponLicenseBOk returns a tuple with the WeaponLicenseB field value
// and a boolean to check if the value has been set.
func (o *Character) GetWeaponLicenseBOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WeaponLicenseB, true
}

// SetWeaponLicenseB sets field value
func (o *Character) SetWeaponLicenseB(v int32) {
	o.WeaponLicenseB = v
}

// GetWeaponLicenseC returns the WeaponLicenseC field value
func (o *Character) GetWeaponLicenseC() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.WeaponLicenseC
}

// GetWeaponLicenseCOk returns a tuple with the WeaponLicenseC field value
// and a boolean to check if the value has been set.
func (o *Character) GetWeaponLicenseCOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WeaponLicenseC, true
}

// SetWeaponLicenseC sets field value
func (o *Character) SetWeaponLicenseC(v int32) {
	o.WeaponLicenseC = v
}

// GetActivityTimestamp returns the ActivityTimestamp field value
func (o *Character) GetActivityTimestamp() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ActivityTimestamp
}

// GetActivityTimestampOk returns a tuple with the ActivityTimestamp field value
// and a boolean to check if the value has been set.
func (o *Character) GetActivityTimestampOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ActivityTimestamp, true
}

// SetActivityTimestamp sets field value
func (o *Character) SetActivityTimestamp(v int32) {
	o.ActivityTimestamp = v
}

// GetQuestID returns the QuestID field value
func (o *Character) GetQuestID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QuestID
}

// GetQuestIDOk returns a tuple with the QuestID field value
// and a boolean to check if the value has been set.
func (o *Character) GetQuestIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuestID, true
}

// SetQuestID sets field value
func (o *Character) SetQuestID(v string) {
	o.QuestID = v
}

// GetQuestStatus returns the QuestStatus field value
func (o *Character) GetQuestStatus() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.QuestStatus
}

// GetQuestStatusOk returns a tuple with the QuestStatus field value
// and a boolean to check if the value has been set.
func (o *Character) GetQuestStatusOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuestStatus, true
}

// SetQuestStatus sets field value
func (o *Character) SetQuestStatus(v int32) {
	o.QuestStatus = v
}

// GetPhoneNumber returns the PhoneNumber field value
func (o *Character) GetPhoneNumber() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PhoneNumber
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value
// and a boolean to check if the value has been set.
func (o *Character) GetPhoneNumberOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PhoneNumber, true
}

// SetPhoneNumber sets field value
func (o *Character) SetPhoneNumber(v int32) {
	o.PhoneNumber = v
}

// GetFactionTime returns the FactionTime field value
func (o *Character) GetFactionTime() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.FactionTime
}

// GetFactionTimeOk returns a tuple with the FactionTime field value
// and a boolean to check if the value has been set.
func (o *Character) GetFactionTimeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FactionTime, true
}

// SetFactionTime sets field value
func (o *Character) SetFactionTime(v int32) {
	o.FactionTime = v
}

// GetGrade returns the Grade field value
func (o *Character) GetGrade() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Grade
}

// GetGradeOk returns a tuple with the Grade field value
// and a boolean to check if the value has been set.
func (o *Character) GetGradeOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Grade, true
}

// SetGrade sets field value
func (o *Character) SetGrade(v float64) {
	o.Grade = v
}

// GetRaiting returns the Raiting field value
func (o *Character) GetRaiting() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Raiting
}

// GetRaitingOk returns a tuple with the Raiting field value
// and a boolean to check if the value has been set.
func (o *Character) GetRaitingOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Raiting, true
}

// SetRaiting sets field value
func (o *Character) SetRaiting(v float64) {
	o.Raiting = v
}

// GetDrivingLicenseA returns the DrivingLicenseA field value
func (o *Character) GetDrivingLicenseA() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DrivingLicenseA
}

// GetDrivingLicenseAOk returns a tuple with the DrivingLicenseA field value
// and a boolean to check if the value has been set.
func (o *Character) GetDrivingLicenseAOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DrivingLicenseA, true
}

// SetDrivingLicenseA sets field value
func (o *Character) SetDrivingLicenseA(v int32) {
	o.DrivingLicenseA = v
}

// GetFoodStatus returns the FoodStatus field value
func (o *Character) GetFoodStatus() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.FoodStatus
}

// GetFoodStatusOk returns a tuple with the FoodStatus field value
// and a boolean to check if the value has been set.
func (o *Character) GetFoodStatusOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FoodStatus, true
}

// SetFoodStatus sets field value
func (o *Character) SetFoodStatus(v int32) {
	o.FoodStatus = v
}

// GetActivityStep returns the ActivityStep field value
func (o *Character) GetActivityStep() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ActivityStep
}

// GetActivityStepOk returns a tuple with the ActivityStep field value
// and a boolean to check if the value has been set.
func (o *Character) GetActivityStepOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ActivityStep, true
}

// SetActivityStep sets field value
func (o *Character) SetActivityStep(v int32) {
	o.ActivityStep = v
}

// GetDrivingLicensesBlockedTimestamp returns the DrivingLicensesBlockedTimestamp field value
func (o *Character) GetDrivingLicensesBlockedTimestamp() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DrivingLicensesBlockedTimestamp
}

// GetDrivingLicensesBlockedTimestampOk returns a tuple with the DrivingLicensesBlockedTimestamp field value
// and a boolean to check if the value has been set.
func (o *Character) GetDrivingLicensesBlockedTimestampOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DrivingLicensesBlockedTimestamp, true
}

// SetDrivingLicensesBlockedTimestamp sets field value
func (o *Character) SetDrivingLicensesBlockedTimestamp(v int32) {
	o.DrivingLicensesBlockedTimestamp = v
}

// GetWantedArchiv returns the WantedArchiv field value
func (o *Character) GetWantedArchiv() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WantedArchiv
}

// GetWantedArchivOk returns a tuple with the WantedArchiv field value
// and a boolean to check if the value has been set.
func (o *Character) GetWantedArchivOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WantedArchiv, true
}

// SetWantedArchiv sets field value
func (o *Character) SetWantedArchiv(v string) {
	o.WantedArchiv = v
}

// GetSkin returns the Skin field value
func (o *Character) GetSkin() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Skin
}

// GetSkinOk returns a tuple with the Skin field value
// and a boolean to check if the value has been set.
func (o *Character) GetSkinOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Skin, true
}

// SetSkin sets field value
func (o *Character) SetSkin(v string) {
	o.Skin = v
}

// GetSkills returns the Skills field value
func (o *Character) GetSkills() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Skills
}

// GetSkillsOk returns a tuple with the Skills field value
// and a boolean to check if the value has been set.
func (o *Character) GetSkillsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Skills, true
}

// SetSkills sets field value
func (o *Character) SetSkills(v string) {
	o.Skills = v
}

// GetDailyQuests returns the DailyQuests field value
func (o *Character) GetDailyQuests() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DailyQuests
}

// GetDailyQuestsOk returns a tuple with the DailyQuests field value
// and a boolean to check if the value has been set.
func (o *Character) GetDailyQuestsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DailyQuests, true
}

// SetDailyQuests sets field value
func (o *Character) SetDailyQuests(v string) {
	o.DailyQuests = v
}

// GetBonusVehicleLimit returns the BonusVehicleLimit field value
func (o *Character) GetBonusVehicleLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.BonusVehicleLimit
}

// GetBonusVehicleLimitOk returns a tuple with the BonusVehicleLimit field value
// and a boolean to check if the value has been set.
func (o *Character) GetBonusVehicleLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BonusVehicleLimit, true
}

// SetBonusVehicleLimit sets field value
func (o *Character) SetBonusVehicleLimit(v int32) {
	o.BonusVehicleLimit = v
}

// GetAccessory returns the Accessory field value
func (o *Character) GetAccessory() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Accessory
}

// GetAccessoryOk returns a tuple with the Accessory field value
// and a boolean to check if the value has been set.
func (o *Character) GetAccessoryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Accessory, true
}

// SetAccessory sets field value
func (o *Character) SetAccessory(v string) {
	o.Accessory = v
}

// GetAchievements returns the Achievements field value
func (o *Character) GetAchievements() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Achievements
}

// GetAchievementsOk returns a tuple with the Achievements field value
// and a boolean to check if the value has been set.
func (o *Character) GetAchievementsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Achievements, true
}

// SetAchievements sets field value
func (o *Character) SetAchievements(v string) {
	o.Achievements = v
}

// GetTotalStatus returns the TotalStatus field value
func (o *Character) GetTotalStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TotalStatus
}

// GetTotalStatusOk returns a tuple with the TotalStatus field value
// and a boolean to check if the value has been set.
func (o *Character) GetTotalStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalStatus, true
}

// SetTotalStatus sets field value
func (o *Character) SetTotalStatus(v string) {
	o.TotalStatus = v
}

// GetActiveStatus returns the ActiveStatus field value
func (o *Character) GetActiveStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ActiveStatus
}

// GetActiveStatusOk returns a tuple with the ActiveStatus field value
// and a boolean to check if the value has been set.
func (o *Character) GetActiveStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ActiveStatus, true
}

// SetActiveStatus sets field value
func (o *Character) SetActiveStatus(v string) {
	o.ActiveStatus = v
}

// GetSkillPoints returns the SkillPoints field value
func (o *Character) GetSkillPoints() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SkillPoints
}

// GetSkillPointsOk returns a tuple with the SkillPoints field value
// and a boolean to check if the value has been set.
func (o *Character) GetSkillPointsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SkillPoints, true
}

// SetSkillPoints sets field value
func (o *Character) SetSkillPoints(v string) {
	o.SkillPoints = v
}

// GetSkillBranches returns the SkillBranches field value
func (o *Character) GetSkillBranches() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SkillBranches
}

// GetSkillBranchesOk returns a tuple with the SkillBranches field value
// and a boolean to check if the value has been set.
func (o *Character) GetSkillBranchesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SkillBranches, true
}

// SetSkillBranches sets field value
func (o *Character) SetSkillBranches(v string) {
	o.SkillBranches = v
}

// GetSkillSync returns the SkillSync field value
func (o *Character) GetSkillSync() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SkillSync
}

// GetSkillSyncOk returns a tuple with the SkillSync field value
// and a boolean to check if the value has been set.
func (o *Character) GetSkillSyncOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SkillSync, true
}

// SetSkillSync sets field value
func (o *Character) SetSkillSync(v int32) {
	o.SkillSync = v
}

// GetBoosts returns the Boosts field value
func (o *Character) GetBoosts() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Boosts
}

// GetBoostsOk returns a tuple with the Boosts field value
// and a boolean to check if the value has been set.
func (o *Character) GetBoostsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Boosts, true
}

// SetBoosts sets field value
func (o *Character) SetBoosts(v string) {
	o.Boosts = v
}

// GetTattoos returns the Tattoos field value
func (o *Character) GetTattoos() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Tattoos
}

// GetTattoosOk returns a tuple with the Tattoos field value
// and a boolean to check if the value has been set.
func (o *Character) GetTattoosOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tattoos, true
}

// SetTattoos sets field value
func (o *Character) SetTattoos(v string) {
	o.Tattoos = v
}

// GetLicenses returns the Licenses field value
func (o *Character) GetLicenses() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Licenses
}

// GetLicensesOk returns a tuple with the Licenses field value
// and a boolean to check if the value has been set.
func (o *Character) GetLicensesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Licenses, true
}

// SetLicenses sets field value
func (o *Character) SetLicenses(v string) {
	o.Licenses = v
}

// GetDailyBonus returns the DailyBonus field value
func (o *Character) GetDailyBonus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DailyBonus
}

// GetDailyBonusOk returns a tuple with the DailyBonus field value
// and a boolean to check if the value has been set.
func (o *Character) GetDailyBonusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DailyBonus, true
}

// SetDailyBonus sets field value
func (o *Character) SetDailyBonus(v string) {
	o.DailyBonus = v
}

// GetSeasonPass returns the SeasonPass field value
func (o *Character) GetSeasonPass() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SeasonPass
}

// GetSeasonPassOk returns a tuple with the SeasonPass field value
// and a boolean to check if the value has been set.
func (o *Character) GetSeasonPassOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SeasonPass, true
}

// SetSeasonPass sets field value
func (o *Character) SetSeasonPass(v string) {
	o.SeasonPass = v
}

// GetSeasonPassPoints returns the SeasonPassPoints field value
func (o *Character) GetSeasonPassPoints() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.SeasonPassPoints
}

// GetSeasonPassPointsOk returns a tuple with the SeasonPassPoints field value
// and a boolean to check if the value has been set.
func (o *Character) GetSeasonPassPointsOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SeasonPassPoints, true
}

// SetSeasonPassPoints sets field value
func (o *Character) SetSeasonPassPoints(v float64) {
	o.SeasonPassPoints = v
}

// GetSeasonPassPremium returns the SeasonPassPremium field value
func (o *Character) GetSeasonPassPremium() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SeasonPassPremium
}

// GetSeasonPassPremiumOk returns a tuple with the SeasonPassPremium field value
// and a boolean to check if the value has been set.
func (o *Character) GetSeasonPassPremiumOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SeasonPassPremium, true
}

// SetSeasonPassPremium sets field value
func (o *Character) SetSeasonPassPremium(v int32) {
	o.SeasonPassPremium = v
}

// GetWeaponsSkins returns the WeaponsSkins field value
func (o *Character) GetWeaponsSkins() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WeaponsSkins
}

// GetWeaponsSkinsOk returns a tuple with the WeaponsSkins field value
// and a boolean to check if the value has been set.
func (o *Character) GetWeaponsSkinsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WeaponsSkins, true
}

// SetWeaponsSkins sets field value
func (o *Character) SetWeaponsSkins(v string) {
	o.WeaponsSkins = v
}

// GetVehiclesSkins returns the VehiclesSkins field value
func (o *Character) GetVehiclesSkins() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VehiclesSkins
}

// GetVehiclesSkinsOk returns a tuple with the VehiclesSkins field value
// and a boolean to check if the value has been set.
func (o *Character) GetVehiclesSkinsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VehiclesSkins, true
}

// SetVehiclesSkins sets field value
func (o *Character) SetVehiclesSkins(v string) {
	o.VehiclesSkins = v
}

// GetHalloweenCount returns the HalloweenCount field value
func (o *Character) GetHalloweenCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.HalloweenCount
}

// GetHalloweenCountOk returns a tuple with the HalloweenCount field value
// and a boolean to check if the value has been set.
func (o *Character) GetHalloweenCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HalloweenCount, true
}

// SetHalloweenCount sets field value
func (o *Character) SetHalloweenCount(v int32) {
	o.HalloweenCount = v
}

// GetLoginTimestamp returns the LoginTimestamp field value
func (o *Character) GetLoginTimestamp() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.LoginTimestamp
}

// GetLoginTimestampOk returns a tuple with the LoginTimestamp field value
// and a boolean to check if the value has been set.
func (o *Character) GetLoginTimestampOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LoginTimestamp, true
}

// SetLoginTimestamp sets field value
func (o *Character) SetLoginTimestamp(v int32) {
	o.LoginTimestamp = v
}

// GetRegisterTimestamp returns the RegisterTimestamp field value
func (o *Character) GetRegisterTimestamp() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.RegisterTimestamp
}

// GetRegisterTimestampOk returns a tuple with the RegisterTimestamp field value
// and a boolean to check if the value has been set.
func (o *Character) GetRegisterTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RegisterTimestamp, true
}

// SetRegisterTimestamp sets field value
func (o *Character) SetRegisterTimestamp(v time.Time) {
	o.RegisterTimestamp = v
}

func (o Character) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Character) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ID"] = o.ID
	toSerialize["AccountID"] = o.AccountID
	toSerialize["Name"] = o.Name
	toSerialize["Playingtime"] = o.Playingtime
	toSerialize["Gender"] = o.Gender
	toSerialize["STVO"] = o.STVO
	toSerialize["VehicleLimit"] = o.VehicleLimit
	toSerialize["BusExp"] = o.BusExp
	toSerialize["Spawn"] = o.Spawn
	toSerialize["SpawnID"] = o.SpawnID
	toSerialize["Wanteds"] = o.Wanteds
	toSerialize["JailTime"] = o.JailTime
	toSerialize["MethTime"] = o.MethTime
	toSerialize["WeaponLicenseA"] = o.WeaponLicenseA
	toSerialize["WeaponLicenseB"] = o.WeaponLicenseB
	toSerialize["WeaponLicenseC"] = o.WeaponLicenseC
	toSerialize["ActivityTimestamp"] = o.ActivityTimestamp
	toSerialize["QuestID"] = o.QuestID
	toSerialize["QuestStatus"] = o.QuestStatus
	toSerialize["PhoneNumber"] = o.PhoneNumber
	toSerialize["FactionTime"] = o.FactionTime
	toSerialize["Grade"] = o.Grade
	toSerialize["Raiting"] = o.Raiting
	toSerialize["DrivingLicenseA"] = o.DrivingLicenseA
	toSerialize["FoodStatus"] = o.FoodStatus
	toSerialize["ActivityStep"] = o.ActivityStep
	toSerialize["DrivingLicensesBlockedTimestamp"] = o.DrivingLicensesBlockedTimestamp
	toSerialize["WantedArchiv"] = o.WantedArchiv
	toSerialize["Skin"] = o.Skin
	toSerialize["Skills"] = o.Skills
	toSerialize["DailyQuests"] = o.DailyQuests
	toSerialize["BonusVehicleLimit"] = o.BonusVehicleLimit
	toSerialize["Accessory"] = o.Accessory
	toSerialize["Achievements"] = o.Achievements
	toSerialize["TotalStatus"] = o.TotalStatus
	toSerialize["ActiveStatus"] = o.ActiveStatus
	toSerialize["SkillPoints"] = o.SkillPoints
	toSerialize["SkillBranches"] = o.SkillBranches
	toSerialize["SkillSync"] = o.SkillSync
	toSerialize["Boosts"] = o.Boosts
	toSerialize["Tattoos"] = o.Tattoos
	toSerialize["Licenses"] = o.Licenses
	toSerialize["DailyBonus"] = o.DailyBonus
	toSerialize["SeasonPass"] = o.SeasonPass
	toSerialize["SeasonPassPoints"] = o.SeasonPassPoints
	toSerialize["SeasonPassPremium"] = o.SeasonPassPremium
	toSerialize["WeaponsSkins"] = o.WeaponsSkins
	toSerialize["VehiclesSkins"] = o.VehiclesSkins
	toSerialize["HalloweenCount"] = o.HalloweenCount
	toSerialize["LoginTimestamp"] = o.LoginTimestamp
	toSerialize["RegisterTimestamp"] = o.RegisterTimestamp
	return toSerialize, nil
}

func (o *Character) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ID",
		"AccountID",
		"Name",
		"Playingtime",
		"Gender",
		"STVO",
		"VehicleLimit",
		"BusExp",
		"Spawn",
		"SpawnID",
		"Wanteds",
		"JailTime",
		"MethTime",
		"WeaponLicenseA",
		"WeaponLicenseB",
		"WeaponLicenseC",
		"ActivityTimestamp",
		"QuestID",
		"QuestStatus",
		"PhoneNumber",
		"FactionTime",
		"Grade",
		"Raiting",
		"DrivingLicenseA",
		"FoodStatus",
		"ActivityStep",
		"DrivingLicensesBlockedTimestamp",
		"WantedArchiv",
		"Skin",
		"Skills",
		"DailyQuests",
		"BonusVehicleLimit",
		"Accessory",
		"Achievements",
		"TotalStatus",
		"ActiveStatus",
		"SkillPoints",
		"SkillBranches",
		"SkillSync",
		"Boosts",
		"Tattoos",
		"Licenses",
		"DailyBonus",
		"SeasonPass",
		"SeasonPassPoints",
		"SeasonPassPremium",
		"WeaponsSkins",
		"VehiclesSkins",
		"HalloweenCount",
		"LoginTimestamp",
		"RegisterTimestamp",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCharacter := _Character{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCharacter)

	if err != nil {
		return err
	}

	*o = Character(varCharacter)

	return err
}

type NullableCharacter struct {
	value *Character
	isSet bool
}

func (v NullableCharacter) Get() *Character {
	return v.value
}

func (v *NullableCharacter) Set(val *Character) {
	v.value = val
	v.isSet = true
}

func (v NullableCharacter) IsSet() bool {
	return v.isSet
}

func (v *NullableCharacter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCharacter(val *Character) *NullableCharacter {
	return &NullableCharacter{value: val, isSet: true}
}

func (v NullableCharacter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCharacter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


