/*
Vio-V

Vio-V API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GroupOwnFactory type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupOwnFactory{}

// GroupOwnFactory struct for GroupOwnFactory
type GroupOwnFactory struct {
	ID *int32 `json:"ID,omitempty"`
	Type string `json:"Type"`
	GroupID int32 `json:"GroupID"`
	MasterID int32 `json:"MasterID"`
	Storage string `json:"Storage"`
	Settings string `json:"Settings"`
	CraftingStorages string `json:"CraftingStorages"`
	EXP int32 `json:"EXP"`
}

type _GroupOwnFactory GroupOwnFactory

// NewGroupOwnFactory instantiates a new GroupOwnFactory object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupOwnFactory(type_ string, groupID int32, masterID int32, storage string, settings string, craftingStorages string, eXP int32) *GroupOwnFactory {
	this := GroupOwnFactory{}
	this.Type = type_
	this.GroupID = groupID
	this.MasterID = masterID
	this.Storage = storage
	this.Settings = settings
	this.CraftingStorages = craftingStorages
	this.EXP = eXP
	return &this
}

// NewGroupOwnFactoryWithDefaults instantiates a new GroupOwnFactory object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupOwnFactoryWithDefaults() *GroupOwnFactory {
	this := GroupOwnFactory{}
	return &this
}

// GetID returns the ID field value if set, zero value otherwise.
func (o *GroupOwnFactory) GetID() int32 {
	if o == nil || IsNil(o.ID) {
		var ret int32
		return ret
	}
	return *o.ID
}

// GetIDOk returns a tuple with the ID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupOwnFactory) GetIDOk() (*int32, bool) {
	if o == nil || IsNil(o.ID) {
		return nil, false
	}
	return o.ID, true
}

// HasID returns a boolean if a field has been set.
func (o *GroupOwnFactory) HasID() bool {
	if o != nil && !IsNil(o.ID) {
		return true
	}

	return false
}

// SetID gets a reference to the given int32 and assigns it to the ID field.
func (o *GroupOwnFactory) SetID(v int32) {
	o.ID = &v
}

// GetType returns the Type field value
func (o *GroupOwnFactory) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *GroupOwnFactory) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *GroupOwnFactory) SetType(v string) {
	o.Type = v
}

// GetGroupID returns the GroupID field value
func (o *GroupOwnFactory) GetGroupID() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.GroupID
}

// GetGroupIDOk returns a tuple with the GroupID field value
// and a boolean to check if the value has been set.
func (o *GroupOwnFactory) GetGroupIDOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GroupID, true
}

// SetGroupID sets field value
func (o *GroupOwnFactory) SetGroupID(v int32) {
	o.GroupID = v
}

// GetMasterID returns the MasterID field value
func (o *GroupOwnFactory) GetMasterID() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MasterID
}

// GetMasterIDOk returns a tuple with the MasterID field value
// and a boolean to check if the value has been set.
func (o *GroupOwnFactory) GetMasterIDOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MasterID, true
}

// SetMasterID sets field value
func (o *GroupOwnFactory) SetMasterID(v int32) {
	o.MasterID = v
}

// GetStorage returns the Storage field value
func (o *GroupOwnFactory) GetStorage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Storage
}

// GetStorageOk returns a tuple with the Storage field value
// and a boolean to check if the value has been set.
func (o *GroupOwnFactory) GetStorageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Storage, true
}

// SetStorage sets field value
func (o *GroupOwnFactory) SetStorage(v string) {
	o.Storage = v
}

// GetSettings returns the Settings field value
func (o *GroupOwnFactory) GetSettings() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Settings
}

// GetSettingsOk returns a tuple with the Settings field value
// and a boolean to check if the value has been set.
func (o *GroupOwnFactory) GetSettingsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Settings, true
}

// SetSettings sets field value
func (o *GroupOwnFactory) SetSettings(v string) {
	o.Settings = v
}

// GetCraftingStorages returns the CraftingStorages field value
func (o *GroupOwnFactory) GetCraftingStorages() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CraftingStorages
}

// GetCraftingStoragesOk returns a tuple with the CraftingStorages field value
// and a boolean to check if the value has been set.
func (o *GroupOwnFactory) GetCraftingStoragesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CraftingStorages, true
}

// SetCraftingStorages sets field value
func (o *GroupOwnFactory) SetCraftingStorages(v string) {
	o.CraftingStorages = v
}

// GetEXP returns the EXP field value
func (o *GroupOwnFactory) GetEXP() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.EXP
}

// GetEXPOk returns a tuple with the EXP field value
// and a boolean to check if the value has been set.
func (o *GroupOwnFactory) GetEXPOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EXP, true
}

// SetEXP sets field value
func (o *GroupOwnFactory) SetEXP(v int32) {
	o.EXP = v
}

func (o GroupOwnFactory) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupOwnFactory) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ID) {
		toSerialize["ID"] = o.ID
	}
	toSerialize["Type"] = o.Type
	toSerialize["GroupID"] = o.GroupID
	toSerialize["MasterID"] = o.MasterID
	toSerialize["Storage"] = o.Storage
	toSerialize["Settings"] = o.Settings
	toSerialize["CraftingStorages"] = o.CraftingStorages
	toSerialize["EXP"] = o.EXP
	return toSerialize, nil
}

func (o *GroupOwnFactory) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Type",
		"GroupID",
		"MasterID",
		"Storage",
		"Settings",
		"CraftingStorages",
		"EXP",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGroupOwnFactory := _GroupOwnFactory{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGroupOwnFactory)

	if err != nil {
		return err
	}

	*o = GroupOwnFactory(varGroupOwnFactory)

	return err
}

type NullableGroupOwnFactory struct {
	value *GroupOwnFactory
	isSet bool
}

func (v NullableGroupOwnFactory) Get() *GroupOwnFactory {
	return v.value
}

func (v *NullableGroupOwnFactory) Set(val *GroupOwnFactory) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupOwnFactory) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupOwnFactory) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupOwnFactory(val *GroupOwnFactory) *NullableGroupOwnFactory {
	return &NullableGroupOwnFactory{value: val, isSet: true}
}

func (v NullableGroupOwnFactory) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupOwnFactory) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


