/*
Vio-V

Vio-V API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GroupRank type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupRank{}

// GroupRank struct for GroupRank
type GroupRank struct {
	RankID int32 `json:"RankID"`
	GroupID int32 `json:"GroupID"`
	Name string `json:"Name"`
	Bonus int32 `json:"Bonus"`
	Leader int32 `json:"Leader"`
}

type _GroupRank GroupRank

// NewGroupRank instantiates a new GroupRank object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupRank(rankID int32, groupID int32, name string, bonus int32, leader int32) *GroupRank {
	this := GroupRank{}
	this.RankID = rankID
	this.GroupID = groupID
	this.Name = name
	this.Bonus = bonus
	this.Leader = leader
	return &this
}

// NewGroupRankWithDefaults instantiates a new GroupRank object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupRankWithDefaults() *GroupRank {
	this := GroupRank{}
	return &this
}

// GetRankID returns the RankID field value
func (o *GroupRank) GetRankID() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RankID
}

// GetRankIDOk returns a tuple with the RankID field value
// and a boolean to check if the value has been set.
func (o *GroupRank) GetRankIDOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RankID, true
}

// SetRankID sets field value
func (o *GroupRank) SetRankID(v int32) {
	o.RankID = v
}

// GetGroupID returns the GroupID field value
func (o *GroupRank) GetGroupID() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.GroupID
}

// GetGroupIDOk returns a tuple with the GroupID field value
// and a boolean to check if the value has been set.
func (o *GroupRank) GetGroupIDOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GroupID, true
}

// SetGroupID sets field value
func (o *GroupRank) SetGroupID(v int32) {
	o.GroupID = v
}

// GetName returns the Name field value
func (o *GroupRank) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GroupRank) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GroupRank) SetName(v string) {
	o.Name = v
}

// GetBonus returns the Bonus field value
func (o *GroupRank) GetBonus() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Bonus
}

// GetBonusOk returns a tuple with the Bonus field value
// and a boolean to check if the value has been set.
func (o *GroupRank) GetBonusOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Bonus, true
}

// SetBonus sets field value
func (o *GroupRank) SetBonus(v int32) {
	o.Bonus = v
}

// GetLeader returns the Leader field value
func (o *GroupRank) GetLeader() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Leader
}

// GetLeaderOk returns a tuple with the Leader field value
// and a boolean to check if the value has been set.
func (o *GroupRank) GetLeaderOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Leader, true
}

// SetLeader sets field value
func (o *GroupRank) SetLeader(v int32) {
	o.Leader = v
}

func (o GroupRank) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupRank) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["RankID"] = o.RankID
	toSerialize["GroupID"] = o.GroupID
	toSerialize["Name"] = o.Name
	toSerialize["Bonus"] = o.Bonus
	toSerialize["Leader"] = o.Leader
	return toSerialize, nil
}

func (o *GroupRank) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"RankID",
		"GroupID",
		"Name",
		"Bonus",
		"Leader",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGroupRank := _GroupRank{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGroupRank)

	if err != nil {
		return err
	}

	*o = GroupRank(varGroupRank)

	return err
}

type NullableGroupRank struct {
	value *GroupRank
	isSet bool
}

func (v NullableGroupRank) Get() *GroupRank {
	return v.value
}

func (v *NullableGroupRank) Set(val *GroupRank) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupRank) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupRank) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupRank(val *GroupRank) *NullableGroupRank {
	return &NullableGroupRank{value: val, isSet: true}
}

func (v NullableGroupRank) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupRank) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


