/*
Vio-V

Vio-V API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the GroupVehicle type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupVehicle{}

// GroupVehicle struct for GroupVehicle
type GroupVehicle struct {
	ID int64 `json:"ID"`
	GroupID int32 `json:"GroupID"`
	Hash string `json:"Hash"`
	PosX string `json:"PosX"`
	PosY string `json:"PosY"`
	PosZ string `json:"PosZ"`
	RotX string `json:"RotX"`
	RotY string `json:"RotY"`
	RotZ string `json:"RotZ"`
	Color1 int32 `json:"Color1"`
	Color2 int32 `json:"Color2"`
	BuyDate time.Time `json:"BuyDate"`
	Color1R int32 `json:"Color1R"`
	Color1G int32 `json:"Color1G"`
	Color1B int32 `json:"Color1B"`
	Color2R int32 `json:"Color2R"`
	Color2G int32 `json:"Color2G"`
	Color2B int32 `json:"Color2B"`
	Spoilers int32 `json:"Spoilers"`
	FrontBumper int32 `json:"FrontBumper"`
	RearBumper int32 `json:"RearBumper"`
	SideSkirt int32 `json:"SideSkirt"`
	Exhaust int32 `json:"Exhaust"`
	Frame int32 `json:"Frame"`
	Grille int32 `json:"Grille"`
	Hood int32 `json:"Hood"`
	Fender int32 `json:"Fender"`
	RightFender int32 `json:"RightFender"`
	Roof int32 `json:"Roof"`
	Engine int32 `json:"Engine"`
	Brakes int32 `json:"Brakes"`
	Transmission int32 `json:"Transmission"`
	Horns int32 `json:"Horns"`
	Suspension int32 `json:"Suspension"`
	Armor int32 `json:"Armor"`
	Turbo int32 `json:"Turbo"`
	Xenon int32 `json:"Xenon"`
	FrontWheels int32 `json:"FrontWheels"`
	BackWheels int32 `json:"BackWheels"`
	Plateholders int32 `json:"Plateholders"`
	TrimDesign int32 `json:"TrimDesign"`
	Ornaments int32 `json:"Ornaments"`
	DialDesign int32 `json:"DialDesign"`
	SteeringWheel int32 `json:"SteeringWheel"`
	ShiftLever int32 `json:"ShiftLever"`
	Plaques int32 `json:"Plaques"`
	Hydraulics int32 `json:"Hydraulics"`
	Livery int32 `json:"Livery"`
	Plate int32 `json:"Plate"`
	WindowTint int32 `json:"WindowTint"`
	ModName string `json:"ModName"`
	InteriorColor int32 `json:"InteriorColor"`
	ChipTuning int32 `json:"ChipTuning"`
	PaintArt int32 `json:"PaintArt"`
	WheelColor int32 `json:"WheelColor"`
	WheelType int32 `json:"WheelType"`
	SpawnGarage int32 `json:"SpawnGarage"`
	LastDriver string `json:"LastDriver"`
	PlateText string `json:"PlateText"`
	Fuel string `json:"Fuel"`
	Health int32 `json:"Health"`
	DirtLevel string `json:"DirtLevel"`
	Permission *string `json:"Permission,omitempty"`
}

type _GroupVehicle GroupVehicle

// NewGroupVehicle instantiates a new GroupVehicle object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupVehicle(iD int64, groupID int32, hash string, posX string, posY string, posZ string, rotX string, rotY string, rotZ string, color1 int32, color2 int32, buyDate time.Time, color1R int32, color1G int32, color1B int32, color2R int32, color2G int32, color2B int32, spoilers int32, frontBumper int32, rearBumper int32, sideSkirt int32, exhaust int32, frame int32, grille int32, hood int32, fender int32, rightFender int32, roof int32, engine int32, brakes int32, transmission int32, horns int32, suspension int32, armor int32, turbo int32, xenon int32, frontWheels int32, backWheels int32, plateholders int32, trimDesign int32, ornaments int32, dialDesign int32, steeringWheel int32, shiftLever int32, plaques int32, hydraulics int32, livery int32, plate int32, windowTint int32, modName string, interiorColor int32, chipTuning int32, paintArt int32, wheelColor int32, wheelType int32, spawnGarage int32, lastDriver string, plateText string, fuel string, health int32, dirtLevel string) *GroupVehicle {
	this := GroupVehicle{}
	this.ID = iD
	this.GroupID = groupID
	this.Hash = hash
	this.PosX = posX
	this.PosY = posY
	this.PosZ = posZ
	this.RotX = rotX
	this.RotY = rotY
	this.RotZ = rotZ
	this.Color1 = color1
	this.Color2 = color2
	this.BuyDate = buyDate
	this.Color1R = color1R
	this.Color1G = color1G
	this.Color1B = color1B
	this.Color2R = color2R
	this.Color2G = color2G
	this.Color2B = color2B
	this.Spoilers = spoilers
	this.FrontBumper = frontBumper
	this.RearBumper = rearBumper
	this.SideSkirt = sideSkirt
	this.Exhaust = exhaust
	this.Frame = frame
	this.Grille = grille
	this.Hood = hood
	this.Fender = fender
	this.RightFender = rightFender
	this.Roof = roof
	this.Engine = engine
	this.Brakes = brakes
	this.Transmission = transmission
	this.Horns = horns
	this.Suspension = suspension
	this.Armor = armor
	this.Turbo = turbo
	this.Xenon = xenon
	this.FrontWheels = frontWheels
	this.BackWheels = backWheels
	this.Plateholders = plateholders
	this.TrimDesign = trimDesign
	this.Ornaments = ornaments
	this.DialDesign = dialDesign
	this.SteeringWheel = steeringWheel
	this.ShiftLever = shiftLever
	this.Plaques = plaques
	this.Hydraulics = hydraulics
	this.Livery = livery
	this.Plate = plate
	this.WindowTint = windowTint
	this.ModName = modName
	this.InteriorColor = interiorColor
	this.ChipTuning = chipTuning
	this.PaintArt = paintArt
	this.WheelColor = wheelColor
	this.WheelType = wheelType
	this.SpawnGarage = spawnGarage
	this.LastDriver = lastDriver
	this.PlateText = plateText
	this.Fuel = fuel
	this.Health = health
	this.DirtLevel = dirtLevel
	return &this
}

// NewGroupVehicleWithDefaults instantiates a new GroupVehicle object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupVehicleWithDefaults() *GroupVehicle {
	this := GroupVehicle{}
	return &this
}

// GetID returns the ID field value
func (o *GroupVehicle) GetID() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ID
}

// GetIDOk returns a tuple with the ID field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetIDOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ID, true
}

// SetID sets field value
func (o *GroupVehicle) SetID(v int64) {
	o.ID = v
}

// GetGroupID returns the GroupID field value
func (o *GroupVehicle) GetGroupID() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.GroupID
}

// GetGroupIDOk returns a tuple with the GroupID field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetGroupIDOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GroupID, true
}

// SetGroupID sets field value
func (o *GroupVehicle) SetGroupID(v int32) {
	o.GroupID = v
}

// GetHash returns the Hash field value
func (o *GroupVehicle) GetHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Hash
}

// GetHashOk returns a tuple with the Hash field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hash, true
}

// SetHash sets field value
func (o *GroupVehicle) SetHash(v string) {
	o.Hash = v
}

// GetPosX returns the PosX field value
func (o *GroupVehicle) GetPosX() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PosX
}

// GetPosXOk returns a tuple with the PosX field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetPosXOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PosX, true
}

// SetPosX sets field value
func (o *GroupVehicle) SetPosX(v string) {
	o.PosX = v
}

// GetPosY returns the PosY field value
func (o *GroupVehicle) GetPosY() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PosY
}

// GetPosYOk returns a tuple with the PosY field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetPosYOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PosY, true
}

// SetPosY sets field value
func (o *GroupVehicle) SetPosY(v string) {
	o.PosY = v
}

// GetPosZ returns the PosZ field value
func (o *GroupVehicle) GetPosZ() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PosZ
}

// GetPosZOk returns a tuple with the PosZ field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetPosZOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PosZ, true
}

// SetPosZ sets field value
func (o *GroupVehicle) SetPosZ(v string) {
	o.PosZ = v
}

// GetRotX returns the RotX field value
func (o *GroupVehicle) GetRotX() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RotX
}

// GetRotXOk returns a tuple with the RotX field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetRotXOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RotX, true
}

// SetRotX sets field value
func (o *GroupVehicle) SetRotX(v string) {
	o.RotX = v
}

// GetRotY returns the RotY field value
func (o *GroupVehicle) GetRotY() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RotY
}

// GetRotYOk returns a tuple with the RotY field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetRotYOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RotY, true
}

// SetRotY sets field value
func (o *GroupVehicle) SetRotY(v string) {
	o.RotY = v
}

// GetRotZ returns the RotZ field value
func (o *GroupVehicle) GetRotZ() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RotZ
}

// GetRotZOk returns a tuple with the RotZ field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetRotZOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RotZ, true
}

// SetRotZ sets field value
func (o *GroupVehicle) SetRotZ(v string) {
	o.RotZ = v
}

// GetColor1 returns the Color1 field value
func (o *GroupVehicle) GetColor1() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Color1
}

// GetColor1Ok returns a tuple with the Color1 field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetColor1Ok() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Color1, true
}

// SetColor1 sets field value
func (o *GroupVehicle) SetColor1(v int32) {
	o.Color1 = v
}

// GetColor2 returns the Color2 field value
func (o *GroupVehicle) GetColor2() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Color2
}

// GetColor2Ok returns a tuple with the Color2 field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetColor2Ok() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Color2, true
}

// SetColor2 sets field value
func (o *GroupVehicle) SetColor2(v int32) {
	o.Color2 = v
}

// GetBuyDate returns the BuyDate field value
func (o *GroupVehicle) GetBuyDate() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.BuyDate
}

// GetBuyDateOk returns a tuple with the BuyDate field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetBuyDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BuyDate, true
}

// SetBuyDate sets field value
func (o *GroupVehicle) SetBuyDate(v time.Time) {
	o.BuyDate = v
}

// GetColor1R returns the Color1R field value
func (o *GroupVehicle) GetColor1R() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Color1R
}

// GetColor1ROk returns a tuple with the Color1R field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetColor1ROk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Color1R, true
}

// SetColor1R sets field value
func (o *GroupVehicle) SetColor1R(v int32) {
	o.Color1R = v
}

// GetColor1G returns the Color1G field value
func (o *GroupVehicle) GetColor1G() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Color1G
}

// GetColor1GOk returns a tuple with the Color1G field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetColor1GOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Color1G, true
}

// SetColor1G sets field value
func (o *GroupVehicle) SetColor1G(v int32) {
	o.Color1G = v
}

// GetColor1B returns the Color1B field value
func (o *GroupVehicle) GetColor1B() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Color1B
}

// GetColor1BOk returns a tuple with the Color1B field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetColor1BOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Color1B, true
}

// SetColor1B sets field value
func (o *GroupVehicle) SetColor1B(v int32) {
	o.Color1B = v
}

// GetColor2R returns the Color2R field value
func (o *GroupVehicle) GetColor2R() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Color2R
}

// GetColor2ROk returns a tuple with the Color2R field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetColor2ROk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Color2R, true
}

// SetColor2R sets field value
func (o *GroupVehicle) SetColor2R(v int32) {
	o.Color2R = v
}

// GetColor2G returns the Color2G field value
func (o *GroupVehicle) GetColor2G() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Color2G
}

// GetColor2GOk returns a tuple with the Color2G field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetColor2GOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Color2G, true
}

// SetColor2G sets field value
func (o *GroupVehicle) SetColor2G(v int32) {
	o.Color2G = v
}

// GetColor2B returns the Color2B field value
func (o *GroupVehicle) GetColor2B() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Color2B
}

// GetColor2BOk returns a tuple with the Color2B field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetColor2BOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Color2B, true
}

// SetColor2B sets field value
func (o *GroupVehicle) SetColor2B(v int32) {
	o.Color2B = v
}

// GetSpoilers returns the Spoilers field value
func (o *GroupVehicle) GetSpoilers() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Spoilers
}

// GetSpoilersOk returns a tuple with the Spoilers field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetSpoilersOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Spoilers, true
}

// SetSpoilers sets field value
func (o *GroupVehicle) SetSpoilers(v int32) {
	o.Spoilers = v
}

// GetFrontBumper returns the FrontBumper field value
func (o *GroupVehicle) GetFrontBumper() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.FrontBumper
}

// GetFrontBumperOk returns a tuple with the FrontBumper field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetFrontBumperOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FrontBumper, true
}

// SetFrontBumper sets field value
func (o *GroupVehicle) SetFrontBumper(v int32) {
	o.FrontBumper = v
}

// GetRearBumper returns the RearBumper field value
func (o *GroupVehicle) GetRearBumper() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RearBumper
}

// GetRearBumperOk returns a tuple with the RearBumper field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetRearBumperOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RearBumper, true
}

// SetRearBumper sets field value
func (o *GroupVehicle) SetRearBumper(v int32) {
	o.RearBumper = v
}

// GetSideSkirt returns the SideSkirt field value
func (o *GroupVehicle) GetSideSkirt() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SideSkirt
}

// GetSideSkirtOk returns a tuple with the SideSkirt field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetSideSkirtOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SideSkirt, true
}

// SetSideSkirt sets field value
func (o *GroupVehicle) SetSideSkirt(v int32) {
	o.SideSkirt = v
}

// GetExhaust returns the Exhaust field value
func (o *GroupVehicle) GetExhaust() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Exhaust
}

// GetExhaustOk returns a tuple with the Exhaust field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetExhaustOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Exhaust, true
}

// SetExhaust sets field value
func (o *GroupVehicle) SetExhaust(v int32) {
	o.Exhaust = v
}

// GetFrame returns the Frame field value
func (o *GroupVehicle) GetFrame() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Frame
}

// GetFrameOk returns a tuple with the Frame field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetFrameOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Frame, true
}

// SetFrame sets field value
func (o *GroupVehicle) SetFrame(v int32) {
	o.Frame = v
}

// GetGrille returns the Grille field value
func (o *GroupVehicle) GetGrille() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Grille
}

// GetGrilleOk returns a tuple with the Grille field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetGrilleOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Grille, true
}

// SetGrille sets field value
func (o *GroupVehicle) SetGrille(v int32) {
	o.Grille = v
}

// GetHood returns the Hood field value
func (o *GroupVehicle) GetHood() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Hood
}

// GetHoodOk returns a tuple with the Hood field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetHoodOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hood, true
}

// SetHood sets field value
func (o *GroupVehicle) SetHood(v int32) {
	o.Hood = v
}

// GetFender returns the Fender field value
func (o *GroupVehicle) GetFender() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Fender
}

// GetFenderOk returns a tuple with the Fender field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetFenderOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Fender, true
}

// SetFender sets field value
func (o *GroupVehicle) SetFender(v int32) {
	o.Fender = v
}

// GetRightFender returns the RightFender field value
func (o *GroupVehicle) GetRightFender() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RightFender
}

// GetRightFenderOk returns a tuple with the RightFender field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetRightFenderOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RightFender, true
}

// SetRightFender sets field value
func (o *GroupVehicle) SetRightFender(v int32) {
	o.RightFender = v
}

// GetRoof returns the Roof field value
func (o *GroupVehicle) GetRoof() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Roof
}

// GetRoofOk returns a tuple with the Roof field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetRoofOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Roof, true
}

// SetRoof sets field value
func (o *GroupVehicle) SetRoof(v int32) {
	o.Roof = v
}

// GetEngine returns the Engine field value
func (o *GroupVehicle) GetEngine() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Engine
}

// GetEngineOk returns a tuple with the Engine field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetEngineOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Engine, true
}

// SetEngine sets field value
func (o *GroupVehicle) SetEngine(v int32) {
	o.Engine = v
}

// GetBrakes returns the Brakes field value
func (o *GroupVehicle) GetBrakes() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Brakes
}

// GetBrakesOk returns a tuple with the Brakes field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetBrakesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Brakes, true
}

// SetBrakes sets field value
func (o *GroupVehicle) SetBrakes(v int32) {
	o.Brakes = v
}

// GetTransmission returns the Transmission field value
func (o *GroupVehicle) GetTransmission() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Transmission
}

// GetTransmissionOk returns a tuple with the Transmission field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetTransmissionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Transmission, true
}

// SetTransmission sets field value
func (o *GroupVehicle) SetTransmission(v int32) {
	o.Transmission = v
}

// GetHorns returns the Horns field value
func (o *GroupVehicle) GetHorns() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Horns
}

// GetHornsOk returns a tuple with the Horns field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetHornsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Horns, true
}

// SetHorns sets field value
func (o *GroupVehicle) SetHorns(v int32) {
	o.Horns = v
}

// GetSuspension returns the Suspension field value
func (o *GroupVehicle) GetSuspension() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Suspension
}

// GetSuspensionOk returns a tuple with the Suspension field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetSuspensionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Suspension, true
}

// SetSuspension sets field value
func (o *GroupVehicle) SetSuspension(v int32) {
	o.Suspension = v
}

// GetArmor returns the Armor field value
func (o *GroupVehicle) GetArmor() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Armor
}

// GetArmorOk returns a tuple with the Armor field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetArmorOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Armor, true
}

// SetArmor sets field value
func (o *GroupVehicle) SetArmor(v int32) {
	o.Armor = v
}

// GetTurbo returns the Turbo field value
func (o *GroupVehicle) GetTurbo() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Turbo
}

// GetTurboOk returns a tuple with the Turbo field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetTurboOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Turbo, true
}

// SetTurbo sets field value
func (o *GroupVehicle) SetTurbo(v int32) {
	o.Turbo = v
}

// GetXenon returns the Xenon field value
func (o *GroupVehicle) GetXenon() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Xenon
}

// GetXenonOk returns a tuple with the Xenon field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetXenonOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Xenon, true
}

// SetXenon sets field value
func (o *GroupVehicle) SetXenon(v int32) {
	o.Xenon = v
}

// GetFrontWheels returns the FrontWheels field value
func (o *GroupVehicle) GetFrontWheels() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.FrontWheels
}

// GetFrontWheelsOk returns a tuple with the FrontWheels field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetFrontWheelsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FrontWheels, true
}

// SetFrontWheels sets field value
func (o *GroupVehicle) SetFrontWheels(v int32) {
	o.FrontWheels = v
}

// GetBackWheels returns the BackWheels field value
func (o *GroupVehicle) GetBackWheels() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.BackWheels
}

// GetBackWheelsOk returns a tuple with the BackWheels field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetBackWheelsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BackWheels, true
}

// SetBackWheels sets field value
func (o *GroupVehicle) SetBackWheels(v int32) {
	o.BackWheels = v
}

// GetPlateholders returns the Plateholders field value
func (o *GroupVehicle) GetPlateholders() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Plateholders
}

// GetPlateholdersOk returns a tuple with the Plateholders field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetPlateholdersOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Plateholders, true
}

// SetPlateholders sets field value
func (o *GroupVehicle) SetPlateholders(v int32) {
	o.Plateholders = v
}

// GetTrimDesign returns the TrimDesign field value
func (o *GroupVehicle) GetTrimDesign() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TrimDesign
}

// GetTrimDesignOk returns a tuple with the TrimDesign field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetTrimDesignOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TrimDesign, true
}

// SetTrimDesign sets field value
func (o *GroupVehicle) SetTrimDesign(v int32) {
	o.TrimDesign = v
}

// GetOrnaments returns the Ornaments field value
func (o *GroupVehicle) GetOrnaments() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Ornaments
}

// GetOrnamentsOk returns a tuple with the Ornaments field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetOrnamentsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ornaments, true
}

// SetOrnaments sets field value
func (o *GroupVehicle) SetOrnaments(v int32) {
	o.Ornaments = v
}

// GetDialDesign returns the DialDesign field value
func (o *GroupVehicle) GetDialDesign() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DialDesign
}

// GetDialDesignOk returns a tuple with the DialDesign field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetDialDesignOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DialDesign, true
}

// SetDialDesign sets field value
func (o *GroupVehicle) SetDialDesign(v int32) {
	o.DialDesign = v
}

// GetSteeringWheel returns the SteeringWheel field value
func (o *GroupVehicle) GetSteeringWheel() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SteeringWheel
}

// GetSteeringWheelOk returns a tuple with the SteeringWheel field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetSteeringWheelOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SteeringWheel, true
}

// SetSteeringWheel sets field value
func (o *GroupVehicle) SetSteeringWheel(v int32) {
	o.SteeringWheel = v
}

// GetShiftLever returns the ShiftLever field value
func (o *GroupVehicle) GetShiftLever() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ShiftLever
}

// GetShiftLeverOk returns a tuple with the ShiftLever field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetShiftLeverOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ShiftLever, true
}

// SetShiftLever sets field value
func (o *GroupVehicle) SetShiftLever(v int32) {
	o.ShiftLever = v
}

// GetPlaques returns the Plaques field value
func (o *GroupVehicle) GetPlaques() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Plaques
}

// GetPlaquesOk returns a tuple with the Plaques field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetPlaquesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Plaques, true
}

// SetPlaques sets field value
func (o *GroupVehicle) SetPlaques(v int32) {
	o.Plaques = v
}

// GetHydraulics returns the Hydraulics field value
func (o *GroupVehicle) GetHydraulics() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Hydraulics
}

// GetHydraulicsOk returns a tuple with the Hydraulics field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetHydraulicsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hydraulics, true
}

// SetHydraulics sets field value
func (o *GroupVehicle) SetHydraulics(v int32) {
	o.Hydraulics = v
}

// GetLivery returns the Livery field value
func (o *GroupVehicle) GetLivery() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Livery
}

// GetLiveryOk returns a tuple with the Livery field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetLiveryOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Livery, true
}

// SetLivery sets field value
func (o *GroupVehicle) SetLivery(v int32) {
	o.Livery = v
}

// GetPlate returns the Plate field value
func (o *GroupVehicle) GetPlate() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Plate
}

// GetPlateOk returns a tuple with the Plate field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetPlateOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Plate, true
}

// SetPlate sets field value
func (o *GroupVehicle) SetPlate(v int32) {
	o.Plate = v
}

// GetWindowTint returns the WindowTint field value
func (o *GroupVehicle) GetWindowTint() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.WindowTint
}

// GetWindowTintOk returns a tuple with the WindowTint field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetWindowTintOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WindowTint, true
}

// SetWindowTint sets field value
func (o *GroupVehicle) SetWindowTint(v int32) {
	o.WindowTint = v
}

// GetModName returns the ModName field value
func (o *GroupVehicle) GetModName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ModName
}

// GetModNameOk returns a tuple with the ModName field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetModNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModName, true
}

// SetModName sets field value
func (o *GroupVehicle) SetModName(v string) {
	o.ModName = v
}

// GetInteriorColor returns the InteriorColor field value
func (o *GroupVehicle) GetInteriorColor() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.InteriorColor
}

// GetInteriorColorOk returns a tuple with the InteriorColor field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetInteriorColorOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InteriorColor, true
}

// SetInteriorColor sets field value
func (o *GroupVehicle) SetInteriorColor(v int32) {
	o.InteriorColor = v
}

// GetChipTuning returns the ChipTuning field value
func (o *GroupVehicle) GetChipTuning() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ChipTuning
}

// GetChipTuningOk returns a tuple with the ChipTuning field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetChipTuningOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChipTuning, true
}

// SetChipTuning sets field value
func (o *GroupVehicle) SetChipTuning(v int32) {
	o.ChipTuning = v
}

// GetPaintArt returns the PaintArt field value
func (o *GroupVehicle) GetPaintArt() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PaintArt
}

// GetPaintArtOk returns a tuple with the PaintArt field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetPaintArtOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PaintArt, true
}

// SetPaintArt sets field value
func (o *GroupVehicle) SetPaintArt(v int32) {
	o.PaintArt = v
}

// GetWheelColor returns the WheelColor field value
func (o *GroupVehicle) GetWheelColor() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.WheelColor
}

// GetWheelColorOk returns a tuple with the WheelColor field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetWheelColorOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WheelColor, true
}

// SetWheelColor sets field value
func (o *GroupVehicle) SetWheelColor(v int32) {
	o.WheelColor = v
}

// GetWheelType returns the WheelType field value
func (o *GroupVehicle) GetWheelType() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.WheelType
}

// GetWheelTypeOk returns a tuple with the WheelType field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetWheelTypeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WheelType, true
}

// SetWheelType sets field value
func (o *GroupVehicle) SetWheelType(v int32) {
	o.WheelType = v
}

// GetSpawnGarage returns the SpawnGarage field value
func (o *GroupVehicle) GetSpawnGarage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SpawnGarage
}

// GetSpawnGarageOk returns a tuple with the SpawnGarage field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetSpawnGarageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SpawnGarage, true
}

// SetSpawnGarage sets field value
func (o *GroupVehicle) SetSpawnGarage(v int32) {
	o.SpawnGarage = v
}

// GetLastDriver returns the LastDriver field value
func (o *GroupVehicle) GetLastDriver() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastDriver
}

// GetLastDriverOk returns a tuple with the LastDriver field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetLastDriverOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastDriver, true
}

// SetLastDriver sets field value
func (o *GroupVehicle) SetLastDriver(v string) {
	o.LastDriver = v
}

// GetPlateText returns the PlateText field value
func (o *GroupVehicle) GetPlateText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PlateText
}

// GetPlateTextOk returns a tuple with the PlateText field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetPlateTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlateText, true
}

// SetPlateText sets field value
func (o *GroupVehicle) SetPlateText(v string) {
	o.PlateText = v
}

// GetFuel returns the Fuel field value
func (o *GroupVehicle) GetFuel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Fuel
}

// GetFuelOk returns a tuple with the Fuel field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetFuelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Fuel, true
}

// SetFuel sets field value
func (o *GroupVehicle) SetFuel(v string) {
	o.Fuel = v
}

// GetHealth returns the Health field value
func (o *GroupVehicle) GetHealth() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Health
}

// GetHealthOk returns a tuple with the Health field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetHealthOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Health, true
}

// SetHealth sets field value
func (o *GroupVehicle) SetHealth(v int32) {
	o.Health = v
}

// GetDirtLevel returns the DirtLevel field value
func (o *GroupVehicle) GetDirtLevel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DirtLevel
}

// GetDirtLevelOk returns a tuple with the DirtLevel field value
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetDirtLevelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DirtLevel, true
}

// SetDirtLevel sets field value
func (o *GroupVehicle) SetDirtLevel(v string) {
	o.DirtLevel = v
}

// GetPermission returns the Permission field value if set, zero value otherwise.
func (o *GroupVehicle) GetPermission() string {
	if o == nil || IsNil(o.Permission) {
		var ret string
		return ret
	}
	return *o.Permission
}

// GetPermissionOk returns a tuple with the Permission field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupVehicle) GetPermissionOk() (*string, bool) {
	if o == nil || IsNil(o.Permission) {
		return nil, false
	}
	return o.Permission, true
}

// HasPermission returns a boolean if a field has been set.
func (o *GroupVehicle) HasPermission() bool {
	if o != nil && !IsNil(o.Permission) {
		return true
	}

	return false
}

// SetPermission gets a reference to the given string and assigns it to the Permission field.
func (o *GroupVehicle) SetPermission(v string) {
	o.Permission = &v
}

func (o GroupVehicle) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupVehicle) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ID"] = o.ID
	toSerialize["GroupID"] = o.GroupID
	toSerialize["Hash"] = o.Hash
	toSerialize["PosX"] = o.PosX
	toSerialize["PosY"] = o.PosY
	toSerialize["PosZ"] = o.PosZ
	toSerialize["RotX"] = o.RotX
	toSerialize["RotY"] = o.RotY
	toSerialize["RotZ"] = o.RotZ
	toSerialize["Color1"] = o.Color1
	toSerialize["Color2"] = o.Color2
	toSerialize["BuyDate"] = o.BuyDate
	toSerialize["Color1R"] = o.Color1R
	toSerialize["Color1G"] = o.Color1G
	toSerialize["Color1B"] = o.Color1B
	toSerialize["Color2R"] = o.Color2R
	toSerialize["Color2G"] = o.Color2G
	toSerialize["Color2B"] = o.Color2B
	toSerialize["Spoilers"] = o.Spoilers
	toSerialize["FrontBumper"] = o.FrontBumper
	toSerialize["RearBumper"] = o.RearBumper
	toSerialize["SideSkirt"] = o.SideSkirt
	toSerialize["Exhaust"] = o.Exhaust
	toSerialize["Frame"] = o.Frame
	toSerialize["Grille"] = o.Grille
	toSerialize["Hood"] = o.Hood
	toSerialize["Fender"] = o.Fender
	toSerialize["RightFender"] = o.RightFender
	toSerialize["Roof"] = o.Roof
	toSerialize["Engine"] = o.Engine
	toSerialize["Brakes"] = o.Brakes
	toSerialize["Transmission"] = o.Transmission
	toSerialize["Horns"] = o.Horns
	toSerialize["Suspension"] = o.Suspension
	toSerialize["Armor"] = o.Armor
	toSerialize["Turbo"] = o.Turbo
	toSerialize["Xenon"] = o.Xenon
	toSerialize["FrontWheels"] = o.FrontWheels
	toSerialize["BackWheels"] = o.BackWheels
	toSerialize["Plateholders"] = o.Plateholders
	toSerialize["TrimDesign"] = o.TrimDesign
	toSerialize["Ornaments"] = o.Ornaments
	toSerialize["DialDesign"] = o.DialDesign
	toSerialize["SteeringWheel"] = o.SteeringWheel
	toSerialize["ShiftLever"] = o.ShiftLever
	toSerialize["Plaques"] = o.Plaques
	toSerialize["Hydraulics"] = o.Hydraulics
	toSerialize["Livery"] = o.Livery
	toSerialize["Plate"] = o.Plate
	toSerialize["WindowTint"] = o.WindowTint
	toSerialize["ModName"] = o.ModName
	toSerialize["InteriorColor"] = o.InteriorColor
	toSerialize["ChipTuning"] = o.ChipTuning
	toSerialize["PaintArt"] = o.PaintArt
	toSerialize["WheelColor"] = o.WheelColor
	toSerialize["WheelType"] = o.WheelType
	toSerialize["SpawnGarage"] = o.SpawnGarage
	toSerialize["LastDriver"] = o.LastDriver
	toSerialize["PlateText"] = o.PlateText
	toSerialize["Fuel"] = o.Fuel
	toSerialize["Health"] = o.Health
	toSerialize["DirtLevel"] = o.DirtLevel
	if !IsNil(o.Permission) {
		toSerialize["Permission"] = o.Permission
	}
	return toSerialize, nil
}

func (o *GroupVehicle) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ID",
		"GroupID",
		"Hash",
		"PosX",
		"PosY",
		"PosZ",
		"RotX",
		"RotY",
		"RotZ",
		"Color1",
		"Color2",
		"BuyDate",
		"Color1R",
		"Color1G",
		"Color1B",
		"Color2R",
		"Color2G",
		"Color2B",
		"Spoilers",
		"FrontBumper",
		"RearBumper",
		"SideSkirt",
		"Exhaust",
		"Frame",
		"Grille",
		"Hood",
		"Fender",
		"RightFender",
		"Roof",
		"Engine",
		"Brakes",
		"Transmission",
		"Horns",
		"Suspension",
		"Armor",
		"Turbo",
		"Xenon",
		"FrontWheels",
		"BackWheels",
		"Plateholders",
		"TrimDesign",
		"Ornaments",
		"DialDesign",
		"SteeringWheel",
		"ShiftLever",
		"Plaques",
		"Hydraulics",
		"Livery",
		"Plate",
		"WindowTint",
		"ModName",
		"InteriorColor",
		"ChipTuning",
		"PaintArt",
		"WheelColor",
		"WheelType",
		"SpawnGarage",
		"LastDriver",
		"PlateText",
		"Fuel",
		"Health",
		"DirtLevel",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGroupVehicle := _GroupVehicle{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGroupVehicle)

	if err != nil {
		return err
	}

	*o = GroupVehicle(varGroupVehicle)

	return err
}

type NullableGroupVehicle struct {
	value *GroupVehicle
	isSet bool
}

func (v NullableGroupVehicle) Get() *GroupVehicle {
	return v.value
}

func (v *NullableGroupVehicle) Set(val *GroupVehicle) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupVehicle) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupVehicle) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupVehicle(val *GroupVehicle) *NullableGroupVehicle {
	return &NullableGroupVehicle{value: val, isSet: true}
}

func (v NullableGroupVehicle) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupVehicle) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


