/*
Vio-V

Vio-V API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GroupShop type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupShop{}

// GroupShop struct for GroupShop
type GroupShop struct {
	ShopId int32 `json:"ShopId"`
	Money int32 `json:"Money"`
	Mats int32 `json:"Mats"`
}

type _GroupShop GroupShop

// NewGroupShop instantiates a new GroupShop object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupShop(shopId int32, money int32, mats int32) *GroupShop {
	this := GroupShop{}
	this.ShopId = shopId
	this.Money = money
	this.Mats = mats
	return &this
}

// NewGroupShopWithDefaults instantiates a new GroupShop object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupShopWithDefaults() *GroupShop {
	this := GroupShop{}
	return &this
}

// GetShopId returns the ShopId field value
func (o *GroupShop) GetShopId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ShopId
}

// GetShopIdOk returns a tuple with the ShopId field value
// and a boolean to check if the value has been set.
func (o *GroupShop) GetShopIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ShopId, true
}

// SetShopId sets field value
func (o *GroupShop) SetShopId(v int32) {
	o.ShopId = v
}

// GetMoney returns the Money field value
func (o *GroupShop) GetMoney() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Money
}

// GetMoneyOk returns a tuple with the Money field value
// and a boolean to check if the value has been set.
func (o *GroupShop) GetMoneyOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Money, true
}

// SetMoney sets field value
func (o *GroupShop) SetMoney(v int32) {
	o.Money = v
}

// GetMats returns the Mats field value
func (o *GroupShop) GetMats() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Mats
}

// GetMatsOk returns a tuple with the Mats field value
// and a boolean to check if the value has been set.
func (o *GroupShop) GetMatsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mats, true
}

// SetMats sets field value
func (o *GroupShop) SetMats(v int32) {
	o.Mats = v
}

func (o GroupShop) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupShop) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ShopId"] = o.ShopId
	toSerialize["Money"] = o.Money
	toSerialize["Mats"] = o.Mats
	return toSerialize, nil
}

func (o *GroupShop) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ShopId",
		"Money",
		"Mats",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGroupShop := _GroupShop{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGroupShop)

	if err != nil {
		return err
	}

	*o = GroupShop(varGroupShop)

	return err
}

type NullableGroupShop struct {
	value *GroupShop
	isSet bool
}

func (v NullableGroupShop) Get() *GroupShop {
	return v.value
}

func (v *NullableGroupShop) Set(val *GroupShop) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupShop) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupShop) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupShop(val *GroupShop) *NullableGroupShop {
	return &NullableGroupShop{value: val, isSet: true}
}

func (v NullableGroupShop) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupShop) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


