/*
Vio-V

Vio-V API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GangArea type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GangArea{}

// GangArea struct for GangArea
type GangArea struct {
	ID int32 `json:"ID"`
	DistriktID int32 `json:"DistriktID"`
	Name string `json:"Name"`
	X float32 `json:"X"`
	Y float32 `json:"Y"`
	Z float32 `json:"Z"`
	Range int32 `json:"Range"`
	Rotation int32 `json:"Rotation"`
	Owner int32 `json:"Owner"`
	LastAttack int32 `json:"LastAttack"`
	ItemID int32 `json:"ItemID"`
	Amount int32 `json:"Amount"`
	Impact int32 `json:"Impact"`
	OldOwner int32 `json:"OldOwner"`
}

type _GangArea GangArea

// NewGangArea instantiates a new GangArea object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGangArea(iD int32, distriktID int32, name string, x float32, y float32, z float32, range_ int32, rotation int32, owner int32, lastAttack int32, itemID int32, amount int32, impact int32, oldOwner int32) *GangArea {
	this := GangArea{}
	this.ID = iD
	this.DistriktID = distriktID
	this.Name = name
	this.X = x
	this.Y = y
	this.Z = z
	this.Range = range_
	this.Rotation = rotation
	this.Owner = owner
	this.LastAttack = lastAttack
	this.ItemID = itemID
	this.Amount = amount
	this.Impact = impact
	this.OldOwner = oldOwner
	return &this
}

// NewGangAreaWithDefaults instantiates a new GangArea object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGangAreaWithDefaults() *GangArea {
	this := GangArea{}
	return &this
}

// GetID returns the ID field value
func (o *GangArea) GetID() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ID
}

// GetIDOk returns a tuple with the ID field value
// and a boolean to check if the value has been set.
func (o *GangArea) GetIDOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ID, true
}

// SetID sets field value
func (o *GangArea) SetID(v int32) {
	o.ID = v
}

// GetDistriktID returns the DistriktID field value
func (o *GangArea) GetDistriktID() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DistriktID
}

// GetDistriktIDOk returns a tuple with the DistriktID field value
// and a boolean to check if the value has been set.
func (o *GangArea) GetDistriktIDOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DistriktID, true
}

// SetDistriktID sets field value
func (o *GangArea) SetDistriktID(v int32) {
	o.DistriktID = v
}

// GetName returns the Name field value
func (o *GangArea) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GangArea) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GangArea) SetName(v string) {
	o.Name = v
}

// GetX returns the X field value
func (o *GangArea) GetX() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.X
}

// GetXOk returns a tuple with the X field value
// and a boolean to check if the value has been set.
func (o *GangArea) GetXOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.X, true
}

// SetX sets field value
func (o *GangArea) SetX(v float32) {
	o.X = v
}

// GetY returns the Y field value
func (o *GangArea) GetY() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Y
}

// GetYOk returns a tuple with the Y field value
// and a boolean to check if the value has been set.
func (o *GangArea) GetYOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Y, true
}

// SetY sets field value
func (o *GangArea) SetY(v float32) {
	o.Y = v
}

// GetZ returns the Z field value
func (o *GangArea) GetZ() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Z
}

// GetZOk returns a tuple with the Z field value
// and a boolean to check if the value has been set.
func (o *GangArea) GetZOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Z, true
}

// SetZ sets field value
func (o *GangArea) SetZ(v float32) {
	o.Z = v
}

// GetRange returns the Range field value
func (o *GangArea) GetRange() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Range
}

// GetRangeOk returns a tuple with the Range field value
// and a boolean to check if the value has been set.
func (o *GangArea) GetRangeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Range, true
}

// SetRange sets field value
func (o *GangArea) SetRange(v int32) {
	o.Range = v
}

// GetRotation returns the Rotation field value
func (o *GangArea) GetRotation() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Rotation
}

// GetRotationOk returns a tuple with the Rotation field value
// and a boolean to check if the value has been set.
func (o *GangArea) GetRotationOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rotation, true
}

// SetRotation sets field value
func (o *GangArea) SetRotation(v int32) {
	o.Rotation = v
}

// GetOwner returns the Owner field value
func (o *GangArea) GetOwner() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value
// and a boolean to check if the value has been set.
func (o *GangArea) GetOwnerOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Owner, true
}

// SetOwner sets field value
func (o *GangArea) SetOwner(v int32) {
	o.Owner = v
}

// GetLastAttack returns the LastAttack field value
func (o *GangArea) GetLastAttack() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.LastAttack
}

// GetLastAttackOk returns a tuple with the LastAttack field value
// and a boolean to check if the value has been set.
func (o *GangArea) GetLastAttackOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastAttack, true
}

// SetLastAttack sets field value
func (o *GangArea) SetLastAttack(v int32) {
	o.LastAttack = v
}

// GetItemID returns the ItemID field value
func (o *GangArea) GetItemID() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ItemID
}

// GetItemIDOk returns a tuple with the ItemID field value
// and a boolean to check if the value has been set.
func (o *GangArea) GetItemIDOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ItemID, true
}

// SetItemID sets field value
func (o *GangArea) SetItemID(v int32) {
	o.ItemID = v
}

// GetAmount returns the Amount field value
func (o *GangArea) GetAmount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *GangArea) GetAmountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *GangArea) SetAmount(v int32) {
	o.Amount = v
}

// GetImpact returns the Impact field value
func (o *GangArea) GetImpact() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Impact
}

// GetImpactOk returns a tuple with the Impact field value
// and a boolean to check if the value has been set.
func (o *GangArea) GetImpactOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Impact, true
}

// SetImpact sets field value
func (o *GangArea) SetImpact(v int32) {
	o.Impact = v
}

// GetOldOwner returns the OldOwner field value
func (o *GangArea) GetOldOwner() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.OldOwner
}

// GetOldOwnerOk returns a tuple with the OldOwner field value
// and a boolean to check if the value has been set.
func (o *GangArea) GetOldOwnerOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OldOwner, true
}

// SetOldOwner sets field value
func (o *GangArea) SetOldOwner(v int32) {
	o.OldOwner = v
}

func (o GangArea) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GangArea) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ID"] = o.ID
	toSerialize["DistriktID"] = o.DistriktID
	toSerialize["Name"] = o.Name
	toSerialize["X"] = o.X
	toSerialize["Y"] = o.Y
	toSerialize["Z"] = o.Z
	toSerialize["Range"] = o.Range
	toSerialize["Rotation"] = o.Rotation
	toSerialize["Owner"] = o.Owner
	toSerialize["LastAttack"] = o.LastAttack
	toSerialize["ItemID"] = o.ItemID
	toSerialize["Amount"] = o.Amount
	toSerialize["Impact"] = o.Impact
	toSerialize["OldOwner"] = o.OldOwner
	return toSerialize, nil
}

func (o *GangArea) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ID",
		"DistriktID",
		"Name",
		"X",
		"Y",
		"Z",
		"Range",
		"Rotation",
		"Owner",
		"LastAttack",
		"ItemID",
		"Amount",
		"Impact",
		"OldOwner",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGangArea := _GangArea{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGangArea)

	if err != nil {
		return err
	}

	*o = GangArea(varGangArea)

	return err
}

type NullableGangArea struct {
	value *GangArea
	isSet bool
}

func (v NullableGangArea) Get() *GangArea {
	return v.value
}

func (v *NullableGangArea) Set(val *GangArea) {
	v.value = val
	v.isSet = true
}

func (v NullableGangArea) IsSet() bool {
	return v.isSet
}

func (v *NullableGangArea) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGangArea(val *GangArea) *NullableGangArea {
	return &NullableGangArea{value: val, isSet: true}
}

func (v NullableGangArea) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGangArea) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


