/*
Vio-V

Vio-V API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GroupLSPDBlacklist type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupLSPDBlacklist{}

// GroupLSPDBlacklist struct for GroupLSPDBlacklist
type GroupLSPDBlacklist struct {
	GroupID int32 `json:"GroupID"`
	GroupName *string `json:"GroupName,omitempty"`
	Expiry int32 `json:"Expiry"`
	Reason string `json:"Reason"`
	Creator string `json:"Creator"`
}

type _GroupLSPDBlacklist GroupLSPDBlacklist

// NewGroupLSPDBlacklist instantiates a new GroupLSPDBlacklist object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupLSPDBlacklist(groupID int32, expiry int32, reason string, creator string) *GroupLSPDBlacklist {
	this := GroupLSPDBlacklist{}
	this.GroupID = groupID
	this.Expiry = expiry
	this.Reason = reason
	this.Creator = creator
	return &this
}

// NewGroupLSPDBlacklistWithDefaults instantiates a new GroupLSPDBlacklist object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupLSPDBlacklistWithDefaults() *GroupLSPDBlacklist {
	this := GroupLSPDBlacklist{}
	return &this
}

// GetGroupID returns the GroupID field value
func (o *GroupLSPDBlacklist) GetGroupID() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.GroupID
}

// GetGroupIDOk returns a tuple with the GroupID field value
// and a boolean to check if the value has been set.
func (o *GroupLSPDBlacklist) GetGroupIDOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GroupID, true
}

// SetGroupID sets field value
func (o *GroupLSPDBlacklist) SetGroupID(v int32) {
	o.GroupID = v
}

// GetGroupName returns the GroupName field value if set, zero value otherwise.
func (o *GroupLSPDBlacklist) GetGroupName() string {
	if o == nil || IsNil(o.GroupName) {
		var ret string
		return ret
	}
	return *o.GroupName
}

// GetGroupNameOk returns a tuple with the GroupName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupLSPDBlacklist) GetGroupNameOk() (*string, bool) {
	if o == nil || IsNil(o.GroupName) {
		return nil, false
	}
	return o.GroupName, true
}

// HasGroupName returns a boolean if a field has been set.
func (o *GroupLSPDBlacklist) HasGroupName() bool {
	if o != nil && !IsNil(o.GroupName) {
		return true
	}

	return false
}

// SetGroupName gets a reference to the given string and assigns it to the GroupName field.
func (o *GroupLSPDBlacklist) SetGroupName(v string) {
	o.GroupName = &v
}

// GetExpiry returns the Expiry field value
func (o *GroupLSPDBlacklist) GetExpiry() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Expiry
}

// GetExpiryOk returns a tuple with the Expiry field value
// and a boolean to check if the value has been set.
func (o *GroupLSPDBlacklist) GetExpiryOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Expiry, true
}

// SetExpiry sets field value
func (o *GroupLSPDBlacklist) SetExpiry(v int32) {
	o.Expiry = v
}

// GetReason returns the Reason field value
func (o *GroupLSPDBlacklist) GetReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Reason
}

// GetReasonOk returns a tuple with the Reason field value
// and a boolean to check if the value has been set.
func (o *GroupLSPDBlacklist) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reason, true
}

// SetReason sets field value
func (o *GroupLSPDBlacklist) SetReason(v string) {
	o.Reason = v
}

// GetCreator returns the Creator field value
func (o *GroupLSPDBlacklist) GetCreator() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Creator
}

// GetCreatorOk returns a tuple with the Creator field value
// and a boolean to check if the value has been set.
func (o *GroupLSPDBlacklist) GetCreatorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Creator, true
}

// SetCreator sets field value
func (o *GroupLSPDBlacklist) SetCreator(v string) {
	o.Creator = v
}

func (o GroupLSPDBlacklist) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupLSPDBlacklist) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["GroupID"] = o.GroupID
	if !IsNil(o.GroupName) {
		toSerialize["GroupName"] = o.GroupName
	}
	toSerialize["Expiry"] = o.Expiry
	toSerialize["Reason"] = o.Reason
	toSerialize["Creator"] = o.Creator
	return toSerialize, nil
}

func (o *GroupLSPDBlacklist) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"GroupID",
		"Expiry",
		"Reason",
		"Creator",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGroupLSPDBlacklist := _GroupLSPDBlacklist{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGroupLSPDBlacklist)

	if err != nil {
		return err
	}

	*o = GroupLSPDBlacklist(varGroupLSPDBlacklist)

	return err
}

type NullableGroupLSPDBlacklist struct {
	value *GroupLSPDBlacklist
	isSet bool
}

func (v NullableGroupLSPDBlacklist) Get() *GroupLSPDBlacklist {
	return v.value
}

func (v *NullableGroupLSPDBlacklist) Set(val *GroupLSPDBlacklist) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupLSPDBlacklist) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupLSPDBlacklist) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupLSPDBlacklist(val *GroupLSPDBlacklist) *NullableGroupLSPDBlacklist {
	return &NullableGroupLSPDBlacklist{value: val, isSet: true}
}

func (v NullableGroupLSPDBlacklist) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupLSPDBlacklist) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


