/*
Vio-V

Vio-V API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GroupStorageLog type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupStorageLog{}

// GroupStorageLog struct for GroupStorageLog
type GroupStorageLog struct {
	GroupID int32 `json:"GroupID"`
	Name string `json:"Name"`
	Amount string `json:"Amount"`
	Item string `json:"Item"`
	Timestamp string `json:"Timestamp"`
}

type _GroupStorageLog GroupStorageLog

// NewGroupStorageLog instantiates a new GroupStorageLog object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupStorageLog(groupID int32, name string, amount string, item string, timestamp string) *GroupStorageLog {
	this := GroupStorageLog{}
	this.GroupID = groupID
	this.Name = name
	this.Amount = amount
	this.Item = item
	this.Timestamp = timestamp
	return &this
}

// NewGroupStorageLogWithDefaults instantiates a new GroupStorageLog object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupStorageLogWithDefaults() *GroupStorageLog {
	this := GroupStorageLog{}
	return &this
}

// GetGroupID returns the GroupID field value
func (o *GroupStorageLog) GetGroupID() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.GroupID
}

// GetGroupIDOk returns a tuple with the GroupID field value
// and a boolean to check if the value has been set.
func (o *GroupStorageLog) GetGroupIDOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GroupID, true
}

// SetGroupID sets field value
func (o *GroupStorageLog) SetGroupID(v int32) {
	o.GroupID = v
}

// GetName returns the Name field value
func (o *GroupStorageLog) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GroupStorageLog) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GroupStorageLog) SetName(v string) {
	o.Name = v
}

// GetAmount returns the Amount field value
func (o *GroupStorageLog) GetAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *GroupStorageLog) GetAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *GroupStorageLog) SetAmount(v string) {
	o.Amount = v
}

// GetItem returns the Item field value
func (o *GroupStorageLog) GetItem() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Item
}

// GetItemOk returns a tuple with the Item field value
// and a boolean to check if the value has been set.
func (o *GroupStorageLog) GetItemOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Item, true
}

// SetItem sets field value
func (o *GroupStorageLog) SetItem(v string) {
	o.Item = v
}

// GetTimestamp returns the Timestamp field value
func (o *GroupStorageLog) GetTimestamp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *GroupStorageLog) GetTimestampOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *GroupStorageLog) SetTimestamp(v string) {
	o.Timestamp = v
}

func (o GroupStorageLog) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupStorageLog) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["GroupID"] = o.GroupID
	toSerialize["Name"] = o.Name
	toSerialize["Amount"] = o.Amount
	toSerialize["Item"] = o.Item
	toSerialize["Timestamp"] = o.Timestamp
	return toSerialize, nil
}

func (o *GroupStorageLog) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"GroupID",
		"Name",
		"Amount",
		"Item",
		"Timestamp",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGroupStorageLog := _GroupStorageLog{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGroupStorageLog)

	if err != nil {
		return err
	}

	*o = GroupStorageLog(varGroupStorageLog)

	return err
}

type NullableGroupStorageLog struct {
	value *GroupStorageLog
	isSet bool
}

func (v NullableGroupStorageLog) Get() *GroupStorageLog {
	return v.value
}

func (v *NullableGroupStorageLog) Set(val *GroupStorageLog) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupStorageLog) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupStorageLog) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupStorageLog(val *GroupStorageLog) *NullableGroupStorageLog {
	return &NullableGroupStorageLog{value: val, isSet: true}
}

func (v NullableGroupStorageLog) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupStorageLog) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


