/*
Vio-V

Vio-V API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CharacterPlaytime type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CharacterPlaytime{}

// CharacterPlaytime struct for CharacterPlaytime
type CharacterPlaytime struct {
	ID *int32 `json:"ID,omitempty"`
	Timestamp *int64 `json:"Timestamp,omitempty"`
	Minutes *int32 `json:"Minutes,omitempty"`
}

// NewCharacterPlaytime instantiates a new CharacterPlaytime object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCharacterPlaytime() *CharacterPlaytime {
	this := CharacterPlaytime{}
	return &this
}

// NewCharacterPlaytimeWithDefaults instantiates a new CharacterPlaytime object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCharacterPlaytimeWithDefaults() *CharacterPlaytime {
	this := CharacterPlaytime{}
	return &this
}

// GetID returns the ID field value if set, zero value otherwise.
func (o *CharacterPlaytime) GetID() int32 {
	if o == nil || IsNil(o.ID) {
		var ret int32
		return ret
	}
	return *o.ID
}

// GetIDOk returns a tuple with the ID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CharacterPlaytime) GetIDOk() (*int32, bool) {
	if o == nil || IsNil(o.ID) {
		return nil, false
	}
	return o.ID, true
}

// HasID returns a boolean if a field has been set.
func (o *CharacterPlaytime) HasID() bool {
	if o != nil && !IsNil(o.ID) {
		return true
	}

	return false
}

// SetID gets a reference to the given int32 and assigns it to the ID field.
func (o *CharacterPlaytime) SetID(v int32) {
	o.ID = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *CharacterPlaytime) GetTimestamp() int64 {
	if o == nil || IsNil(o.Timestamp) {
		var ret int64
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CharacterPlaytime) GetTimestampOk() (*int64, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *CharacterPlaytime) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given int64 and assigns it to the Timestamp field.
func (o *CharacterPlaytime) SetTimestamp(v int64) {
	o.Timestamp = &v
}

// GetMinutes returns the Minutes field value if set, zero value otherwise.
func (o *CharacterPlaytime) GetMinutes() int32 {
	if o == nil || IsNil(o.Minutes) {
		var ret int32
		return ret
	}
	return *o.Minutes
}

// GetMinutesOk returns a tuple with the Minutes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CharacterPlaytime) GetMinutesOk() (*int32, bool) {
	if o == nil || IsNil(o.Minutes) {
		return nil, false
	}
	return o.Minutes, true
}

// HasMinutes returns a boolean if a field has been set.
func (o *CharacterPlaytime) HasMinutes() bool {
	if o != nil && !IsNil(o.Minutes) {
		return true
	}

	return false
}

// SetMinutes gets a reference to the given int32 and assigns it to the Minutes field.
func (o *CharacterPlaytime) SetMinutes(v int32) {
	o.Minutes = &v
}

func (o CharacterPlaytime) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CharacterPlaytime) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ID) {
		toSerialize["ID"] = o.ID
	}
	if !IsNil(o.Timestamp) {
		toSerialize["Timestamp"] = o.Timestamp
	}
	if !IsNil(o.Minutes) {
		toSerialize["Minutes"] = o.Minutes
	}
	return toSerialize, nil
}

type NullableCharacterPlaytime struct {
	value *CharacterPlaytime
	isSet bool
}

func (v NullableCharacterPlaytime) Get() *CharacterPlaytime {
	return v.value
}

func (v *NullableCharacterPlaytime) Set(val *CharacterPlaytime) {
	v.value = val
	v.isSet = true
}

func (v NullableCharacterPlaytime) IsSet() bool {
	return v.isSet
}

func (v *NullableCharacterPlaytime) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCharacterPlaytime(val *CharacterPlaytime) *NullableCharacterPlaytime {
	return &NullableCharacterPlaytime{value: val, isSet: true}
}

func (v NullableCharacterPlaytime) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCharacterPlaytime) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


