/*
Vio-V

Vio-V API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SystemItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SystemItem{}

// SystemItem struct for SystemItem
type SystemItem struct {
	ID int32 `json:"ID"`
	Name *string `json:"Name,omitempty"`
	Description *string `json:"Description,omitempty"`
	Weight *float64 `json:"Weight,omitempty"`
	Legal int32 `json:"Legal"`
	Heal int32 `json:"Heal"`
	Food int32 `json:"Food"`
	PriceMin int32 `json:"PriceMin"`
	PriceMax int32 `json:"PriceMax"`
	AllowTrade int32 `json:"AllowTrade"`
	Sync int32 `json:"Sync"`
	OnlyOnce int32 `json:"OnlyOnce"`
}

type _SystemItem SystemItem

// NewSystemItem instantiates a new SystemItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemItem(iD int32, legal int32, heal int32, food int32, priceMin int32, priceMax int32, allowTrade int32, sync int32, onlyOnce int32) *SystemItem {
	this := SystemItem{}
	this.ID = iD
	this.Legal = legal
	this.Heal = heal
	this.Food = food
	this.PriceMin = priceMin
	this.PriceMax = priceMax
	this.AllowTrade = allowTrade
	this.Sync = sync
	this.OnlyOnce = onlyOnce
	return &this
}

// NewSystemItemWithDefaults instantiates a new SystemItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemItemWithDefaults() *SystemItem {
	this := SystemItem{}
	return &this
}

// GetID returns the ID field value
func (o *SystemItem) GetID() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ID
}

// GetIDOk returns a tuple with the ID field value
// and a boolean to check if the value has been set.
func (o *SystemItem) GetIDOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ID, true
}

// SetID sets field value
func (o *SystemItem) SetID(v int32) {
	o.ID = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SystemItem) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemItem) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SystemItem) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SystemItem) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *SystemItem) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemItem) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *SystemItem) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *SystemItem) SetDescription(v string) {
	o.Description = &v
}

// GetWeight returns the Weight field value if set, zero value otherwise.
func (o *SystemItem) GetWeight() float64 {
	if o == nil || IsNil(o.Weight) {
		var ret float64
		return ret
	}
	return *o.Weight
}

// GetWeightOk returns a tuple with the Weight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemItem) GetWeightOk() (*float64, bool) {
	if o == nil || IsNil(o.Weight) {
		return nil, false
	}
	return o.Weight, true
}

// HasWeight returns a boolean if a field has been set.
func (o *SystemItem) HasWeight() bool {
	if o != nil && !IsNil(o.Weight) {
		return true
	}

	return false
}

// SetWeight gets a reference to the given float64 and assigns it to the Weight field.
func (o *SystemItem) SetWeight(v float64) {
	o.Weight = &v
}

// GetLegal returns the Legal field value
func (o *SystemItem) GetLegal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Legal
}

// GetLegalOk returns a tuple with the Legal field value
// and a boolean to check if the value has been set.
func (o *SystemItem) GetLegalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Legal, true
}

// SetLegal sets field value
func (o *SystemItem) SetLegal(v int32) {
	o.Legal = v
}

// GetHeal returns the Heal field value
func (o *SystemItem) GetHeal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Heal
}

// GetHealOk returns a tuple with the Heal field value
// and a boolean to check if the value has been set.
func (o *SystemItem) GetHealOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Heal, true
}

// SetHeal sets field value
func (o *SystemItem) SetHeal(v int32) {
	o.Heal = v
}

// GetFood returns the Food field value
func (o *SystemItem) GetFood() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Food
}

// GetFoodOk returns a tuple with the Food field value
// and a boolean to check if the value has been set.
func (o *SystemItem) GetFoodOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Food, true
}

// SetFood sets field value
func (o *SystemItem) SetFood(v int32) {
	o.Food = v
}

// GetPriceMin returns the PriceMin field value
func (o *SystemItem) GetPriceMin() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PriceMin
}

// GetPriceMinOk returns a tuple with the PriceMin field value
// and a boolean to check if the value has been set.
func (o *SystemItem) GetPriceMinOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PriceMin, true
}

// SetPriceMin sets field value
func (o *SystemItem) SetPriceMin(v int32) {
	o.PriceMin = v
}

// GetPriceMax returns the PriceMax field value
func (o *SystemItem) GetPriceMax() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PriceMax
}

// GetPriceMaxOk returns a tuple with the PriceMax field value
// and a boolean to check if the value has been set.
func (o *SystemItem) GetPriceMaxOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PriceMax, true
}

// SetPriceMax sets field value
func (o *SystemItem) SetPriceMax(v int32) {
	o.PriceMax = v
}

// GetAllowTrade returns the AllowTrade field value
func (o *SystemItem) GetAllowTrade() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AllowTrade
}

// GetAllowTradeOk returns a tuple with the AllowTrade field value
// and a boolean to check if the value has been set.
func (o *SystemItem) GetAllowTradeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AllowTrade, true
}

// SetAllowTrade sets field value
func (o *SystemItem) SetAllowTrade(v int32) {
	o.AllowTrade = v
}

// GetSync returns the Sync field value
func (o *SystemItem) GetSync() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Sync
}

// GetSyncOk returns a tuple with the Sync field value
// and a boolean to check if the value has been set.
func (o *SystemItem) GetSyncOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sync, true
}

// SetSync sets field value
func (o *SystemItem) SetSync(v int32) {
	o.Sync = v
}

// GetOnlyOnce returns the OnlyOnce field value
func (o *SystemItem) GetOnlyOnce() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.OnlyOnce
}

// GetOnlyOnceOk returns a tuple with the OnlyOnce field value
// and a boolean to check if the value has been set.
func (o *SystemItem) GetOnlyOnceOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OnlyOnce, true
}

// SetOnlyOnce sets field value
func (o *SystemItem) SetOnlyOnce(v int32) {
	o.OnlyOnce = v
}

func (o SystemItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SystemItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ID"] = o.ID
	if !IsNil(o.Name) {
		toSerialize["Name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["Description"] = o.Description
	}
	if !IsNil(o.Weight) {
		toSerialize["Weight"] = o.Weight
	}
	toSerialize["Legal"] = o.Legal
	toSerialize["Heal"] = o.Heal
	toSerialize["Food"] = o.Food
	toSerialize["PriceMin"] = o.PriceMin
	toSerialize["PriceMax"] = o.PriceMax
	toSerialize["AllowTrade"] = o.AllowTrade
	toSerialize["Sync"] = o.Sync
	toSerialize["OnlyOnce"] = o.OnlyOnce
	return toSerialize, nil
}

func (o *SystemItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ID",
		"Legal",
		"Heal",
		"Food",
		"PriceMin",
		"PriceMax",
		"AllowTrade",
		"Sync",
		"OnlyOnce",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSystemItem := _SystemItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSystemItem)

	if err != nil {
		return err
	}

	*o = SystemItem(varSystemItem)

	return err
}

type NullableSystemItem struct {
	value *SystemItem
	isSet bool
}

func (v NullableSystemItem) Get() *SystemItem {
	return v.value
}

func (v *NullableSystemItem) Set(val *SystemItem) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemItem) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemItem(val *SystemItem) *NullableSystemItem {
	return &NullableSystemItem{value: val, isSet: true}
}

func (v NullableSystemItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


