/*
Vio-V

Vio-V API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SystemGroupWar type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SystemGroupWar{}

// SystemGroupWar struct for SystemGroupWar
type SystemGroupWar struct {
	ID *string `json:"ID,omitempty"`
	Deathmatch *string `json:"Deathmatch,omitempty"`
	EndGameTimestamp *int32 `json:"EndGameTimestamp,omitempty"`
}

// NewSystemGroupWar instantiates a new SystemGroupWar object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemGroupWar() *SystemGroupWar {
	this := SystemGroupWar{}
	return &this
}

// NewSystemGroupWarWithDefaults instantiates a new SystemGroupWar object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemGroupWarWithDefaults() *SystemGroupWar {
	this := SystemGroupWar{}
	return &this
}

// GetID returns the ID field value if set, zero value otherwise.
func (o *SystemGroupWar) GetID() string {
	if o == nil || IsNil(o.ID) {
		var ret string
		return ret
	}
	return *o.ID
}

// GetIDOk returns a tuple with the ID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemGroupWar) GetIDOk() (*string, bool) {
	if o == nil || IsNil(o.ID) {
		return nil, false
	}
	return o.ID, true
}

// HasID returns a boolean if a field has been set.
func (o *SystemGroupWar) HasID() bool {
	if o != nil && !IsNil(o.ID) {
		return true
	}

	return false
}

// SetID gets a reference to the given string and assigns it to the ID field.
func (o *SystemGroupWar) SetID(v string) {
	o.ID = &v
}

// GetDeathmatch returns the Deathmatch field value if set, zero value otherwise.
func (o *SystemGroupWar) GetDeathmatch() string {
	if o == nil || IsNil(o.Deathmatch) {
		var ret string
		return ret
	}
	return *o.Deathmatch
}

// GetDeathmatchOk returns a tuple with the Deathmatch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemGroupWar) GetDeathmatchOk() (*string, bool) {
	if o == nil || IsNil(o.Deathmatch) {
		return nil, false
	}
	return o.Deathmatch, true
}

// HasDeathmatch returns a boolean if a field has been set.
func (o *SystemGroupWar) HasDeathmatch() bool {
	if o != nil && !IsNil(o.Deathmatch) {
		return true
	}

	return false
}

// SetDeathmatch gets a reference to the given string and assigns it to the Deathmatch field.
func (o *SystemGroupWar) SetDeathmatch(v string) {
	o.Deathmatch = &v
}

// GetEndGameTimestamp returns the EndGameTimestamp field value if set, zero value otherwise.
func (o *SystemGroupWar) GetEndGameTimestamp() int32 {
	if o == nil || IsNil(o.EndGameTimestamp) {
		var ret int32
		return ret
	}
	return *o.EndGameTimestamp
}

// GetEndGameTimestampOk returns a tuple with the EndGameTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemGroupWar) GetEndGameTimestampOk() (*int32, bool) {
	if o == nil || IsNil(o.EndGameTimestamp) {
		return nil, false
	}
	return o.EndGameTimestamp, true
}

// HasEndGameTimestamp returns a boolean if a field has been set.
func (o *SystemGroupWar) HasEndGameTimestamp() bool {
	if o != nil && !IsNil(o.EndGameTimestamp) {
		return true
	}

	return false
}

// SetEndGameTimestamp gets a reference to the given int32 and assigns it to the EndGameTimestamp field.
func (o *SystemGroupWar) SetEndGameTimestamp(v int32) {
	o.EndGameTimestamp = &v
}

func (o SystemGroupWar) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SystemGroupWar) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ID) {
		toSerialize["ID"] = o.ID
	}
	if !IsNil(o.Deathmatch) {
		toSerialize["Deathmatch"] = o.Deathmatch
	}
	if !IsNil(o.EndGameTimestamp) {
		toSerialize["EndGameTimestamp"] = o.EndGameTimestamp
	}
	return toSerialize, nil
}

type NullableSystemGroupWar struct {
	value *SystemGroupWar
	isSet bool
}

func (v NullableSystemGroupWar) Get() *SystemGroupWar {
	return v.value
}

func (v *NullableSystemGroupWar) Set(val *SystemGroupWar) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemGroupWar) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemGroupWar) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemGroupWar(val *SystemGroupWar) *NullableSystemGroupWar {
	return &NullableSystemGroupWar{value: val, isSet: true}
}

func (v NullableSystemGroupWar) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemGroupWar) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


