/*
Vio-V

Vio-V API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Vehicle type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Vehicle{}

// Vehicle struct for Vehicle
type Vehicle struct {
	ID int32 `json:"ID"`
	CharacterID int32 `json:"CharacterID"`
	Hash string `json:"Hash"`
	PosX string `json:"PosX"`
	PosY string `json:"PosY"`
	PosZ string `json:"PosZ"`
	RotX string `json:"RotX"`
	RotY string `json:"RotY"`
	RotZ string `json:"RotZ"`
	BuyDate time.Time `json:"BuyDate"`
	Color1R int32 `json:"Color1R"`
	Color1G int32 `json:"Color1G"`
	Color1B int32 `json:"Color1B"`
	Color2R int32 `json:"Color2R"`
	Color2G int32 `json:"Color2G"`
	Color2B int32 `json:"Color2B"`
	Spoilers int32 `json:"Spoilers"`
	FrontBumper int32 `json:"FrontBumper"`
	RearBumper int32 `json:"RearBumper"`
	SideSkirt int32 `json:"SideSkirt"`
	Exhaust int32 `json:"Exhaust"`
	Frame int32 `json:"Frame"`
	Grille int32 `json:"Grille"`
	Hood int32 `json:"Hood"`
	Fender int32 `json:"Fender"`
	RightFender int32 `json:"RightFender"`
	Roof int32 `json:"Roof"`
	Engine int32 `json:"Engine"`
	Brakes int32 `json:"Brakes"`
	Transmission int32 `json:"Transmission"`
	Horns int32 `json:"Horns"`
	Suspension int32 `json:"Suspension"`
	Armor int32 `json:"Armor"`
	Turbo int32 `json:"Turbo"`
	Xenon int32 `json:"Xenon"`
	FrontWheels int32 `json:"FrontWheels"`
	BackWheels int32 `json:"BackWheels"`
	Plateholders int32 `json:"Plateholders"`
	TrimDesign int32 `json:"TrimDesign"`
	Ornaments int32 `json:"Ornaments"`
	DialDesign int32 `json:"DialDesign"`
	SteeringWheel int32 `json:"SteeringWheel"`
	ShiftLever int32 `json:"ShiftLever"`
	Plaques int32 `json:"Plaques"`
	Hydraulics int32 `json:"Hydraulics"`
	Livery int32 `json:"Livery"`
	Plate int32 `json:"Plate"`
	WindowTint int32 `json:"WindowTint"`
	NeonStateLeft int32 `json:"NeonStateLeft"`
	NeonStateRight int32 `json:"NeonStateRight"`
	NeonStateFront int32 `json:"NeonStateFront"`
	NeonStateBack int32 `json:"NeonStateBack"`
	NeonStateColorR int32 `json:"NeonStateColorR"`
	NeonStateColorG int32 `json:"NeonStateColorG"`
	NeonStateColorB int32 `json:"NeonStateColorB"`
	Fuel string `json:"Fuel"`
	Repair int32 `json:"Repair"`
	Distance string `json:"Distance"`
	Garage int32 `json:"Garage"`
	Health int32 `json:"Health"`
	DirtLevel string `json:"DirtLevel"`
	InteriorColor int32 `json:"InteriorColor"`
	ChipTuning int32 `json:"ChipTuning"`
	PaintArt int32 `json:"PaintArt"`
	WheelColor int32 `json:"WheelColor"`
	WheelType int32 `json:"WheelType"`
	PlateText string `json:"PlateText"`
	Insurance string `json:"Insurance"`
	InsuranceExpiry int32 `json:"InsuranceExpiry"`
}

type _Vehicle Vehicle

// NewVehicle instantiates a new Vehicle object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVehicle(iD int32, characterID int32, hash string, posX string, posY string, posZ string, rotX string, rotY string, rotZ string, buyDate time.Time, color1R int32, color1G int32, color1B int32, color2R int32, color2G int32, color2B int32, spoilers int32, frontBumper int32, rearBumper int32, sideSkirt int32, exhaust int32, frame int32, grille int32, hood int32, fender int32, rightFender int32, roof int32, engine int32, brakes int32, transmission int32, horns int32, suspension int32, armor int32, turbo int32, xenon int32, frontWheels int32, backWheels int32, plateholders int32, trimDesign int32, ornaments int32, dialDesign int32, steeringWheel int32, shiftLever int32, plaques int32, hydraulics int32, livery int32, plate int32, windowTint int32, neonStateLeft int32, neonStateRight int32, neonStateFront int32, neonStateBack int32, neonStateColorR int32, neonStateColorG int32, neonStateColorB int32, fuel string, repair int32, distance string, garage int32, health int32, dirtLevel string, interiorColor int32, chipTuning int32, paintArt int32, wheelColor int32, wheelType int32, plateText string, insurance string, insuranceExpiry int32) *Vehicle {
	this := Vehicle{}
	this.ID = iD
	this.CharacterID = characterID
	this.Hash = hash
	this.PosX = posX
	this.PosY = posY
	this.PosZ = posZ
	this.RotX = rotX
	this.RotY = rotY
	this.RotZ = rotZ
	this.BuyDate = buyDate
	this.Color1R = color1R
	this.Color1G = color1G
	this.Color1B = color1B
	this.Color2R = color2R
	this.Color2G = color2G
	this.Color2B = color2B
	this.Spoilers = spoilers
	this.FrontBumper = frontBumper
	this.RearBumper = rearBumper
	this.SideSkirt = sideSkirt
	this.Exhaust = exhaust
	this.Frame = frame
	this.Grille = grille
	this.Hood = hood
	this.Fender = fender
	this.RightFender = rightFender
	this.Roof = roof
	this.Engine = engine
	this.Brakes = brakes
	this.Transmission = transmission
	this.Horns = horns
	this.Suspension = suspension
	this.Armor = armor
	this.Turbo = turbo
	this.Xenon = xenon
	this.FrontWheels = frontWheels
	this.BackWheels = backWheels
	this.Plateholders = plateholders
	this.TrimDesign = trimDesign
	this.Ornaments = ornaments
	this.DialDesign = dialDesign
	this.SteeringWheel = steeringWheel
	this.ShiftLever = shiftLever
	this.Plaques = plaques
	this.Hydraulics = hydraulics
	this.Livery = livery
	this.Plate = plate
	this.WindowTint = windowTint
	this.NeonStateLeft = neonStateLeft
	this.NeonStateRight = neonStateRight
	this.NeonStateFront = neonStateFront
	this.NeonStateBack = neonStateBack
	this.NeonStateColorR = neonStateColorR
	this.NeonStateColorG = neonStateColorG
	this.NeonStateColorB = neonStateColorB
	this.Fuel = fuel
	this.Repair = repair
	this.Distance = distance
	this.Garage = garage
	this.Health = health
	this.DirtLevel = dirtLevel
	this.InteriorColor = interiorColor
	this.ChipTuning = chipTuning
	this.PaintArt = paintArt
	this.WheelColor = wheelColor
	this.WheelType = wheelType
	this.PlateText = plateText
	this.Insurance = insurance
	this.InsuranceExpiry = insuranceExpiry
	return &this
}

// NewVehicleWithDefaults instantiates a new Vehicle object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVehicleWithDefaults() *Vehicle {
	this := Vehicle{}
	return &this
}

// GetID returns the ID field value
func (o *Vehicle) GetID() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ID
}

// GetIDOk returns a tuple with the ID field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetIDOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ID, true
}

// SetID sets field value
func (o *Vehicle) SetID(v int32) {
	o.ID = v
}

// GetCharacterID returns the CharacterID field value
func (o *Vehicle) GetCharacterID() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CharacterID
}

// GetCharacterIDOk returns a tuple with the CharacterID field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetCharacterIDOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CharacterID, true
}

// SetCharacterID sets field value
func (o *Vehicle) SetCharacterID(v int32) {
	o.CharacterID = v
}

// GetHash returns the Hash field value
func (o *Vehicle) GetHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Hash
}

// GetHashOk returns a tuple with the Hash field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hash, true
}

// SetHash sets field value
func (o *Vehicle) SetHash(v string) {
	o.Hash = v
}

// GetPosX returns the PosX field value
func (o *Vehicle) GetPosX() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PosX
}

// GetPosXOk returns a tuple with the PosX field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetPosXOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PosX, true
}

// SetPosX sets field value
func (o *Vehicle) SetPosX(v string) {
	o.PosX = v
}

// GetPosY returns the PosY field value
func (o *Vehicle) GetPosY() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PosY
}

// GetPosYOk returns a tuple with the PosY field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetPosYOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PosY, true
}

// SetPosY sets field value
func (o *Vehicle) SetPosY(v string) {
	o.PosY = v
}

// GetPosZ returns the PosZ field value
func (o *Vehicle) GetPosZ() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PosZ
}

// GetPosZOk returns a tuple with the PosZ field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetPosZOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PosZ, true
}

// SetPosZ sets field value
func (o *Vehicle) SetPosZ(v string) {
	o.PosZ = v
}

// GetRotX returns the RotX field value
func (o *Vehicle) GetRotX() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RotX
}

// GetRotXOk returns a tuple with the RotX field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetRotXOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RotX, true
}

// SetRotX sets field value
func (o *Vehicle) SetRotX(v string) {
	o.RotX = v
}

// GetRotY returns the RotY field value
func (o *Vehicle) GetRotY() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RotY
}

// GetRotYOk returns a tuple with the RotY field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetRotYOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RotY, true
}

// SetRotY sets field value
func (o *Vehicle) SetRotY(v string) {
	o.RotY = v
}

// GetRotZ returns the RotZ field value
func (o *Vehicle) GetRotZ() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RotZ
}

// GetRotZOk returns a tuple with the RotZ field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetRotZOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RotZ, true
}

// SetRotZ sets field value
func (o *Vehicle) SetRotZ(v string) {
	o.RotZ = v
}

// GetBuyDate returns the BuyDate field value
func (o *Vehicle) GetBuyDate() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.BuyDate
}

// GetBuyDateOk returns a tuple with the BuyDate field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetBuyDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BuyDate, true
}

// SetBuyDate sets field value
func (o *Vehicle) SetBuyDate(v time.Time) {
	o.BuyDate = v
}

// GetColor1R returns the Color1R field value
func (o *Vehicle) GetColor1R() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Color1R
}

// GetColor1ROk returns a tuple with the Color1R field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetColor1ROk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Color1R, true
}

// SetColor1R sets field value
func (o *Vehicle) SetColor1R(v int32) {
	o.Color1R = v
}

// GetColor1G returns the Color1G field value
func (o *Vehicle) GetColor1G() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Color1G
}

// GetColor1GOk returns a tuple with the Color1G field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetColor1GOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Color1G, true
}

// SetColor1G sets field value
func (o *Vehicle) SetColor1G(v int32) {
	o.Color1G = v
}

// GetColor1B returns the Color1B field value
func (o *Vehicle) GetColor1B() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Color1B
}

// GetColor1BOk returns a tuple with the Color1B field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetColor1BOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Color1B, true
}

// SetColor1B sets field value
func (o *Vehicle) SetColor1B(v int32) {
	o.Color1B = v
}

// GetColor2R returns the Color2R field value
func (o *Vehicle) GetColor2R() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Color2R
}

// GetColor2ROk returns a tuple with the Color2R field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetColor2ROk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Color2R, true
}

// SetColor2R sets field value
func (o *Vehicle) SetColor2R(v int32) {
	o.Color2R = v
}

// GetColor2G returns the Color2G field value
func (o *Vehicle) GetColor2G() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Color2G
}

// GetColor2GOk returns a tuple with the Color2G field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetColor2GOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Color2G, true
}

// SetColor2G sets field value
func (o *Vehicle) SetColor2G(v int32) {
	o.Color2G = v
}

// GetColor2B returns the Color2B field value
func (o *Vehicle) GetColor2B() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Color2B
}

// GetColor2BOk returns a tuple with the Color2B field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetColor2BOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Color2B, true
}

// SetColor2B sets field value
func (o *Vehicle) SetColor2B(v int32) {
	o.Color2B = v
}

// GetSpoilers returns the Spoilers field value
func (o *Vehicle) GetSpoilers() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Spoilers
}

// GetSpoilersOk returns a tuple with the Spoilers field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetSpoilersOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Spoilers, true
}

// SetSpoilers sets field value
func (o *Vehicle) SetSpoilers(v int32) {
	o.Spoilers = v
}

// GetFrontBumper returns the FrontBumper field value
func (o *Vehicle) GetFrontBumper() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.FrontBumper
}

// GetFrontBumperOk returns a tuple with the FrontBumper field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetFrontBumperOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FrontBumper, true
}

// SetFrontBumper sets field value
func (o *Vehicle) SetFrontBumper(v int32) {
	o.FrontBumper = v
}

// GetRearBumper returns the RearBumper field value
func (o *Vehicle) GetRearBumper() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RearBumper
}

// GetRearBumperOk returns a tuple with the RearBumper field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetRearBumperOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RearBumper, true
}

// SetRearBumper sets field value
func (o *Vehicle) SetRearBumper(v int32) {
	o.RearBumper = v
}

// GetSideSkirt returns the SideSkirt field value
func (o *Vehicle) GetSideSkirt() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SideSkirt
}

// GetSideSkirtOk returns a tuple with the SideSkirt field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetSideSkirtOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SideSkirt, true
}

// SetSideSkirt sets field value
func (o *Vehicle) SetSideSkirt(v int32) {
	o.SideSkirt = v
}

// GetExhaust returns the Exhaust field value
func (o *Vehicle) GetExhaust() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Exhaust
}

// GetExhaustOk returns a tuple with the Exhaust field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetExhaustOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Exhaust, true
}

// SetExhaust sets field value
func (o *Vehicle) SetExhaust(v int32) {
	o.Exhaust = v
}

// GetFrame returns the Frame field value
func (o *Vehicle) GetFrame() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Frame
}

// GetFrameOk returns a tuple with the Frame field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetFrameOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Frame, true
}

// SetFrame sets field value
func (o *Vehicle) SetFrame(v int32) {
	o.Frame = v
}

// GetGrille returns the Grille field value
func (o *Vehicle) GetGrille() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Grille
}

// GetGrilleOk returns a tuple with the Grille field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetGrilleOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Grille, true
}

// SetGrille sets field value
func (o *Vehicle) SetGrille(v int32) {
	o.Grille = v
}

// GetHood returns the Hood field value
func (o *Vehicle) GetHood() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Hood
}

// GetHoodOk returns a tuple with the Hood field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetHoodOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hood, true
}

// SetHood sets field value
func (o *Vehicle) SetHood(v int32) {
	o.Hood = v
}

// GetFender returns the Fender field value
func (o *Vehicle) GetFender() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Fender
}

// GetFenderOk returns a tuple with the Fender field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetFenderOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Fender, true
}

// SetFender sets field value
func (o *Vehicle) SetFender(v int32) {
	o.Fender = v
}

// GetRightFender returns the RightFender field value
func (o *Vehicle) GetRightFender() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RightFender
}

// GetRightFenderOk returns a tuple with the RightFender field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetRightFenderOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RightFender, true
}

// SetRightFender sets field value
func (o *Vehicle) SetRightFender(v int32) {
	o.RightFender = v
}

// GetRoof returns the Roof field value
func (o *Vehicle) GetRoof() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Roof
}

// GetRoofOk returns a tuple with the Roof field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetRoofOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Roof, true
}

// SetRoof sets field value
func (o *Vehicle) SetRoof(v int32) {
	o.Roof = v
}

// GetEngine returns the Engine field value
func (o *Vehicle) GetEngine() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Engine
}

// GetEngineOk returns a tuple with the Engine field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetEngineOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Engine, true
}

// SetEngine sets field value
func (o *Vehicle) SetEngine(v int32) {
	o.Engine = v
}

// GetBrakes returns the Brakes field value
func (o *Vehicle) GetBrakes() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Brakes
}

// GetBrakesOk returns a tuple with the Brakes field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetBrakesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Brakes, true
}

// SetBrakes sets field value
func (o *Vehicle) SetBrakes(v int32) {
	o.Brakes = v
}

// GetTransmission returns the Transmission field value
func (o *Vehicle) GetTransmission() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Transmission
}

// GetTransmissionOk returns a tuple with the Transmission field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetTransmissionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Transmission, true
}

// SetTransmission sets field value
func (o *Vehicle) SetTransmission(v int32) {
	o.Transmission = v
}

// GetHorns returns the Horns field value
func (o *Vehicle) GetHorns() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Horns
}

// GetHornsOk returns a tuple with the Horns field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetHornsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Horns, true
}

// SetHorns sets field value
func (o *Vehicle) SetHorns(v int32) {
	o.Horns = v
}

// GetSuspension returns the Suspension field value
func (o *Vehicle) GetSuspension() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Suspension
}

// GetSuspensionOk returns a tuple with the Suspension field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetSuspensionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Suspension, true
}

// SetSuspension sets field value
func (o *Vehicle) SetSuspension(v int32) {
	o.Suspension = v
}

// GetArmor returns the Armor field value
func (o *Vehicle) GetArmor() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Armor
}

// GetArmorOk returns a tuple with the Armor field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetArmorOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Armor, true
}

// SetArmor sets field value
func (o *Vehicle) SetArmor(v int32) {
	o.Armor = v
}

// GetTurbo returns the Turbo field value
func (o *Vehicle) GetTurbo() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Turbo
}

// GetTurboOk returns a tuple with the Turbo field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetTurboOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Turbo, true
}

// SetTurbo sets field value
func (o *Vehicle) SetTurbo(v int32) {
	o.Turbo = v
}

// GetXenon returns the Xenon field value
func (o *Vehicle) GetXenon() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Xenon
}

// GetXenonOk returns a tuple with the Xenon field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetXenonOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Xenon, true
}

// SetXenon sets field value
func (o *Vehicle) SetXenon(v int32) {
	o.Xenon = v
}

// GetFrontWheels returns the FrontWheels field value
func (o *Vehicle) GetFrontWheels() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.FrontWheels
}

// GetFrontWheelsOk returns a tuple with the FrontWheels field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetFrontWheelsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FrontWheels, true
}

// SetFrontWheels sets field value
func (o *Vehicle) SetFrontWheels(v int32) {
	o.FrontWheels = v
}

// GetBackWheels returns the BackWheels field value
func (o *Vehicle) GetBackWheels() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.BackWheels
}

// GetBackWheelsOk returns a tuple with the BackWheels field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetBackWheelsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BackWheels, true
}

// SetBackWheels sets field value
func (o *Vehicle) SetBackWheels(v int32) {
	o.BackWheels = v
}

// GetPlateholders returns the Plateholders field value
func (o *Vehicle) GetPlateholders() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Plateholders
}

// GetPlateholdersOk returns a tuple with the Plateholders field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetPlateholdersOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Plateholders, true
}

// SetPlateholders sets field value
func (o *Vehicle) SetPlateholders(v int32) {
	o.Plateholders = v
}

// GetTrimDesign returns the TrimDesign field value
func (o *Vehicle) GetTrimDesign() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TrimDesign
}

// GetTrimDesignOk returns a tuple with the TrimDesign field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetTrimDesignOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TrimDesign, true
}

// SetTrimDesign sets field value
func (o *Vehicle) SetTrimDesign(v int32) {
	o.TrimDesign = v
}

// GetOrnaments returns the Ornaments field value
func (o *Vehicle) GetOrnaments() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Ornaments
}

// GetOrnamentsOk returns a tuple with the Ornaments field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetOrnamentsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ornaments, true
}

// SetOrnaments sets field value
func (o *Vehicle) SetOrnaments(v int32) {
	o.Ornaments = v
}

// GetDialDesign returns the DialDesign field value
func (o *Vehicle) GetDialDesign() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DialDesign
}

// GetDialDesignOk returns a tuple with the DialDesign field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetDialDesignOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DialDesign, true
}

// SetDialDesign sets field value
func (o *Vehicle) SetDialDesign(v int32) {
	o.DialDesign = v
}

// GetSteeringWheel returns the SteeringWheel field value
func (o *Vehicle) GetSteeringWheel() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SteeringWheel
}

// GetSteeringWheelOk returns a tuple with the SteeringWheel field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetSteeringWheelOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SteeringWheel, true
}

// SetSteeringWheel sets field value
func (o *Vehicle) SetSteeringWheel(v int32) {
	o.SteeringWheel = v
}

// GetShiftLever returns the ShiftLever field value
func (o *Vehicle) GetShiftLever() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ShiftLever
}

// GetShiftLeverOk returns a tuple with the ShiftLever field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetShiftLeverOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ShiftLever, true
}

// SetShiftLever sets field value
func (o *Vehicle) SetShiftLever(v int32) {
	o.ShiftLever = v
}

// GetPlaques returns the Plaques field value
func (o *Vehicle) GetPlaques() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Plaques
}

// GetPlaquesOk returns a tuple with the Plaques field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetPlaquesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Plaques, true
}

// SetPlaques sets field value
func (o *Vehicle) SetPlaques(v int32) {
	o.Plaques = v
}

// GetHydraulics returns the Hydraulics field value
func (o *Vehicle) GetHydraulics() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Hydraulics
}

// GetHydraulicsOk returns a tuple with the Hydraulics field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetHydraulicsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hydraulics, true
}

// SetHydraulics sets field value
func (o *Vehicle) SetHydraulics(v int32) {
	o.Hydraulics = v
}

// GetLivery returns the Livery field value
func (o *Vehicle) GetLivery() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Livery
}

// GetLiveryOk returns a tuple with the Livery field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetLiveryOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Livery, true
}

// SetLivery sets field value
func (o *Vehicle) SetLivery(v int32) {
	o.Livery = v
}

// GetPlate returns the Plate field value
func (o *Vehicle) GetPlate() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Plate
}

// GetPlateOk returns a tuple with the Plate field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetPlateOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Plate, true
}

// SetPlate sets field value
func (o *Vehicle) SetPlate(v int32) {
	o.Plate = v
}

// GetWindowTint returns the WindowTint field value
func (o *Vehicle) GetWindowTint() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.WindowTint
}

// GetWindowTintOk returns a tuple with the WindowTint field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetWindowTintOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WindowTint, true
}

// SetWindowTint sets field value
func (o *Vehicle) SetWindowTint(v int32) {
	o.WindowTint = v
}

// GetNeonStateLeft returns the NeonStateLeft field value
func (o *Vehicle) GetNeonStateLeft() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NeonStateLeft
}

// GetNeonStateLeftOk returns a tuple with the NeonStateLeft field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetNeonStateLeftOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NeonStateLeft, true
}

// SetNeonStateLeft sets field value
func (o *Vehicle) SetNeonStateLeft(v int32) {
	o.NeonStateLeft = v
}

// GetNeonStateRight returns the NeonStateRight field value
func (o *Vehicle) GetNeonStateRight() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NeonStateRight
}

// GetNeonStateRightOk returns a tuple with the NeonStateRight field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetNeonStateRightOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NeonStateRight, true
}

// SetNeonStateRight sets field value
func (o *Vehicle) SetNeonStateRight(v int32) {
	o.NeonStateRight = v
}

// GetNeonStateFront returns the NeonStateFront field value
func (o *Vehicle) GetNeonStateFront() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NeonStateFront
}

// GetNeonStateFrontOk returns a tuple with the NeonStateFront field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetNeonStateFrontOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NeonStateFront, true
}

// SetNeonStateFront sets field value
func (o *Vehicle) SetNeonStateFront(v int32) {
	o.NeonStateFront = v
}

// GetNeonStateBack returns the NeonStateBack field value
func (o *Vehicle) GetNeonStateBack() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NeonStateBack
}

// GetNeonStateBackOk returns a tuple with the NeonStateBack field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetNeonStateBackOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NeonStateBack, true
}

// SetNeonStateBack sets field value
func (o *Vehicle) SetNeonStateBack(v int32) {
	o.NeonStateBack = v
}

// GetNeonStateColorR returns the NeonStateColorR field value
func (o *Vehicle) GetNeonStateColorR() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NeonStateColorR
}

// GetNeonStateColorROk returns a tuple with the NeonStateColorR field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetNeonStateColorROk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NeonStateColorR, true
}

// SetNeonStateColorR sets field value
func (o *Vehicle) SetNeonStateColorR(v int32) {
	o.NeonStateColorR = v
}

// GetNeonStateColorG returns the NeonStateColorG field value
func (o *Vehicle) GetNeonStateColorG() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NeonStateColorG
}

// GetNeonStateColorGOk returns a tuple with the NeonStateColorG field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetNeonStateColorGOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NeonStateColorG, true
}

// SetNeonStateColorG sets field value
func (o *Vehicle) SetNeonStateColorG(v int32) {
	o.NeonStateColorG = v
}

// GetNeonStateColorB returns the NeonStateColorB field value
func (o *Vehicle) GetNeonStateColorB() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NeonStateColorB
}

// GetNeonStateColorBOk returns a tuple with the NeonStateColorB field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetNeonStateColorBOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NeonStateColorB, true
}

// SetNeonStateColorB sets field value
func (o *Vehicle) SetNeonStateColorB(v int32) {
	o.NeonStateColorB = v
}

// GetFuel returns the Fuel field value
func (o *Vehicle) GetFuel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Fuel
}

// GetFuelOk returns a tuple with the Fuel field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetFuelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Fuel, true
}

// SetFuel sets field value
func (o *Vehicle) SetFuel(v string) {
	o.Fuel = v
}

// GetRepair returns the Repair field value
func (o *Vehicle) GetRepair() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Repair
}

// GetRepairOk returns a tuple with the Repair field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetRepairOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Repair, true
}

// SetRepair sets field value
func (o *Vehicle) SetRepair(v int32) {
	o.Repair = v
}

// GetDistance returns the Distance field value
func (o *Vehicle) GetDistance() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Distance
}

// GetDistanceOk returns a tuple with the Distance field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetDistanceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Distance, true
}

// SetDistance sets field value
func (o *Vehicle) SetDistance(v string) {
	o.Distance = v
}

// GetGarage returns the Garage field value
func (o *Vehicle) GetGarage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Garage
}

// GetGarageOk returns a tuple with the Garage field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetGarageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Garage, true
}

// SetGarage sets field value
func (o *Vehicle) SetGarage(v int32) {
	o.Garage = v
}

// GetHealth returns the Health field value
func (o *Vehicle) GetHealth() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Health
}

// GetHealthOk returns a tuple with the Health field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetHealthOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Health, true
}

// SetHealth sets field value
func (o *Vehicle) SetHealth(v int32) {
	o.Health = v
}

// GetDirtLevel returns the DirtLevel field value
func (o *Vehicle) GetDirtLevel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DirtLevel
}

// GetDirtLevelOk returns a tuple with the DirtLevel field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetDirtLevelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DirtLevel, true
}

// SetDirtLevel sets field value
func (o *Vehicle) SetDirtLevel(v string) {
	o.DirtLevel = v
}

// GetInteriorColor returns the InteriorColor field value
func (o *Vehicle) GetInteriorColor() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.InteriorColor
}

// GetInteriorColorOk returns a tuple with the InteriorColor field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetInteriorColorOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InteriorColor, true
}

// SetInteriorColor sets field value
func (o *Vehicle) SetInteriorColor(v int32) {
	o.InteriorColor = v
}

// GetChipTuning returns the ChipTuning field value
func (o *Vehicle) GetChipTuning() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ChipTuning
}

// GetChipTuningOk returns a tuple with the ChipTuning field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetChipTuningOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChipTuning, true
}

// SetChipTuning sets field value
func (o *Vehicle) SetChipTuning(v int32) {
	o.ChipTuning = v
}

// GetPaintArt returns the PaintArt field value
func (o *Vehicle) GetPaintArt() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PaintArt
}

// GetPaintArtOk returns a tuple with the PaintArt field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetPaintArtOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PaintArt, true
}

// SetPaintArt sets field value
func (o *Vehicle) SetPaintArt(v int32) {
	o.PaintArt = v
}

// GetWheelColor returns the WheelColor field value
func (o *Vehicle) GetWheelColor() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.WheelColor
}

// GetWheelColorOk returns a tuple with the WheelColor field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetWheelColorOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WheelColor, true
}

// SetWheelColor sets field value
func (o *Vehicle) SetWheelColor(v int32) {
	o.WheelColor = v
}

// GetWheelType returns the WheelType field value
func (o *Vehicle) GetWheelType() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.WheelType
}

// GetWheelTypeOk returns a tuple with the WheelType field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetWheelTypeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WheelType, true
}

// SetWheelType sets field value
func (o *Vehicle) SetWheelType(v int32) {
	o.WheelType = v
}

// GetPlateText returns the PlateText field value
func (o *Vehicle) GetPlateText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PlateText
}

// GetPlateTextOk returns a tuple with the PlateText field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetPlateTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlateText, true
}

// SetPlateText sets field value
func (o *Vehicle) SetPlateText(v string) {
	o.PlateText = v
}

// GetInsurance returns the Insurance field value
func (o *Vehicle) GetInsurance() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Insurance
}

// GetInsuranceOk returns a tuple with the Insurance field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetInsuranceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Insurance, true
}

// SetInsurance sets field value
func (o *Vehicle) SetInsurance(v string) {
	o.Insurance = v
}

// GetInsuranceExpiry returns the InsuranceExpiry field value
func (o *Vehicle) GetInsuranceExpiry() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.InsuranceExpiry
}

// GetInsuranceExpiryOk returns a tuple with the InsuranceExpiry field value
// and a boolean to check if the value has been set.
func (o *Vehicle) GetInsuranceExpiryOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InsuranceExpiry, true
}

// SetInsuranceExpiry sets field value
func (o *Vehicle) SetInsuranceExpiry(v int32) {
	o.InsuranceExpiry = v
}

func (o Vehicle) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Vehicle) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ID"] = o.ID
	toSerialize["CharacterID"] = o.CharacterID
	toSerialize["Hash"] = o.Hash
	toSerialize["PosX"] = o.PosX
	toSerialize["PosY"] = o.PosY
	toSerialize["PosZ"] = o.PosZ
	toSerialize["RotX"] = o.RotX
	toSerialize["RotY"] = o.RotY
	toSerialize["RotZ"] = o.RotZ
	toSerialize["BuyDate"] = o.BuyDate
	toSerialize["Color1R"] = o.Color1R
	toSerialize["Color1G"] = o.Color1G
	toSerialize["Color1B"] = o.Color1B
	toSerialize["Color2R"] = o.Color2R
	toSerialize["Color2G"] = o.Color2G
	toSerialize["Color2B"] = o.Color2B
	toSerialize["Spoilers"] = o.Spoilers
	toSerialize["FrontBumper"] = o.FrontBumper
	toSerialize["RearBumper"] = o.RearBumper
	toSerialize["SideSkirt"] = o.SideSkirt
	toSerialize["Exhaust"] = o.Exhaust
	toSerialize["Frame"] = o.Frame
	toSerialize["Grille"] = o.Grille
	toSerialize["Hood"] = o.Hood
	toSerialize["Fender"] = o.Fender
	toSerialize["RightFender"] = o.RightFender
	toSerialize["Roof"] = o.Roof
	toSerialize["Engine"] = o.Engine
	toSerialize["Brakes"] = o.Brakes
	toSerialize["Transmission"] = o.Transmission
	toSerialize["Horns"] = o.Horns
	toSerialize["Suspension"] = o.Suspension
	toSerialize["Armor"] = o.Armor
	toSerialize["Turbo"] = o.Turbo
	toSerialize["Xenon"] = o.Xenon
	toSerialize["FrontWheels"] = o.FrontWheels
	toSerialize["BackWheels"] = o.BackWheels
	toSerialize["Plateholders"] = o.Plateholders
	toSerialize["TrimDesign"] = o.TrimDesign
	toSerialize["Ornaments"] = o.Ornaments
	toSerialize["DialDesign"] = o.DialDesign
	toSerialize["SteeringWheel"] = o.SteeringWheel
	toSerialize["ShiftLever"] = o.ShiftLever
	toSerialize["Plaques"] = o.Plaques
	toSerialize["Hydraulics"] = o.Hydraulics
	toSerialize["Livery"] = o.Livery
	toSerialize["Plate"] = o.Plate
	toSerialize["WindowTint"] = o.WindowTint
	toSerialize["NeonStateLeft"] = o.NeonStateLeft
	toSerialize["NeonStateRight"] = o.NeonStateRight
	toSerialize["NeonStateFront"] = o.NeonStateFront
	toSerialize["NeonStateBack"] = o.NeonStateBack
	toSerialize["NeonStateColorR"] = o.NeonStateColorR
	toSerialize["NeonStateColorG"] = o.NeonStateColorG
	toSerialize["NeonStateColorB"] = o.NeonStateColorB
	toSerialize["Fuel"] = o.Fuel
	toSerialize["Repair"] = o.Repair
	toSerialize["Distance"] = o.Distance
	toSerialize["Garage"] = o.Garage
	toSerialize["Health"] = o.Health
	toSerialize["DirtLevel"] = o.DirtLevel
	toSerialize["InteriorColor"] = o.InteriorColor
	toSerialize["ChipTuning"] = o.ChipTuning
	toSerialize["PaintArt"] = o.PaintArt
	toSerialize["WheelColor"] = o.WheelColor
	toSerialize["WheelType"] = o.WheelType
	toSerialize["PlateText"] = o.PlateText
	toSerialize["Insurance"] = o.Insurance
	toSerialize["InsuranceExpiry"] = o.InsuranceExpiry
	return toSerialize, nil
}

func (o *Vehicle) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ID",
		"CharacterID",
		"Hash",
		"PosX",
		"PosY",
		"PosZ",
		"RotX",
		"RotY",
		"RotZ",
		"BuyDate",
		"Color1R",
		"Color1G",
		"Color1B",
		"Color2R",
		"Color2G",
		"Color2B",
		"Spoilers",
		"FrontBumper",
		"RearBumper",
		"SideSkirt",
		"Exhaust",
		"Frame",
		"Grille",
		"Hood",
		"Fender",
		"RightFender",
		"Roof",
		"Engine",
		"Brakes",
		"Transmission",
		"Horns",
		"Suspension",
		"Armor",
		"Turbo",
		"Xenon",
		"FrontWheels",
		"BackWheels",
		"Plateholders",
		"TrimDesign",
		"Ornaments",
		"DialDesign",
		"SteeringWheel",
		"ShiftLever",
		"Plaques",
		"Hydraulics",
		"Livery",
		"Plate",
		"WindowTint",
		"NeonStateLeft",
		"NeonStateRight",
		"NeonStateFront",
		"NeonStateBack",
		"NeonStateColorR",
		"NeonStateColorG",
		"NeonStateColorB",
		"Fuel",
		"Repair",
		"Distance",
		"Garage",
		"Health",
		"DirtLevel",
		"InteriorColor",
		"ChipTuning",
		"PaintArt",
		"WheelColor",
		"WheelType",
		"PlateText",
		"Insurance",
		"InsuranceExpiry",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVehicle := _Vehicle{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVehicle)

	if err != nil {
		return err
	}

	*o = Vehicle(varVehicle)

	return err
}

type NullableVehicle struct {
	value *Vehicle
	isSet bool
}

func (v NullableVehicle) Get() *Vehicle {
	return v.value
}

func (v *NullableVehicle) Set(val *Vehicle) {
	v.value = val
	v.isSet = true
}

func (v NullableVehicle) IsSet() bool {
	return v.isSet
}

func (v *NullableVehicle) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVehicle(val *Vehicle) *NullableVehicle {
	return &NullableVehicle{value: val, isSet: true}
}

func (v NullableVehicle) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVehicle) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


