/*
Vio-V

Vio-V API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GroupFactory type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupFactory{}

// GroupFactory struct for GroupFactory
type GroupFactory struct {
	ID int32 `json:"ID"`
	GroupID int32 `json:"GroupID"`
	Storage int32 `json:"Storage"`
	NextCapture int32 `json:"NextCapture"`
	CraftingStorage *int32 `json:"CraftingStorage,omitempty"`
}

type _GroupFactory GroupFactory

// NewGroupFactory instantiates a new GroupFactory object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupFactory(iD int32, groupID int32, storage int32, nextCapture int32) *GroupFactory {
	this := GroupFactory{}
	this.ID = iD
	this.GroupID = groupID
	this.Storage = storage
	this.NextCapture = nextCapture
	return &this
}

// NewGroupFactoryWithDefaults instantiates a new GroupFactory object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupFactoryWithDefaults() *GroupFactory {
	this := GroupFactory{}
	return &this
}

// GetID returns the ID field value
func (o *GroupFactory) GetID() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ID
}

// GetIDOk returns a tuple with the ID field value
// and a boolean to check if the value has been set.
func (o *GroupFactory) GetIDOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ID, true
}

// SetID sets field value
func (o *GroupFactory) SetID(v int32) {
	o.ID = v
}

// GetGroupID returns the GroupID field value
func (o *GroupFactory) GetGroupID() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.GroupID
}

// GetGroupIDOk returns a tuple with the GroupID field value
// and a boolean to check if the value has been set.
func (o *GroupFactory) GetGroupIDOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GroupID, true
}

// SetGroupID sets field value
func (o *GroupFactory) SetGroupID(v int32) {
	o.GroupID = v
}

// GetStorage returns the Storage field value
func (o *GroupFactory) GetStorage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Storage
}

// GetStorageOk returns a tuple with the Storage field value
// and a boolean to check if the value has been set.
func (o *GroupFactory) GetStorageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Storage, true
}

// SetStorage sets field value
func (o *GroupFactory) SetStorage(v int32) {
	o.Storage = v
}

// GetNextCapture returns the NextCapture field value
func (o *GroupFactory) GetNextCapture() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NextCapture
}

// GetNextCaptureOk returns a tuple with the NextCapture field value
// and a boolean to check if the value has been set.
func (o *GroupFactory) GetNextCaptureOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NextCapture, true
}

// SetNextCapture sets field value
func (o *GroupFactory) SetNextCapture(v int32) {
	o.NextCapture = v
}

// GetCraftingStorage returns the CraftingStorage field value if set, zero value otherwise.
func (o *GroupFactory) GetCraftingStorage() int32 {
	if o == nil || IsNil(o.CraftingStorage) {
		var ret int32
		return ret
	}
	return *o.CraftingStorage
}

// GetCraftingStorageOk returns a tuple with the CraftingStorage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupFactory) GetCraftingStorageOk() (*int32, bool) {
	if o == nil || IsNil(o.CraftingStorage) {
		return nil, false
	}
	return o.CraftingStorage, true
}

// HasCraftingStorage returns a boolean if a field has been set.
func (o *GroupFactory) HasCraftingStorage() bool {
	if o != nil && !IsNil(o.CraftingStorage) {
		return true
	}

	return false
}

// SetCraftingStorage gets a reference to the given int32 and assigns it to the CraftingStorage field.
func (o *GroupFactory) SetCraftingStorage(v int32) {
	o.CraftingStorage = &v
}

func (o GroupFactory) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupFactory) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ID"] = o.ID
	toSerialize["GroupID"] = o.GroupID
	toSerialize["Storage"] = o.Storage
	toSerialize["NextCapture"] = o.NextCapture
	if !IsNil(o.CraftingStorage) {
		toSerialize["CraftingStorage"] = o.CraftingStorage
	}
	return toSerialize, nil
}

func (o *GroupFactory) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ID",
		"GroupID",
		"Storage",
		"NextCapture",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGroupFactory := _GroupFactory{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGroupFactory)

	if err != nil {
		return err
	}

	*o = GroupFactory(varGroupFactory)

	return err
}

type NullableGroupFactory struct {
	value *GroupFactory
	isSet bool
}

func (v NullableGroupFactory) Get() *GroupFactory {
	return v.value
}

func (v *NullableGroupFactory) Set(val *GroupFactory) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupFactory) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupFactory) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupFactory(val *GroupFactory) *NullableGroupFactory {
	return &NullableGroupFactory{value: val, isSet: true}
}

func (v NullableGroupFactory) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupFactory) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


