/*
Vio-V

Vio-V API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InventoryItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InventoryItem{}

// InventoryItem struct for InventoryItem
type InventoryItem struct {
	// The title or category of the inventory.
	Title string `json:"title"`
	// Maximum weight capacity allowed for this inventory.
	MaxWeight float32 `json:"maxWeight"`
	// Maximum number of items allowed.
	MaxCount int32 `json:"maxCount"`
	// Identifier of the item type.
	Item int32 `json:"item"`
	// The quantity of this item currently held.
	Amount int32 `json:"amount"`
	// Additional metadata about the item, if any.
	Meta map[string]interface{} `json:"meta,omitempty"`
}

type _InventoryItem InventoryItem

// NewInventoryItem instantiates a new InventoryItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInventoryItem(title string, maxWeight float32, maxCount int32, item int32, amount int32) *InventoryItem {
	this := InventoryItem{}
	this.Title = title
	this.MaxWeight = maxWeight
	this.MaxCount = maxCount
	this.Item = item
	this.Amount = amount
	return &this
}

// NewInventoryItemWithDefaults instantiates a new InventoryItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInventoryItemWithDefaults() *InventoryItem {
	this := InventoryItem{}
	return &this
}

// GetTitle returns the Title field value
func (o *InventoryItem) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *InventoryItem) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *InventoryItem) SetTitle(v string) {
	o.Title = v
}

// GetMaxWeight returns the MaxWeight field value
func (o *InventoryItem) GetMaxWeight() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.MaxWeight
}

// GetMaxWeightOk returns a tuple with the MaxWeight field value
// and a boolean to check if the value has been set.
func (o *InventoryItem) GetMaxWeightOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxWeight, true
}

// SetMaxWeight sets field value
func (o *InventoryItem) SetMaxWeight(v float32) {
	o.MaxWeight = v
}

// GetMaxCount returns the MaxCount field value
func (o *InventoryItem) GetMaxCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaxCount
}

// GetMaxCountOk returns a tuple with the MaxCount field value
// and a boolean to check if the value has been set.
func (o *InventoryItem) GetMaxCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxCount, true
}

// SetMaxCount sets field value
func (o *InventoryItem) SetMaxCount(v int32) {
	o.MaxCount = v
}

// GetItem returns the Item field value
func (o *InventoryItem) GetItem() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Item
}

// GetItemOk returns a tuple with the Item field value
// and a boolean to check if the value has been set.
func (o *InventoryItem) GetItemOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Item, true
}

// SetItem sets field value
func (o *InventoryItem) SetItem(v int32) {
	o.Item = v
}

// GetAmount returns the Amount field value
func (o *InventoryItem) GetAmount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *InventoryItem) GetAmountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *InventoryItem) SetAmount(v int32) {
	o.Amount = v
}

// GetMeta returns the Meta field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InventoryItem) GetMeta() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InventoryItem) GetMetaOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Meta) {
		return map[string]interface{}{}, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *InventoryItem) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given map[string]interface{} and assigns it to the Meta field.
func (o *InventoryItem) SetMeta(v map[string]interface{}) {
	o.Meta = v
}

func (o InventoryItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InventoryItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["title"] = o.Title
	toSerialize["maxWeight"] = o.MaxWeight
	toSerialize["maxCount"] = o.MaxCount
	toSerialize["item"] = o.Item
	toSerialize["amount"] = o.Amount
	if o.Meta != nil {
		toSerialize["meta"] = o.Meta
	}
	return toSerialize, nil
}

func (o *InventoryItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"title",
		"maxWeight",
		"maxCount",
		"item",
		"amount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInventoryItem := _InventoryItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInventoryItem)

	if err != nil {
		return err
	}

	*o = InventoryItem(varInventoryItem)

	return err
}

type NullableInventoryItem struct {
	value *InventoryItem
	isSet bool
}

func (v NullableInventoryItem) Get() *InventoryItem {
	return v.value
}

func (v *NullableInventoryItem) Set(val *InventoryItem) {
	v.value = val
	v.isSet = true
}

func (v NullableInventoryItem) IsSet() bool {
	return v.isSet
}

func (v *NullableInventoryItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInventoryItem(val *InventoryItem) *NullableInventoryItem {
	return &NullableInventoryItem{value: val, isSet: true}
}

func (v NullableInventoryItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInventoryItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


