openapi: 3.0.3
info:
  description: Vio-V API
  title: Vio-V
  version: 1.0.0
servers:
- url: https://apiv1.vio-v.com/api/v3
- url: http://localhost:8080/api/v3
security:
- vio_auth:
  - read.group
  - read.self
  - read.company
tags:
- description: Everything about your Account
  name: own
- description: Everything about your Groups
  name: group
- description: Everything about your Company
  name: company
- description: Everything general
  name: system
paths:
  /group:
    get:
      security:
      - vio_auth:
        - read.group
      summary: Get Group Data
      tags:
      - group
  /group/members:
    get:
      security:
      - vio_auth:
        - read.group
      summary: Get Group Members Data
      tags:
      - group
  /group/ranks:
    get:
      security:
      - vio_auth:
        - read.group
      summary: Get Group Rank Data
      tags:
      - group
  /group/vehicles:
    get:
      security:
      - vio_auth:
        - read.group
      summary: Get Group Vehicles Data
      tags:
      - group
  /group/skin:
    get:
      security:
      - vio_auth:
        - read.group
      summary: Get Group Skin Data
      tags:
      - group
  /group/spraies:
    get:
      security:
      - vio_auth:
        - read.group
      summary: Get Group Spraies Data
      tags:
      - group
  /group/factories:
    get:
      security:
      - vio_auth:
        - read.group
      summary: Get Group Factories Data | Squad only!
      tags:
      - group
  /group/fairplay_blacklist:
    get:
      security:
      - vio_auth: []
      summary: Get Server Fairplay Blacklist
      tags:
      - group
  /group/own_factories:
    get:
      security:
      - vio_auth:
        - read.group
      summary: Get Group Produktion Factories Data
      tags:
      - group
  /group/areas:
    get:
      security:
      - vio_auth:
        - read.group
      summary: Get Group Areas Data (GangWars)
      tags:
      - group
  /group/storage:
    get:
      security:
      - vio_auth:
        - read.group
      summary: Get Group Storage
      tags:
      - group
  /group/storage/logs:
    get:
      security:
      - vio_auth:
        - read.group
      summary: Get Group Storage Logs
      tags:
      - group
  /group/shops:
    get:
      security:
      - vio_auth:
        - read.group
      summary: Get Group Shops
      tags:
      - group
  /self:
    get:
      security:
      - vio_auth:
        - read.self
      summary: Get Own Data
      tags:
      - own
  /self/storage:
    get:
      security:
      - vio_auth:
        - read.self
      summary: Get Own Storage
      tags:
      - own
  /self/playingtime:
    get:
      security:
      - vio_auth:
        - read.self
      summary: Get Own Playingtime statistics
      tags:
      - own
  /self/banklogs:
    get:
      security:
      - vio_auth:
        - read.self
      summary: Get Own Banklogs
      tags:
      - own
  /system/items:
    get:
      security:
      - vio_auth: []
      summary: Get Items Data
      tags:
      - system
  /system/groupwars:
    get:
      security:
      - vio_auth: []
      summary: Get GroupWars Data
      tags:
      - system
components:
  securitySchemes:
    vio_auth:
      flows:
        authorizationCode:
          authorizationUrl: /api/oauth2/authorize
          scopes:
            read.self: read character data
            read.group: read group data
            read.company: read company data
          tokenUrl: /api/oauth2/token
        clientCredentials:
          scopes:
            read.self: read character data
            read.group: read group data
            read.company: read company data
          tokenUrl: /api/oauth2/token
      type: oauth2
